@startuml
hide circle
hide methods
hide stereotype
show <<Enumeration>> stereotype
skinparam class {
   BackgroundColor<<Enumeration>> #E6F5F7
   BackgroundColor<<Ref>> #FFFFE0
   BackgroundColor<<Pivot>> #FFFFFFF
   BackgroundColor<<SimpleType>> #E2F0DA
   BackgroundColor #FCF2E3
}

class AiModelSpecification <<Pivot>> {
    deploymentRecord : object
    description : String
    href : Uri
    id : String
    inheritedModel : object
    isBundle : Boolean
    lastUpdate : DateTime
    lifecycleStatus : String
    modelContractVersionHistory : object
    modelDataSheet : object
    modelEvaluationData : object
    modelSpecificationHistory : object
    modelTrainingData : object
    name : String
    validFor : TimePeriod
    version : String
    @baseType : String
    @schemaLocation : Uri
    @type : String
}

class AttachmentRefOrValue  {
    attachmentType : String
    content : string/base64
    description : String
    href : Uri
    id : String
    mimeType : String
    name : String
    size : Quantity
    url : Uri
    validFor : TimePeriod
    @baseType : String
    @referredType : String
    @schemaLocation : Uri
    @type : String
}

class ServiceSpecRelationship  <<Ref>> {
    href : Uri
    id : String
    name : String
    relationshipType : String [1]
    role : String
    validFor : TimePeriod
    @baseType : String
    @referredType : String
    @schemaLocation : Uri
    @type : String
}

class ServiceLevelSpecificationRef  <<Ref>> {
    href : Uri
    id : String [1]
    name : String
    @baseType : String
    @referredType : String
    @schemaLocation : Uri
    @type : String
}

class TargetEntitySchema  {
    @schemaLocation : String [1]
    @type : String [1]
}

class ResourceSpecificationRef  <<Ref>> {
    href : Uri
    id : String [1]
    name : String
    version : String
    @baseType : String
    @referredType : String
    @schemaLocation : Uri
    @type : String
}

class CharacteristicSpecification  {
    configurable : Boolean
    description : String
    extensible : Boolean
    id : String
    isUnique : Boolean
    maxCardinality : Integer
    minCardinality : Integer
    name : String
    regex : String
    validFor : TimePeriod
    valueType : String
    @baseType : String
    @schemaLocation : Uri
    @type : String
    @valueSchemaLocation : String
}

class CharacteristicSpecificationRelationship  {
    characteristicSpecificationId : String
    name : String
    parentSpecificationHref : Uri
    parentSpecificationId : String
    relationshipType : String
    validFor : TimePeriod
    @baseType : String
    @schemaLocation : Uri
    @type : String
}

class CharacteristicValueSpecification  {
    isDefault : Boolean
    rangeInterval : String
    regex : String
    unitOfMeasure : String
    validFor : TimePeriod
    value : Any
    valueFrom : Integer
    valueTo : Integer
    valueType : String
    @baseType : String
    @schemaLocation : Uri
    @type : String
}

class EntitySpecificationRelationship  <<Ref>> {
    href : Uri
    id : String
    name : String
    relationshipType : String [1]
    role : String
    validFor : TimePeriod
    @baseType : String
    @referredType : String
    @schemaLocation : Uri
    @type : String
}

class AssociationSpecificationRef  <<Ref>> {
    href : Uri
    id : String [1]
    name : String
    @baseType : String
    @referredType : String
    @schemaLocation : Uri
    @type : String
}

class RelatedParty  {
    href : Uri
    id : String [1]
    name : String
    role : String
    @baseType : String
    @referredType : String [1]
    @schemaLocation : Uri
    @type : String
}

class ServiceFeatureSpecification  {
    href : Uri
    id : String
    isBundle : Boolean
    isEnabled : Boolean
    name : String
    validFor : TimePeriod
    version : String
    @baseType : String
    @schemaLocation : Uri
    @type : String
}

class FeatureSpecificationRelationship  {
    featureId : String
    name : String [1]
    parentSpecificationHref : Uri
    parentSpecificationId : String
    relationshipType : String [1]
    validFor : TimePeriod
    @baseType : String
    @schemaLocation : Uri
    @type : String
}

class ConstraintRef  <<Ref>> {
    href : Uri
    id : String [1]
    name : String
    version : String
    @baseType : String
    @referredType : String
    @schemaLocation : Uri
    @type : String
}

ConstraintRef "0..*" <--* AiModelSpecification : constraint

AiModelSpecification *-->  "0..*" CharacteristicSpecification : specCharacteristic

AiModelSpecification *-->  "0..*" ServiceFeatureSpecification : featureSpecification

ConstraintRef "0..*" <--* ServiceFeatureSpecification : constraint

ServiceFeatureSpecification *-->  "0..*" CharacteristicSpecification : featureSpecCharacteristic

AttachmentRefOrValue "0..*" <-left-* AiModelSpecification : attachment

AiModelSpecification *-right-> "0..*" RelatedParty : relatedParty

TargetEntitySchema "0..1" <--* AiModelSpecification : targetEntitySchema

ResourceSpecificationRef "0..*" <--* AiModelSpecification : resourceSpecification

ServiceSpecRelationship "0..*" <--* AiModelSpecification : serviceSpecRelationship

AiModelSpecification *-->  "0..*" ServiceLevelSpecificationRef : serviceLevelSpecification

AiModelSpecification *-->  "0..*" EntitySpecificationRelationship : entitySpecRelationship

ServiceFeatureSpecification *-right-> "0..*" FeatureSpecificationRelationship : featureSpecRelationship

CharacteristicSpecification *-->  "0..*" CharacteristicSpecificationRelationship : charSpecRelationship

CharacteristicSpecification *-->  "0..*" CharacteristicValueSpecification : characteristicValueSpecification

EntitySpecificationRelationship *-->  "0..1" AssociationSpecificationRef : associationSpec

@enduml