@startuml
hide circle
hide methods
hide stereotype
show <<Enumeration>> stereotype
skinparam class {
   BackgroundColor<<Enumeration>> #E6F5F7
   BackgroundColor<<Ref>> #FFFFE0
   BackgroundColor<<Pivot>> #FFFFFFF
   BackgroundColor<<SimpleType>> #E2F0DA
   BackgroundColor #FCF2E3
}

class BalanceDeduct <<Pivot>> {
    confirmationDate : DateTime
    deductType : String
    description : String
    href : String
    id : String
    requestedDate : DateTime
    status : String
    @baseType : String
    @schemaLocation : Uri
    @type : String
}

class ProductRef  <<Ref>> {
    href : Uri
    id : String [1]
    name : String
    @baseType : String
    @referredType : String
    @schemaLocation : Uri
    @type : String
}

class RelatedParty  {
    href : Uri
    id : String [1]
    name : String
    role : String
    @baseType : String
    @referredType : String [1]
    @schemaLocation : Uri
    @type : String
}

class PartyAccountRef  <<Ref>> {
    description : String
    href : String
    id : String [1]
    name : String
    status : String
    @baseType : String
    @referredType : String
    @schemaLocation : Uri
    @type : String
}

class BalanceReserveRef  <<Ref>> {
    href : String
    id : String [1]
    name : String
    @baseType : String
    @referredType : String
    @schemaLocation : Uri
    @type : String
}

BalanceDeduct *-right-> "0..1" ProductRef : product

PartyAccountRef "0..1" <--* BalanceDeduct : partyAccount

BalanceDeduct *-->  "0..1" RelatedParty : relatedParty

BalanceDeduct *-->  "0..1" RelatedParty : requestor

BalanceDeduct *-->  "0..1" BalanceReserveRef : balanceReserve

@enduml