@startuml
hide circle
hide methods
hide stereotype
show <<Enumeration>> stereotype
skinparam class {
   BackgroundColor<<Enumeration>> #E6F5F7
   BackgroundColor<<Ref>> #FFFFE0
   BackgroundColor<<Pivot>> #FFFFFFF
   BackgroundColor<<SimpleType>> #E2F0DA
   BackgroundColor #FCF2E3
}

class ShippingOrderProduct <<Pivot>> {
    href : Uri
    id : String
    name : String
    @baseType : String
    @referredType : String
    @schemaLocation : Uri
    @type : String
}

class Characteristic  {
    id : String
    name : String [1]
    value : Any [1]
    valueType : String
    @baseType : String
    @schemaLocation : Uri
    @type : String
}

class CharacteristicRelationship  <<Ref>> {
    href : Uri
    id : String
    relationshipType : String
    @baseType : String
    @schemaLocation : Uri
    @type : String
}

class ProductOrderItemRef  <<Ref>> {
    href : Uri
    id : String
    name : String
    productOrderId : String [1]
    @baseType : String
    @referredType : String
    @schemaLocation : Uri
    @type : String
}

ShippingOrderProduct *-right-> "0..*" Characteristic : productCharacteristic

ShippingOrderProduct *-->  "0..1" ProductOrderItemRef : productOrderItem

Characteristic *-->  "0..*" CharacteristicRelationship : characteristicRelationship

@enduml