@startuml
hide circle
hide methods
hide stereotype
show <<Enumeration>> stereotype
skinparam class {
   BackgroundColor<<Enumeration>> #E6F5F7
   BackgroundColor<<Ref>> #FFFFE0
   BackgroundColor<<Pivot>> #FFFFFFF
   BackgroundColor<<SimpleType>> #E2F0DA
   BackgroundColor #FCF2E3
}

class RatedProductUsage <<Pivot>> {
    bucketValueConvertedInAmount : Money
    isBilled : Boolean
    isTaxExempt : Boolean
    offerTariffType : String
    ratingAmountType : String
    ratingDate : DateTime
    taxExcludedRatingAmount : Money
    taxIncludedRatingAmount : Money
    taxRate : Float
    usageRatingTag : String
    @baseType : String
    @schemaLocation : Uri
    @type : String
}

class ProductRef  <<Ref>> {
    href : Uri
    id : String [1]
    name : String
    @baseType : String
    @referredType : String
    @schemaLocation : Uri
    @type : String
}

RatedProductUsage *-->  "0..1" ProductRef : productRef

@enduml