@startuml
hide circle
hide methods
hide stereotype
show <<Enumeration>> stereotype
skinparam class {
   BackgroundColor<<Enumeration>> #E6F5F7
   BackgroundColor<<Ref>> #FFFFE0
   BackgroundColor<<Pivot>> #FFFFFFF
   BackgroundColor<<SimpleType>> #E2F0DA
   BackgroundColor #FCF2E3
}

class ProcessFlow <<Pivot>> {
    href : String
    id : String
    processFlowDate : DateTime
    processFlowSpecification : String
    state : ProcessFlowStateType
    @baseType : String
    @schemaLocation : Uri
    @type : String
}

class RelatedEntity  {
    href : Uri
    id : String [1]
    name : String
    role : String [1]
    @baseType : String
    @referredType : String [1]
    @schemaLocation : Uri
    @type : String
}

class ChannelRef  <<Ref>> {
    href : Uri
    id : String [1]
    name : String
    @baseType : String
    @referredType : String
    @schemaLocation : Uri
    @type : String
}

class RelatedParty  {
    href : Uri
    id : String [1]
    name : String
    role : String
    @baseType : String
    @referredType : String [1]
    @schemaLocation : Uri
    @type : String
}

class Characteristic  {
    id : String
    name : String [1]
    value : Any [1]
    valueType : String
    @baseType : String
    @schemaLocation : Uri
    @type : String
}

class CharacteristicRelationship  <<Ref>> {
    href : Uri
    id : String
    relationshipType : String
    @baseType : String
    @schemaLocation : Uri
    @type : String
}

class TaskFlowRef  <<Ref>> {
    href : String
    id : String [1]
    @baseType : String
    @referredType : String
    @schemaLocation : Uri
    @type : String
}

class ProcessFlowStateType <<Enumeration>> {
    active
    cancelled
    hold
    completed
}

ProcessFlow -right[hidden]-> ProcessFlowStateType

ChannelRef "0..*" <-left-* ProcessFlow : channel

TaskFlowRef "0..*" <--* ProcessFlow : taskFlow

RelatedParty "0..*" <--* ProcessFlow : relatedParty

ProcessFlow *-->  "0..*" RelatedEntity : relatedEntity

ProcessFlow *-->  "0..*" Characteristic : characteristic

Characteristic *-->  "0..*" CharacteristicRelationship : characteristicRelationship

@enduml