@startuml
hide circle
hide methods
hide stereotype
show <<Enumeration>> stereotype
skinparam class {
   BackgroundColor<<Enumeration>> #E6F5F7
   BackgroundColor<<Ref>> #FFFFE0
   BackgroundColor<<Pivot>> #FFFFFFF
   BackgroundColor<<SimpleType>> #E2F0DA
   BackgroundColor #FCF2E3
}

class Customer360ProductOrderVO <<Pivot>> {
    cancellationDate : DateTime
    cancellationReason : String
    category : String
    completionDate : DateTime
    description : String
    expectedCompletionDate : DateTime
    externalId : String
    href : String
    id : String
    notificationContact : String
    orderDate : DateTime
    priority : String
    requestedCompletionDate : DateTime
    requestedStartDate : DateTime
    state : ProductOrderStateType
    @baseType : String
    @schemaLocation : Uri
    @type : String
}

class ProductOrderStateType <<Enumeration>> {
    acknowledged
    rejected
    pending
    held
    inProgress
    cancelled
    completed
    failed
    partial
    assessingCancellation
    pendingCancellation
}

Customer360ProductOrderVO -right[hidden]-> ProductOrderStateType

@enduml