= AlternateGeographicAddress

[#domain]
== Domain

This schema is part of Common

[#description]
== Description

No description on schema


[#data_model]
== Data model

A JSON Schema corresponding to this data model can be found https://tmforum.org[here].

The data model is defined as shown below:


=== href
description: An URI used to access to the address resource

type: string


=== id
description: Unique identifier of the address

type: string


=== name
description: A user-friendly name for the place, such as [Paris Store], [London Store], [Main Home]

type: string


=== role
description: Role of the place, such as: [home delivery], [shop retrieval])

type: string


=== city
description: City that the address is in

type: string


=== country
description: Country that the address is in

type: string


=== locality
description: An area of defined or undefined boundaries within a local authority or other legislatively defined area, usually rural or semi rural in nature. [ANZLIC-STREET], or a suburb, a bounded locality within a city, town or shire principally of urban character [ANZLICSTREET]

type: string


=== postcode
description: descriptor for a postal delivery area, used to speed and simplify the delivery of mail (also know as zipcode)

type: string


=== stateOrProvince
description: the State or Province that the address is in

type: string


=== streetName
description: Name of the street or other street type

type: string


=== streetNr
description: Number identifying a specific property on a public street. It may be combined with streetNrLast for ranged addresses

type: string


=== streetNrLast
description: Last number in a range of street numbers allocated to a property

type: string


=== streetNrLastSuffix
description: Last street number suffix for a ranged address

type: string


=== streetNrSuffix
description: the first street number suffix

type: string


=== streetSuffix
description: A modifier denoting a relative direction

type: string


=== streetType
description: alley, avenue, boulevard, brae, crescent, drive, highway, lane, terrace, parade, place, tarn, way, wharf 

type: string


=== geographicLocation
$ref of: xref:v4.1@schemas:Common:GeographicLocation.adoc[]


=== geographicSubAddress
type: array


[#all_of]
== All Of

This schema extends: xref:v4.1@schemas:Common:Entity.adoc[]
