= DocumentAttachment

[#domain]
== Domain

This schema is part of Common

[#description]
== Description

Attachment refers to extensions or additional parts that is or may be attached to something (agreements, contracts, appointments) to perform a particular function. They can be communication attachments, documents and other.


[#data_model]
== Data model

A JSON Schema corresponding to this data model can be found https://tmforum.org[here].

The data model is defined as shown below:


=== description
description: The description of the binary attachment

type: string


=== id
description: Identifier of the binary attachment

type: string


=== mimeType
description: mimeType of the Attachment, such as: application/pdf

type: string


=== name
description: Name of the binary attachment

type: string


=== size
description: The size of the document or attachment. If this component contains the embedded data then the size is the size of the embedded data; if it is a reference without the data then it is the size of the referenced document

type: integer


=== sizeUnit
description: The unit of measure for the size

type: string


=== attachmentType
description: Identifies the sub-type of the instance of binary attachment

type: string


=== URL
description: URL of the Attachment

type: string


=== validFor
description: Validity period of the Attachment

$ref of: xref:4.0.0@schemas:Common:TimePeriod.adoc[]


{&#x27;$ref&#x27;: &#x27;../Common/Entity.schema.json#Entity&#x27;}