= EdgeSpecificationCharacteristicRelationship

[#domain]
== Domain

This schema is part of Common

[#description]
== Description

An aggregation, migration, substitution, dependency or exclusivity relationship between/among EdgeSpecificationCharacteristics. The specification characteristic is embedded within the specification whose ID and href are in this entity, and identified by its ID.


[#data_model]
== Data model

A JSON Schema corresponding to this data model can be found https://tmforum.org[here].

The data model is defined as shown below:


=== relationshipType
description: Type of relationship such as aggregation, migration, substitution, dependency, exclusivity

type: string


=== name
description: Name of the target characteristic within the specification

type: string


=== characteristicSpecificationId
description: Unique identifier of the characteristic within the specification

type: string


=== edgeSpecificationId
description: Unique identifier of the edge specification containing the target characteristic

type: string


=== edgeSpecificationHref
description: Hyperlink reference to the edge specification containing the target characteristic

type: string


=== validFor
description: The period for which the object is valid

$ref of: xref:v4.2@schemas:Common:TimePeriod.adoc[]


= All Of 
This schema extends: xref:v4.2@schemas:Common:Extensible.adoc[]
