= ExportJob

[#domain]
== Domain

This schema is part of Common

[#description]
== Description

Represents a task used to export resources to a file


[#data_model]
== Data model

A JSON Schema corresponding to this data model can be found https://tmforum.org[here].

The data model is defined as shown below:


=== completionDate
description: Data at which the job was completed

type: string


=== contentType
description: The format of the exported data

type: string


=== creationDate
description: Date at which the job was created

type: string


=== errorLog
description: Reason for failure

type: string


=== href
description: Reference of the export job

type: string


=== id
description: Identifier of the export job

type: string


=== path
description: URL of the root resource acting as the source for streaming content to the file specified by the export job

type: string


=== query
description: Used to scope the exported data

type: string


=== status
description: Status of the export job (not started, running, succeeded, failed)

$ref of: xref:v4.0@schemas:Common:JobStateType.adoc[]


=== url
description: URL of the file containing the data to be exported

type: string


= All Of 
This schema extends: xref:v4.0@schemas:Common:Entity.adoc[]
