= MEntity

[#domain]
== Domain

This schema is part of Common

[#description]
== Description

MEntity represents an entity that describes the common set of attributes shared by all concrete entities (e.g. Resource, Service, ..) in the Entity Inventory.


[#data_model]
== Data model

A JSON Schema corresponding to this data model can be found https://tmforum.org[here].

The data model is defined as shown below:


=== description
description: free-text description of the entity

type: string


=== startDate
description: A date time( DateTime). The date from which the entity is effective

type: string


=== endDate
description: A date time( DateTime). The date till the entity is effective

type: string


=== isBundle
description: isBundle determines whether an entity represents a single entity (false), or a bundle of entities(true).

type: boolean


=== isExternal
description: isExternal determines whether an entity represents an external entity in the inventory.

type: boolean


=== status
description: The life cycle state of the entity.

type: string


=== statusChangeDate
description: A date time( DateTime). The date that the entity status changed

type: string


=== name
description: A string used to give a name to the entity

type: string


=== context
description: A string used to give a context to the entity

type: string


=== version
description: A field that identifies the specific version of an instance of an entity.

type: string


=== entitySpecification
$ref of: xref:v4.0@schemas:Common:EntitySpecificationRef.adoc[]


=== entityRelationship
description: A list of entities related to this entity

type: array


=== characteristic
type: array


=== relatedParty
type: array


=== attachment
description: Attachments that may be of relevance to this entity, such as picture, document, media

type: array


=== note
type: array


= All Of 
This schema extends: xref:v4.0@schemas:Common:Entity.adoc[]
