= ReservationItem

[#domain]
== Domain

This schema is part of Common

[#description]
== Description

An identified part of the reservation. A reservation is decomposed into one or more reservation items.


[#data_model]
== Data model

A JSON Schema corresponding to this data model can be found https://tmforum.org[here].

The data model is defined as shown below:


=== action
$ref of: xref:v4.0@schemas:Common:ReservationItemActionType.adoc[]


=== appliedCapacity
$ref of: xref:v4.0@schemas:Common:Capacity.adoc[]


=== capacityDemand
$ref of: xref:v4.0@schemas:Common:Capacity.adoc[]


=== id
description: A string. Identifier of the item.

type: string


=== quantity
type: integer


=== relatedEntity
type: array


=== relatedParty
type: array


=== reservationPeriod
description: Period of time for which the target entity is to be in a reserved state

$ref of: xref:v4.0@schemas:Common:TimePeriod.adoc[]


=== state
$ref of: xref:v4.0@schemas:Common:ReservationItemStateType.adoc[]


=== stateChangeDate
description: The date and time the state changed.

type: string


=== stateChangeReason
description: The reason for changing the state

type: string


=== validFor
$ref of: xref:v4.0@schemas:Common:TimePeriod.adoc[]


= All Of 
This schema extends: xref:v4.0@schemas:Common:Extensible.adoc[]
