= SpecificationCharacteristicRelationship

[#domain]
== Domain

This schema is part of Common

[#description]
== Description

An aggregation, migration, substitution, dependency or exclusivity relationship between/among productSpecCharacteristics.


[#data_model]
== Data model

A JSON Schema corresponding to this data model can be found https://tmforum.org[here].

The data model is defined as shown below:


=== href
description: Hyperlink reference to the target SpecificationCharacteristic

type: string


=== id
description: Unique identifier of the target SpecificationCharacteristic

type: string


=== name
description: Name of the target SpecificationCharacteristic

type: string


=== relationshipType
description: Type of relationship such as aggregation, migration, substitution, dependency, exclusivity

type: string


=== validFor
description: The period for which the SpecificationCharacteristicRelationship is valid

$ref of: xref:v4.2@schemas:Common:TimePeriod.adoc[]


[#all_of]
== All Of

This schema extends: xref:v4.2@schemas:Common:Entity.adoc[]
