= Userinfo

[#domain]
== Domain

This schema is part of Common

[#description]
== Description

TBD need to add description to entity


[#data_model]
== Data model

A JSON Schema corresponding to this data model can be found https://tmforum.org[here].

The data model is defined as shown below:


=== address
description: Structure including the End-User&#x27;s preferred postal address

$ref of: xref:4.0.0@schemas:Common:GeographicAddress.adoc[]


=== birthdate
description: End-User&#x27;s birthday, represented as an [ISO8601-2004] YYYY-MM-DD format. The year MAY be 0000, indicating that it is omitted. To represent only the year, YYYY format is allowed. Note that depending on the underlying platform&#x27;s date related function, providing just year can result in varying month and day, so the implementers need to take this factor into account to correctly process the dates

type: string


=== email
description: End-User&#x27;s preferred e-mail address. Its value MUST conform to the [RFC5322] addr-spec syntax

type: string


=== email_verified
description: True if the user&#x27;s email has been verified.

type: boolean


=== family_name
description: Surname(s) or last name(s) of the End-User. Note that in some cultures, people can have multiple family names or no family name; all can be present, with the names being separated by space characters

type: string


=== gender
description: End-User&#x27;s gender. Values defined by this specification are female and male. Other values MAY be used when neither of the defined values are applicable

type: string


=== given_name
description: Given name(s) or first name(s) of the End-User. Note that in some cultures, people can have multiple given names; all can be present, with the names being separated by space characters

type: string


=== legalId
description: Identification documentation of the contact

type: array


=== locale
description: End-User&#x27;s locale, represented as a [RFC5646] language tag. This is typically an [ISO639-1] language code in lowercase and an [ISO3166-1] country code in uppercase, separated by a dash. For example, en-US or fr-CA. As a compatibility note, some implementations have used an underscore as the separator rather than a dash, for example, en_US

type: string


=== middle_name
description: Middle name(s) of the End-User. Note that in some cultures, people can have multiple middle names; all can be present, with the names being separated by space characters. Also note that in some cultures, middle names are not used

type: string


=== name
description: End-User&#x27;s full name in displayable form including all name parts, possibly including titles and suffixes, ordered according to the End-User&#x27;s locale and preferences

type: string


=== nickname
description: Casual name of the End-User that may or may not be the same as the given_name. For instance, a nickname value of Mike might be returned alongside a given_name value of Michael

type: string


=== phone_number
description: End-User&#x27;s preferred telephone number. [E.164] is RECOMMENDED as the format of this Claim, for example, +1 (425) 555-1212 or +56 82) 687 2400. If the phone number contains an extension, it is RECOMMENDED that the extension be represented using the [RFC3966] extension syntax, for example, +1 (604) 555-1234;ext=5678

type: string


=== phone_number_verified
description: True if the user&#x27;s phone number has been verified.

type: boolean


=== picture
description: URL of the End-User&#x27;s profile picture. This URL MUST refer to an image file (for example, a PNG, JPEG, or GIF image file), rather than to a Web page containing an image. Note that this URL SHOULD specifically reference a profile photo of the End-User suitable for displaying when describing the End-User, rather than an arbitrary photo taken by the End-User

type: string


=== preferred_username
description: Shorthand name by which the End-User wishes to be referred to at the RP, such as janedoe or j.doe. This value MAY be any valid JSON string including special characters such as @, /, or whitespace

type: string


=== profile
description: URL of the End-User&#x27;s profile page. The contents of this Web page SHOULD be about the End-User

type: string


=== sub
description: Subject - Unique Identifier for the End-User

type: string


=== userAssets
description: List of additional profile information

type: array


=== website
description: URL of the End-User&#x27;s Web page or blog. This Web page SHOULD contain information published by the End-User or an organization that the End-User is affiliated with

type: string


=== zoneinfo
description: String from zoneinfo time zone database representing the End-User&#x27;s time zone. For example, Europe/Paris or America/Los_Angeles

type: string

