= VertexSpecification

[#domain]
== Domain

This schema is part of Common

[#description]
== Description

A Vertex is connected by directed Edges to other vertices in a Graph.
A VertexSpecification is a base class that represents a generic means for implementing a particular type of Vertex. In essence, a VertexSpecification defines the common attributes and relationships of a set of related Vertices, while Vertex defines a specific instance that is based on a particular VertexSpecification.


[#data_model]
== Data model

A JSON Schema corresponding to this data model can be found https://tmforum.org[here].

The data model is defined as shown below:


=== name
description: Name given to this REST resource

type: string


=== description
description: Description of this REST resource

type: string


=== version
description: Vertex Specification version

type: string


=== validFor
description: The period for which this REST resource is valid

$ref of: xref:v4.1@schemas:Common:TimePeriod.adoc[]


=== lastUpdate
description: Date and time of the last update of this REST resource

type: string


=== lifecycleStatus
description: Used to indicate the current lifecycle status of the vertex specification

type: string


=== relatedParty
description: A related party defines party or party role linked to a specific entity.

type: array


=== vertexSpecCharacteristic
description: A characteristic quality or distinctive feature of a VertexSpecification.

type: array


[#all_of]
== All Of

This schema extends: xref:v4.1@schemas:Common:Extensible.adoc[]
This schema extends: xref:v4.1@schemas:Common:Addressable.adoc[]
