@startuml
hide circle
hide methods
hide stereotype
show <<Enumeration>> stereotype
skinparam class {
   BackgroundColor<<Enumeration>> #E6F5F7
   BackgroundColor<<Ref>> #FFFFE0
   BackgroundColor<<Pivot>> #FFFFFFF
   BackgroundColor<<SimpleType>> #E2F0DA
   BackgroundColor #FCF2E3
}

class PartyRoleRiskAssessment <<Pivot>> {
    href : Uri
    id : String
    status : String
    @baseType : String
    @schemaLocation : Uri
    @type : String
}

class RiskAssessmentResult  {
    overallScore : Float
    validFor : TimePeriod
    @baseType : String
    @schemaLocation : Uri
    @type : String
}

class RiskScore  {
    riskName : RiskType
    score : Float
    @baseType : String
    @schemaLocation : Uri
    @type : String
}

class RiskType <<Enumeration>> {
    FraudRisk
    BadPaymentRisk
    CreditGamingRisk
    IDConfidenceRisk
    PaymentMethodRisk
}

class RelatedParty  {
    href : Uri
    id : String [1]
    name : String
    role : String
    @baseType : String
    @referredType : String [1]
    @schemaLocation : Uri
    @type : String
}

class RelatedPlace  {
    href : String
    id : String
    name : String
    role : String
    @baseType : String
    @referredType : String
    @schemaLocation : Uri
    @type : String
}

class Characteristic  {
    id : String
    name : String [1]
    value : Any [1]
    valueType : String
    @baseType : String
    @schemaLocation : Uri
    @type : String
}

class CharacteristicRelationship  <<Ref>> {
    href : Uri
    id : String
    relationshipType : String
    @baseType : String
    @schemaLocation : Uri
    @type : String
}

PartyRoleRiskAssessment *-right-> "0..1" RelatedPlace : place

RelatedParty "1" <--* PartyRoleRiskAssessment : partyRole

PartyRoleRiskAssessment *-->  "0..*" Characteristic : characteristic

PartyRoleRiskAssessment *-->  "0..1" RiskAssessmentResult : riskAssessmentResult

RiskAssessmentResult *-->  "0..*" RiskScore : score

Characteristic *-->  "0..*" CharacteristicRelationship : characteristicRelationship

RiskScore -right[hidden]-> RiskType

@enduml