@startuml
hide circle
hide methods
hide stereotype
show <<Enumeration>> stereotype
skinparam class {
   BackgroundColor<<Enumeration>> #E6F5F7
   BackgroundColor<<Ref>> #FFFFE0
   BackgroundColor<<Pivot>> #FFFFFFF
   BackgroundColor<<SimpleType>> #E2F0DA
   BackgroundColor #FCF2E3
}

class ProbableCause <<Enumeration>> {
    ais
    callSetUpFailure
    degradedSignal
    farEndReceiverFailure
    framingError
    lossOfFrame
    lossOfPointer
    lossOfSignal
    payloadTypeMismatch
    transmissionError
    remoteAlarmInterface
    excessiveBitErrorRate
    pathTraceMismatch
    unavailable
    signalLabelMismatch
    lossOfMultiFrame
    receiveFailure
    transmitFailure
    modulationFailure
    demodulationFailure
    broadcastChannelFailure
    connectionEstablishmentError
    invalidMessageReceived
    localNodeTransmissionError
    remoteNodeTransmissionError
    routingFailure
    backplaneFailure
    equipmentIdentifierDuplication
    externalIfDeviceProblem
    lineCardProblem
    multiplexerProblem
    neIdentifierDuplication
    processorProblem
    protectionPathFailure
    receiverFailure
    replaceableUnitMissing
    replaceableUnitTypeMismatch
    synchronizationSourceMismatch
    terminalProblem
    timingProblem
    transceiverFailure
    transmitterFailure
    trunkCardProblem
    replaceableUnitProblem
    realTimeClockFailure
    antennaFailure
    batteryChargingFailure
    diskFailure
    frequencyHoppingFailure
    ioDeviceError
    lossOfSynchronisation
    lossOfRedundancy
    powerSupplyFailure
    signalQualityEvaluationFailure
    protectionMechanismFailure
    protectingResourceFailure
    airCompressorFailure
    airConditioningFailure
    airDryerFailure
    batteryDischarging
    batteryFailure
    commercialPowerFailure
    coolingFanFailure
    engineFailure
    fireDetectorFailure
    fuseFailure
    generatorFailure
    lowBatteryThreshold
    pumpFailure
    rectifierFailure
    rectifierHighVoltage
    rectifierLowVoltage
    ventilationsSystemFailure
    enclosureDoorOpen
    explosiveGas
    fire
    flood
    highHumidity
    highTemperature
    highWind
    iceBuildUp
    intrusionDetection
    lowFuel
    lowHumidity
    lowCablePressure
    lowTemperatue
    lowWater
    smoke
    toxicGas
    coolingSystemFailure
    externalEquipmentFailure
    externalPointFailure
    storageCapacityProblem
    memoryMismatch
    corruptData
    outOfCpuCycles
    softwareEnvironmentProblem
    softwareDownloadFailure
    lossOfRealTime
    reinitialized
    applicationSubsystemFailure
    databaseInconsistency
    fileError
    outOfMemory
    softwareError
    timeoutExpired
    underlyingResourceUnavailable
    versionMismatch
    bandwidthReduced
    congestion
    excessiveResponseTime
    excessiveRetransmissionRate
    reducedLoggingCapability
    systemResourcesOverload
    adapterError
    callEstablishmentError
    communicationsProtocolError
    communicationsSubsystemFailure
    configurationOrCustomizationError
    cpuCyclesLimitExceeded
    dataSetOrModemError
    excessiveVibration
    heatingVentCoolingSystemProblem
    humidityUnacceptable
    inputOutputDeviceError
    inputDeviceError
    lanError
    leakDetected
    materialSupplyExhausted
    ouputDeviceError
    performanceDegraded
    powerProblems
    pressureUnacceptable
    queueSizeExceeded
    resourceAtOrNearingCapacity
    responseTimeExecessive
    retransmissionRateExcessive
    softwareProgramAbnormallyTerminated
    softwareProgramError
    temperatureUnacceptable
    thresholdCrossed
    toxicLeakDetected
    transmiterFailure
    authenticationFailure
    breachOfConfidentiality
    cableTamper
    delayedInformation
    denialOfService
    duplicateInformation
    informationMissing
    informationModificationDetected
    informationOutOfSequence
    keyExpired
    nonRepudiationFailure
    outOfHoursActivity
    outOfService
    proceduralError
    unauthorizedAccessAttempt
    unexpectedInformation
    other
    abisBtsInterfaceFailure
    abisTrxInterfaceFailure
    batteryBreakdown
    clockSynchronizationProblem
    combinerProblem
    equipmentFailure
    excessiveReceiverTemperature
    excessiveTransmitterOutputPower
    excessiveTransmitterTemperature
    frequencyHoppingDegraded
    frequencyRedefinitionFailed
    lineInterfaceFailure
    linkFailure
    mainsBreakdownWithBatteryBackUp
    mainsBreakdownWithoutBatteryBackUp
    receiverAntennaFault
    receiverMulticouplerFailure
    reducedTransmitterOutputPower
    timeslotHardwareFailure
    transcoderProblem
    transcoderOrRateAdapterProblem
    transmitterAntennaFailure
    transmitterAntennaNotAdjusted
    transmitterLowVoltageOrCurrent
    transmitterOffFrequency
    fileSystemCallUnsuccessful
    inputParameterOutOfRange
    invalidParameter
    invalidPointer
    messageNotExpected
    messageNotInitialized
    messageOutOfSequence
    systemCallUnsuccessful
    variableOutOfRange
    watchdogTimerExpired
    externalPowerSupplyFailure
    externalTransmissionDeviceFailure
    reducedAlarmReporting
    reducedEventReporting
    lapdLinkProtocolFailure
    localAlarmIndication
    remoteAlarmIndication
    ss7ProtocolFailure
}


@enduml