@startuml
hide circle
hide methods
hide stereotype
show <<Enumeration>> stereotype
skinparam class {
   BackgroundColor<<Enumeration>> #E6F5F7
   BackgroundColor<<Ref>> #FFFFE0
   BackgroundColor<<Pivot>> #FFFFFFF
   BackgroundColor<<SimpleType>> #E2F0DA
   BackgroundColor #FCF2E3
}

class ResourceReservationItemRef <<Pivot>> {
    href : Uri
    id : String [1]
    name : String
    resourceReservationId : String
    @baseType : String
    @referredType : String
    @schemaLocation : Uri
    @type : String
}


@enduml