@startuml
hide circle
hide methods
hide stereotype
show <<Enumeration>> stereotype
skinparam class {
   BackgroundColor<<Enumeration>> #E6F5F7
   BackgroundColor<<Ref>> #FFFFE0
   BackgroundColor<<Pivot>> #FFFFFFF
   BackgroundColor<<SimpleType>> #E2F0DA
   BackgroundColor #FCF2E3
}

class AssociationSpecification <<Pivot>> {
    description : String
    href : Uri
    id : String
    lastUpdate : DateTime
    lifecycleStatus : String
    name : String
    validFor : TimePeriod
    version : String
    @baseType : String
    @schemaLocation : Uri
    @type : String
}

class AssociationRoleSpecification  {
    aggregation : String
    defaultQuantity : Integer
    entityType : String
    isNavigable : Boolean
    isSource : Boolean
    maxQuantity : Integer
    minQuantity : Integer
    role : String
    @baseType : String
    @schemaLocation : Uri
    @type : String
}

class ConstraintRef  <<Ref>> {
    href : Uri
    id : String [1]
    name : String
    version : String
    @baseType : String
    @referredType : String
    @schemaLocation : Uri
    @type : String
}

AssociationSpecification *-->  "0..1" AssociationRoleSpecification : associationRoleSpec

AssociationSpecification *-->  "0..*" ConstraintRef : constraint

@enduml