@startuml
hide circle
hide methods
hide stereotype
show <<Enumeration>> stereotype
skinparam class {
   BackgroundColor<<Enumeration>> #E6F5F7
   BackgroundColor<<Ref>> #FFFFE0
   BackgroundColor<<Pivot>> #FFFFFFF
   BackgroundColor<<SimpleType>> #E2F0DA
   BackgroundColor #FCF2E3
}

class PartyPrivacyProfileSpecification <<Pivot>> {
    description : String
    href : String
    id : String
    lastUpdate : DateTime
    name : String
    status : String
    validFor : TimePeriod
    version : String
}

class ProductOfferingRef  <<Ref>> {
    href : Uri
    id : String [1]
    name : String
    @baseType : String
    @referredType : String
    @schemaLocation : Uri
    @type : String
}

class PartyPrivacyProfileSpecificationCharacteristic  {
    criticalityLevel : String
    description : String
    id : String
    name : String
    privacyType : String
    privacyUsagePurpose : String
    validFor : TimePeriod
}

class RoleSpecification  {
    description : String
    href : Uri
    id : String
    name : String [1]
    @baseType : String
    @schemaLocation : Uri
    @type : String
}

class SpecificationCharacteristicValue  {
    href : Uri
    id : String
    isDefault : Boolean
    rangeInterval : String
    regex : String
    unitOfMeasure : String
    validFor : TimePeriod
    value : Any
    valueFrom : Integer
    valueTo : Integer
    valueType : String
    @baseType : String
    @schemaLocation : Uri
    @type : String
}

class PartyPrivacyRoleSpecification  {
    description : String
    href : Uri
    id : String
    name : String [1]
    @baseType : String
    @schemaLocation : Uri
    @type : String
}

class AgreementSpecificationRef  <<Ref>> {
    description : String
    href : Uri
    id : String [1]
    name : String
    @baseType : String
    @referredType : String
    @schemaLocation : Uri
    @type : String
}

class RelatedParty  {
    href : Uri
    id : String [1]
    name : String
    role : String
    @baseType : String
    @referredType : String [1]
    @schemaLocation : Uri
    @type : String
}

PartyPrivacyProfileSpecification *-right-> "0..*" RelatedParty : relatedParty

ProductOfferingRef "0..*" <--* PartyPrivacyProfileSpecification : productOffering

PartyPrivacyProfileSpecification *-->  "0..*" PartyPrivacyRoleSpecification : applicableRole

PartyPrivacyProfileSpecification *-->  "0..*" PartyPrivacyProfileSpecificationCharacteristic : partyPrivacyProfileSpecCharacteristic

PartyPrivacyProfileSpecificationCharacteristic *-->  "0..*" SpecificationCharacteristicValue : partyPrivacyProfileSpecCharacteristicValue

PartyPrivacyProfileSpecificationCharacteristic *-->  "0..*" RoleSpecification : allowedRole

PartyPrivacyRoleSpecification *-->  "0..*" AgreementSpecificationRef : agreementSpecification

@enduml