@startuml
hide circle
hide methods
hide stereotype
show <<Enumeration>> stereotype
skinparam class {
   BackgroundColor<<Enumeration>> #E6F5F7
   BackgroundColor<<Ref>> #FFFFE0
   BackgroundColor<<Pivot>> #FFFFFFF
   BackgroundColor<<SimpleType>> #E2F0DA
   BackgroundColor #FCF2E3
}

class Partnership <<Pivot>> {
    description : String
    href : String
    id : String
    name : String [1]
    @baseType : String
    @schemaLocation : Uri
    @type : String
}

class Partner  {
    href : String
    id : String
    name : String [1]
    status : String
    statusReason : String
    validFor : TimePeriod
    @baseType : String
    @schemaLocation : Uri
    @type : String
}

class ContactMedium  {
    href : Uri
    id : String
    mediumType : String
    preferred : Boolean
    validFor : TimePeriod
    @baseType : String
    @schemaLocation : Uri
    @type : String
}

class MediumCharacteristic  {
    city : String
    contactType : String
    country : String
    emailAddress : String
    faxNumber : String
    href : Uri
    id : String
    phoneNumber : String
    postCode : String
    socialNetworkId : String
    stateOrProvince : String
    street1 : String
    street2 : String
    @baseType : String
    @schemaLocation : Uri
    @type : String
}

class CreditProfile  {
    creditProfileDate : DateTime
    creditRiskRating : Integer
    creditScore : Integer
    href : Uri
    id : String
    validFor : TimePeriod
    @baseType : String
    @schemaLocation : Uri
    @type : String
}

class AgreementRef  <<Ref>> {
    href : Uri
    id : String [1]
    name : String
    @baseType : String
    @referredType : String
    @schemaLocation : Uri
    @type : String
}

class RelatedParty  {
    href : Uri
    id : String [1]
    name : String
    role : String
    @baseType : String
    @referredType : String [1]
    @schemaLocation : Uri
    @type : String
}

class Characteristic  {
    id : String
    name : String [1]
    value : Any [1]
    valueType : String
    @baseType : String
    @schemaLocation : Uri
    @type : String
}

class CharacteristicRelationship  <<Ref>> {
    href : Uri
    id : String
    relationshipType : String
    @baseType : String
    @schemaLocation : Uri
    @type : String
}

class PaymentMethodRef  <<Ref>> {
    href : Uri
    id : String [1]
    name : String
    @baseType : String
    @referredType : String
    @schemaLocation : Uri
    @type : String
}

class AccountRef  <<Ref>> {
    description : String
    href : String
    id : String [1]
    name : String
    @baseType : String
    @referredType : String
    @schemaLocation : Uri
    @type : String
}

class PartnershipSpecificationRef  <<Ref>> {
    href : String
    id : String [1]
    name : String
    @baseType : String
    @referredType : String
    @schemaLocation : Uri
    @type : String
}

AccountRef "0..*" <-left-* Partner : account

Partner *-right-> "0..*" AgreementRef : agreement

CreditProfile "0..*" <--* Partner : creditProfile

PaymentMethodRef "0..*" <--* Partner : paymentMethod

Partner *-->  "1" RelatedParty : engagedParty

Partner *-->  "0..*" RelatedParty : relatedParty

Partner *-->  "0..*" ContactMedium : contactMedium

Partner *-->  "0..*" Characteristic : characteristic

Partner "0..*" <--* Partnership : partner

Partnership *-->  "1" PartnershipSpecificationRef : specification

ContactMedium *-->  "0..1" MediumCharacteristic : characteristic

Characteristic *-->  "0..*" CharacteristicRelationship : characteristicRelationship

@enduml