@startuml
hide circle
hide methods
hide stereotype
show <<Enumeration>> stereotype
skinparam class {
   BackgroundColor<<Enumeration>> #E6F5F7
   BackgroundColor<<Ref>> #FFFFE0
   BackgroundColor<<Pivot>> #FFFFFFF
   BackgroundColor<<SimpleType>> #E2F0DA
   BackgroundColor #FCF2E3
}

class AgreementItem <<Pivot>> {
    href : Uri
    id : String
    @baseType : String
    @schemaLocation : Uri
    @type : String
}

class AgreementTermOrCondition  {
    description : String
    href : Uri
    id : String
    validFor : TimePeriod
    @baseType : String
    @schemaLocation : Uri
    @type : String
}

class ProductRef  <<Ref>> {
    href : Uri
    id : String [1]
    name : String
    @baseType : String
    @referredType : String
    @schemaLocation : Uri
    @type : String
}

class ProductOfferingRef  <<Ref>> {
    href : Uri
    id : String [1]
    name : String
    @baseType : String
    @referredType : String
    @schemaLocation : Uri
    @type : String
}

AgreementItem *-->  "0..*" ProductOfferingRef : productOffering

AgreementItem *-->  "0..*" AgreementTermOrCondition : termOrCondition

AgreementItem *-->  "0..*" ProductRef : product

@enduml