@startuml
hide circle
hide methods
hide stereotype
show <<Enumeration>> stereotype
skinparam class {
   BackgroundColor<<Enumeration>> #E6F5F7
   BackgroundColor<<Ref>> #FFFFE0
   BackgroundColor<<Pivot>> #FFFFFFF
   BackgroundColor<<SimpleType>> #E2F0DA
   BackgroundColor #FCF2E3
}

class ServiceSpecCharacteristic <<Pivot>> {
    configurable : Boolean
    description : String
    extensible : Boolean
    href : Uri
    id : String
    isUnique : Boolean
    maxCardinality : Integer
    minCardinality : Integer
    name : String
    regex : String
    validFor : TimePeriod
    valueType : String
    @baseType : String
    @schemaLocation : Uri
    @type : String
    @valueSchemaLocation : String
}

class ServiceSpecCharacteristicValue  {
    href : Uri
    id : String
    isDefault : Boolean
    rangeInterval : String
    regex : String
    unitOfMeasure : String
    validFor : TimePeriod
    value : Any
    valueFrom : Integer
    valueTo : Integer
    valueType : String
    @baseType : String
    @schemaLocation : Uri
    @type : String
}

class ServiceSpecCharRelationship  <<Ref>> {
    href : String
    id : String
    name : String
    relationshipType : String
    role : String
    validFor : TimePeriod
    @baseType : String
    @schemaLocation : Uri
    @type : String
}

ServiceSpecCharacteristic *-->  "0..*" ServiceSpecCharacteristicValue : serviceSpecCharacteristicValue

ServiceSpecCharacteristic *-->  "0..*" ServiceSpecCharRelationship : serviceSpecCharRelationship

@enduml