@startuml
hide circle
hide methods
hide stereotype
show <<Enumeration>> stereotype
skinparam class {
   BackgroundColor<<Enumeration>> #E6F5F7
   BackgroundColor<<Ref>> #FFFFE0
   BackgroundColor<<Pivot>> #FFFFFFF
   BackgroundColor<<SimpleType>> #E2F0DA
   BackgroundColor #FCF2E3
}

class ProblemUngroup <<Pivot>> {
    href : String
    id : String
    @baseType : String
    @schemaLocation : Uri
    @type : String
}

class ServiceProblemRef  <<Ref>> {
    href : Uri
    id : String [1]
    name : String
    @baseType : String
    @referredType : String
    @schemaLocation : Uri
    @type : String
}

ProblemUngroup *-->  "0..1" ServiceProblemRef : parentProblem

ProblemUngroup *-->  "0..*" ServiceProblemRef : childProblem

@enduml