@startuml
hide circle
hide methods
hide stereotype
show <<Enumeration>> stereotype
skinparam class {
   BackgroundColor<<Enumeration>> #E6F5F7
   BackgroundColor<<Ref>> #FFFFE0
   BackgroundColor<<Pivot>> #FFFFFFF
   BackgroundColor<<SimpleType>> #E2F0DA
   BackgroundColor #FCF2E3
}

class Heal <<Pivot>> {
    cause : String [1]
    degreeOfHealing : String [1]
    healAction : String
    href : Uri
    id : String
    name : String
    startTime : String
    state : TaskStateType
    @baseType : String
    @schemaLocation : Uri
    @type : String
}

class HealPolicyRef  <<Ref>> {
    href : Uri
    id : String [1]
    name : String
    @baseType : String
    @referredType : String
    @schemaLocation : Uri
    @type : String
}

class ResourceFunctionRef  <<Ref>> {
    href : Uri
    id : String [1]
    name : String
    version : String
    @baseType : String
    @referredType : String
    @schemaLocation : Uri
    @type : String
}

class TaskStateType <<Enumeration>> {
    accepted
    terminatedWithError
    inProgress
    done
}

class Characteristic  {
    id : String
    name : String [1]
    value : Any [1]
    valueType : String
    @baseType : String
    @schemaLocation : Uri
    @type : String
}

class CharacteristicRelationship  <<Ref>> {
    href : Uri
    id : String
    relationshipType : String
    @baseType : String
    @schemaLocation : Uri
    @type : String
}

Heal -right[hidden]-> TaskStateType

Heal *-->  "0..1" HealPolicyRef : healPolicy

Heal *-->  "1" ResourceFunctionRef : resourceFunction

Heal *-->  "0..*" Characteristic : additionalParms

Characteristic *-->  "0..*" CharacteristicRelationship : characteristicRelationship

@enduml