= Customer360UsageSpecificationVO

[#domain]
== Domain

This schema is part of Customer360

[#description]
== Description
A detailed description of a usage event that are of interest to the business and can have charges applied to it. It is comprised of characteristics, which define all attributes known for a particular type of usage.


[#data_model]
== Data model

A JSON Schema corresponding to this data model can be found https://tmforum.org[here].

The data model is defined as shown below:


=== description
description: A narrative that explains in detail what the usage specification is

type: string


=== href
description: Reference of usage specification

type: string


=== id
description: Usage specification unique identifier

type: string


=== name
description: The name of the usage specification.

type: string


=== validFor
description: The period for which the usage specification is valid

$ref of: xref:4.0.0@schemas:Customer360:TimePeriod.adoc[]


=== usageSpecCharacteristic
type: array

