@startuml
hide circle
hide methods
hide stereotype
show <<Enumeration>> stereotype
skinparam class {
   BackgroundColor<<Enumeration>> #E6F5F7
   BackgroundColor<<Ref>> #FFFFE0
   BackgroundColor<<Pivot>> #FFFFFFF
   BackgroundColor<<SimpleType>> #E2F0DA
   BackgroundColor #FCF2E3
}

class BaseEvent <<Pivot>> {
    correlationId : String
    description : String
    domain : String
    event : Any
    eventId : String
    eventTime : DateTime
    eventType : String
    href : Uri
    id : String
    priority : String
    timeOcurred : DateTime
    title : String
    @baseType : String
    @schemaLocation : Uri
    @type : String
}


@enduml