= IOTObservationAnalytics

[#domain]
== Domain

This schema is part of Analytics

[#description]
== Description

No description on schema


[#data_model]
== Data model

A JSON Schema corresponding to this data model can be found https://tmforum.org[here].

The data model is defined as shown below:


=== observationStartDatetime
description: End datetime of the observation

type: string


=== observationSentDatetime
description: Datetime when the observation was sent to recepient

type: string


=== observationReceivedDatetime
description: Datetime when the observation was received by recepient

type: string


=== dataCreationTimestamp
description: Time stamp for data creation (e.g. system dump creation, event generation…)

type: string


=== runTimestamp
description: Time stamp for data upload run

type: string


=== validFromTimestamp
description: Time stamp for business validity of entity record

type: string


= All Of 
This schema extends: xref:4.0.0@schemas:Analytics:Entity.adoc[]
