= PaymentAnalytics

[#domain]
== Domain

This schema is part of Analytics

[#description]
== Description

No description on schema


[#data_model]
== Data model

A JSON Schema corresponding to this data model can be found https://tmforum.org[here].

The data model is defined as shown below:


=== paymentDueAmount
description: Payment due amount

type: number


=== paymentDueDate
description: Payment due date

type: string


=== paymentPaidAmount
description: Payment paid amount

type: number


=== paymentPaidDate
description: Payment paid date

type: string


=== paymentPaidPostingDate
description: Posting date for payment paid

type: string


=== paymentPaidValueDate
description: Value date for payment paid

type: string


=== paymentPaidDiscountAmount
description: Cash discount granted for clearing

type: number


=== bankCountryCode
description: Bank country key

type: number


=== bankNumber
description: Bank number

type: number


=== bankAccountNumber
description: Bank account number

type: number


=== iban
description: IBAN (International Bank Account Number)

type: number


=== swift
description: SWIFT Code / Bank Identifier Code (BIC)

type: number


=== paymentCardNumber
description: Payment card number

type: number


=== paymentCardValidFromDate
description: Payment card valid from

type: string


=== paymentCardValidToDate
description: Payment card valid to

type: string


=== paymentCardAuthorizationNumber
description: Payment card authorization number

type: number


=== paymentCardAuthorizationDate
description: Payment card authorization date

type: string


=== checkNumber
description: Check number

type: number


=== paymentInstallmentNumber
description: Payment number within payments associated with the same installment

type: number


=== invoiceReferenceIssueDate
description: Date of invoice associated with this payment

type: string


=== customerStatusDate
description: Date when status was set or changed last time

type: string


=== customerCreationDate
description: Date when customer was created

type: string


=== customerBirthDate
description: Date of birth

type: string


=== arpuAmount
$ref of: xref:4.0.0@schemas:Analytics:Money.adoc[]


=== accountStatusDate
description: Status last change date

type: string


=== accountCreationDate
description: Account creation Date

type: string


=== dataCreationTimestamp
description: Time stamp for data creation (e.g. system dump creation, event generation…)

type: string


=== runTimestamp
description: Time stamp for data upload run

type: string


=== validFromTimestamp
description: Time stamp for business validity of entity record

type: string


= All Of 
