@startuml
hide circle
hide methods
hide stereotype
show <<Enumeration>> stereotype
skinparam class {
   BackgroundColor<<Enumeration>> #E6F5F7
   BackgroundColor<<Ref>> #FFFFE0
   BackgroundColor<<Pivot>> #FFFFFFF
   BackgroundColor<<SimpleType>> #E2F0DA
   BackgroundColor #FCF2E3
}

class TestInfo <<Pivot>> {
    termsOfService : String
}

class License  {
    name : String
    url : Uri
}

class Multilingual  {

}

class Attribute  {
    description : String
}

class Characteristic  {
    id : String
    name : String [1]
    value : Any [1]
    valueType : String
    @baseType : String
    @schemaLocation : Uri
    @type : String
}

class CharacteristicRelationship  <<Ref>> {
    href : Uri
    id : String
    relationshipType : String
    @baseType : String
    @schemaLocation : Uri
    @type : String
}

TestInfo *-->  "0..1" License : license

TestInfo *-->  "1" Multilingual : description

TestInfo *-->  "0..*" Attribute : attributes

Attribute *-right-> "0..1" Characteristic : characteristic

Characteristic *-->  "0..*" CharacteristicRelationship : characteristicRelationship

@enduml