= AccumulatedBalance

[#domain]
== Domain

This schema is part of Customer

[#description]
== Description

Represents and tracks the aggregated amount remained or owed in certain account which is owned by certain customer for a set of buckets.


[#data_model]
== Data model

A JSON Schema corresponding to this data model can be found https://tmforum.org[here].

The data model is defined as shown below:


=== href
description: A resource URI pointing to the resource in the OB that stores the detailed information.

type: string


=== id
description: Unique Identifier within the server for the recharge operation request

type: string


=== bucket
description: A reference to the buckets involved in the aggregation

type: array


=== logicalResource
type: array


=== description
description: Text describing the contents of the aggregated balance

type: string


=== name
description: Friendly name to identify the aggregated balance

type: string


=== partyAccount
description: A reference to the account that owns the buckets aggregated

$ref of: xref:v4.2@schemas:Customer:PartyAccountRef.adoc[]


=== product
description: A reference to the product whose consumption is managed by the bucket . This is an array to allow scenarios where a buckets are shared between different products

type: array


=== relatedParty
description: Used to provide information about any other entity with relation to the balance, for instance to define customer hierarchy for the balance (e.g.: customerId, userId, )

type: array


=== totalBalance
description: Aggregated for a set of prepay balance buckets associated to the product

$ref of: xref:v4.2@schemas:Customer:Quantity.adoc[]


= All Of 
This schema extends: xref:v4.2@schemas:Customer:Entity.adoc[]
