= AppliedPartyBillingRate

[#domain]
== Domain

This schema is part of Customer

[#description]
== Description

An applied billing rate presented on a party bill. It is created before or during the billing process.


[#data_model]
== Data model

A JSON Schema corresponding to this data model can be found https://tmforum.org[here].

The data model is defined as shown below:


=== date
description: Creation date of the applied billing charge

type: string


=== description
description: Additional data to be displayed on the bill for this applied billing charge

type: string


=== href
description: Reference of the applied billing charge

type: string


=== id
description: Unique identifier of the applied billing charge

type: string


=== name
description: Name of the applied billing rate

type: string


=== taxExcludedAmount
description: Tax excluded amount to be charged on the bill (expresses in the given currency) for this applied billing rate

$ref of: xref:4.0.0@schemas:Customer:Money.adoc[]


=== taxIncludedAmount
description: All taxes included amount to be charged on the bill (expressed in the given currency) for this applied billing rate

$ref of: xref:4.0.0@schemas:Customer:Money.adoc[]


=== rateType
description: Type of the applied billing rate : appliedBillingCharge (any kind of charge except taxation charges : recurringCharge, oneTimeCharge, usageCharge),  appliedBillingCredit (any kind of credit : rebate or productAlteration) or appliedPenaltyCharge (penalty charges such as late fees, payment rejection fees,...)

type: string


=== appliedTax
type: array


=== bill
$ref of: xref:4.0.0@schemas:Customer:BillRef.adoc[]


=== characteristic
type: array


{&#x27;$ref&#x27;: &#x27;../Common/Entity.schema.json#Entity&#x27;}