= BalanceTransfer

[#domain]
== Domain

This schema is part of Customer

[#description]
== Description

The BalanceTransfer resource is a detailed description of credit transfer operation requested between two buckets (reference to products owned by customers and consuming credit when using a service).


[#data_model]
== Data model

A JSON Schema corresponding to this data model can be found https://tmforum.org[here].

The data model is defined as shown below:


=== id
description: Unique Identifier within the server for the balance transfer operation request.

type: string


=== href
description: A resource URI pointing to the resource in the OB that stores the detailed information. This is typically the resource url to retrieve individual transfer operation details

type: string


=== type
description: A preconfigured value that describes a Transfer type which determines the prepay balance bucket in which the transfer is done (national-voice, roaming-voice, promotional-voice, data, ....)

type: string


=== description
description: Description of the transfer operation

type: string


=== reason
description: Text describing the reason for the adjustment

type: string


=== channel
description: Indicator for the channel used to request the transfer operation. Structure including at least attribute name

$ref of: xref:v4.2@schemas:Customer:ChannelRef.adoc[]


=== requestor
description: Identifier for the user/customer/entity that performs the transfer action.This can be used to indicate the identifier of an agent that performs the operation on behalf of a user via a customer service channel Structure including at least attributes “role” and “name”

$ref of: xref:v4.2@schemas:Customer:RelatedParty.adoc[]


=== targetId
description: Identifier for the entity that receives the transfer (reference to a product via a commercial identifier such as an msisidn that relates to an internal product id)

type: string


=== targetType
description: Intended for scenarios where the transfer is done from one bucket type to another (from voice to data). A preconfigured value that describes a Transfer type which determines the prepay balance bucket in which the transfer is done

type: string


=== receiver
description: Identifier for the user/customer/entity that receives the transfer action when it is required to indicate additional customer hierarchy information regarding the entity receiving the balance transfer Structure including at least attributes “role” and “name”

$ref of: xref:v4.2@schemas:Customer:RelatedParty.adoc[]


=== amount
description: Amount (can be monetary or non-monetary) to be transferred

$ref of: xref:v4.2@schemas:Customer:Quantity.adoc[]


=== transferCost
description: Associated cost to be charged for the transfer operation (can be monetary or non-monetary)

$ref of: xref:v4.2@schemas:Customer:Quantity.adoc[]


=== product
description: A reference to the product related to the bucket that is impacted by the balance related operation

$ref of: xref:v4.2@schemas:Customer:ProductRef.adoc[]


=== sourceBucketBalance
description: A reference to the source bucketBalance from which the funds are being transferred 

$ref of: xref:v4.2@schemas:Customer:BucketBalanceRef.adoc[]


=== targetBucketBalance
description: A reference to the target bucketBalance to which the funds are being transferred 

$ref of: xref:v4.2@schemas:Customer:BucketBalanceRef.adoc[]


=== partyAccount
description: A reference to the account that owns the bucket impacted by the balance transfer request

$ref of: xref:v4.2@schemas:Customer:PartyAccountRef.adoc[]


=== relatedParty
description: Used to provide information about any other entity with relation to the balance transfer

type: array


= All Of 
This schema extends: xref:v4.2@schemas:Customer:BalanceAction.adoc[]
