= BalanceDeductRollback

[#domain]
== Domain

This schema is part of Customer

[#description]
== Description
The Rollback Balance Deduct task resource is a detailed description of rollback deduction


[#data_model]
== Data model

A JSON Schema corresponding to this data model can be found https://tmforum.org[here].

The data model is defined as shown below:


=== description
description: Description of the rollback deduct operation

type: string


=== href
description: A resource URI pointing to the resource in the OB that stores the detailed information about a rollback deduction

type: string


=== id
description: Unique Identifier within the server for the rollback deduction  operation request

type: string


=== requestedDate
description: Date when the rollback deduction request was received in the server

type: string


=== status
description: Status of the rollback deduction operation

type: string


=== relatedParty
$ref of: xref:4.0.0@schemas:Customer:RelatedParty.adoc[]


=== product
$ref of: xref:4.0.0@schemas:Customer:ProductRef.adoc[]


=== partyAccount
$ref of: xref:4.0.0@schemas:Customer:PartyAccountRef.adoc[]


=== balanceDeduct
$ref of: xref:4.0.0@schemas:Customer:BalanceDeductRef.adoc[]


=== requestor
$ref of: xref:4.0.0@schemas:Customer:RelatedParty.adoc[]

