= OrderItemPrice

[#domain]
== Domain

This schema is part of Customer

[#description]
== Description

An amount, usually of money, that represents the actual price paid by the Customer for this item or this order


[#data_model]
== Data model

A JSON Schema corresponding to this data model can be found https://tmforum.org[here].

The data model is defined as shown below:


=== description
description: A narrative that explains in detail the semantics of this order item price.

type: string


=== name
description: Name of the order item price

type: string


=== productOfferingPrice
$ref of: xref:4.0.0@schemas:Customer:ProductOfferingPriceRef.adoc[]


=== priceType
description: A category that describes the price, such as recurring, discount, allowance, penalty, and so forth

type: string


=== recurringChargePeriod
description: Could be month, week...

type: string


=== unitOfMeasure
description: Could be minutes, GB...

type: string


=== billingAccount
$ref of: xref:4.0.0@schemas:Customer:BillingAccountRef.adoc[]


=== price
$ref of: xref:4.0.0@schemas:Customer:Price.adoc[]


=== priceAlteration
type: array


{&#x27;$ref&#x27;: &#x27;../Common/Entity.schema.json#Entity&#x27;}