= ProductOrderItem

[#domain]
== Domain

This schema is part of Customer

[#description]
== Description

An identified part of the order. A product order is decomposed into one or more order items.


[#data_model]
== Data model

A JSON Schema corresponding to this data model can be found https://tmforum.org[here].

The data model is defined as shown below:


=== id
description: Identifier of the line item (generally it is a sequence number 01, 02, 03, ...)

type: string


=== quantity
description: Quantity ordered

type: integer


=== action
description: The action to be carried out on the Product. Can be: add, modify, delete, noChange

$ref of: xref:4.0.0@schemas:Customer:OrderItemActionType.adoc[]


=== appointment
$ref of: xref:4.0.0@schemas:Customer:AppointmentRef.adoc[]


=== billingAccount
$ref of: xref:4.0.0@schemas:Customer:BillingAccountRef.adoc[]


=== itemPrice
type: array


=== itemTerm
type: array


=== itemTotalPrice
type: array


=== payment
type: array


=== product
$ref of: xref:4.0.0@schemas:Customer:ProductRefOrValue.adoc[]


=== productOffering
$ref of: xref:4.0.0@schemas:Customer:ProductOfferingRef.adoc[]


=== productOfferingQualificationItem
$ref of: xref:4.0.0@schemas:Customer:ProductOfferingQualificationItemRef.adoc[]


=== quoteItem
$ref of: xref:4.0.0@schemas:Customer:QuoteItemRef.adoc[]


=== productOrderItem
type: array


=== productOrderItemRelationship
type: array


=== qualification
type: array


=== state
description: State of the order item : described in the state machine diagram

$ref of: xref:4.0.0@schemas:Customer:ProductOrderItemStateType.adoc[]


{&#x27;$ref&#x27;: &#x27;../Common/Entity.schema.json#Entity&#x27;}