= TransferBalance

[#domain]
== Domain

This schema is part of Customer

[#description]
== Description

The TransferBalance resource is a detailed description of credit transfer operation requested between two buckets (reference to products owned by customers and consuming credit when using a service).


[#data_model]
== Data model

A JSON Schema corresponding to this data model can be found https://tmforum.org[here].

The data model is defined as shown below:


=== receiverBucketUsageType
description: Type of prepay balance bucket (e.g.: roaming-data, data, roaming-voice etc)

type: string


=== requestor
description: Identifier for the user/customer/entity that performs the transfer action.This can be used to indicate the identifier of an agent that performs the operation on behalf of a user via a customer service channel Structure including at least attributes “role” and “name”

$ref of: xref:4.0.0@schemas:Customer:RelatedParty.adoc[]


=== receiver
description: Identifier for the user/customer/entity that receives the transfer when it is required to indicate additional customer hierarchy information regarding the entity receiving the balance transfer Structure including at least attributes “role” and “name”

$ref of: xref:4.0.0@schemas:Customer:RelatedParty.adoc[]


=== costOwner
description: Indicates which related party will bear the costs of the transfer. eg originator or receiver

type: string


=== receiverProduct
$ref of: xref:4.0.0@schemas:Customer:ProductRef.adoc[]


=== receiverBucket
description: A reference to the bucket to which the balance will be transferred

$ref of: xref:4.0.0@schemas:Customer:BucketRef.adoc[]


=== receiverLogicalResource
description: A reference to the logical resource that can be used to identify the bucket balance for example where product ids are not unique.

$ref of: xref:4.0.0@schemas:Customer:LogicalResourceRef.adoc[]


=== receiverPartyAccount
description: A reference to the receiver account that owns the receiverlbucket impacted by the balance related operation

$ref of: xref:4.0.0@schemas:Customer:PartyAccountRef.adoc[]


=== transferCost
description: Associated cost to be charged for the transfer operation (can be monetary or non-monetary)

$ref of: xref:4.0.0@schemas:Customer:Quantity.adoc[]


= All Of 
