@startuml
hide circle
hide methods
hide stereotype
show <<Enumeration>> stereotype
skinparam class {
   BackgroundColor<<Enumeration>> #E6F5F7
   BackgroundColor<<Ref>> #FFFFE0
   BackgroundColor<<Pivot>> #FFFFFFF
   BackgroundColor<<SimpleType>> #E2F0DA
   BackgroundColor #FCF2E3
}

class PaymentPlan <<Pivot>> {
    href : Uri
    id : String
    numberOfPayments : Integer
    paymentFrequency : String
    planType : String
    priority : Integer
    status : String
    totalAmount : Money
    validFor : TimePeriod
    @baseType : String
    @schemaLocation : Uri
    @type : String
}

class PaymentMethodRef  <<Ref>> {
    href : Uri
    id : String [1]
    name : String
    @baseType : String
    @referredType : String
    @schemaLocation : Uri
    @type : String
}

PaymentPlan *-->  "0..1" PaymentMethodRef : paymentMethod

@enduml