@startuml
hide circle
hide methods
hide stereotype
show <<Enumeration>> stereotype
skinparam class {
   BackgroundColor<<Enumeration>> #E6F5F7
   BackgroundColor<<Ref>> #FFFFE0
   BackgroundColor<<Pivot>> #FFFFFFF
   BackgroundColor<<SimpleType>> #E2F0DA
   BackgroundColor #FCF2E3
}

class PerformanceIndicatorSpecificationRefOrValue <<Pivot>> {
    collectionType : CollectionType
    derivationAlgorithm : String
    derivationMethod : String
    description : String
    href : Uri
    id : String
    indicatorCategory : String
    indicatorType : IndicatorType
    indicatorUnit : String
    name : String
    perspective : String
    validFor : TimePeriod
    version : String
    @baseType : String
    @referredType : String
    @schemaLocation : Uri
    @type : String
}

class PerformanceIndicatorSpecRelationship  <<Ref>> {
    href : String
    id : String
    name : String
    relationshipType : String [1]
    role : String
    validFor : TimePeriod [1]
    @baseType : String
    @schemaLocation : Uri
    @type : String
}

class CollectionType <<Enumeration>> {
    cumulative
    delta
    discrete_event
    gauge
    status_inspection
}

class IndicatorType <<Enumeration>> {
    string
    int
    float
    double
}

PerformanceIndicatorSpecificationRefOrValue -right[hidden]-> IndicatorType

IndicatorType -right[hidden]-> CollectionType

PerformanceIndicatorSpecificationRefOrValue *-->  "0..*" PerformanceIndicatorSpecRelationship : performanceIndicatorSpecRelationship

@enduml