@startuml
hide circle
hide methods
hide stereotype
show <<Enumeration>> stereotype
skinparam class {
   BackgroundColor<<Enumeration>> #E6F5F7
   BackgroundColor<<Ref>> #FFFFE0
   BackgroundColor<<Pivot>> #FFFFFFF
   BackgroundColor<<SimpleType>> #E2F0DA
   BackgroundColor #FCF2E3
}

class Event <<Pivot>> {
    correlationId : String
    description : String
    domain : String
    event : Any
    eventId : String
    eventTime : DateTime
    eventType : String
    href : Uri
    id : String [1]
    name : String
    priority : String
    timeOccurred : DateTime
    title : String
    @baseType : String
    @referredType : String
    @schemaLocation : Uri
    @type : String
}

class Characteristic  {
    id : String
    name : String [1]
    value : Any [1]
    valueType : String
    @baseType : String
    @schemaLocation : Uri
    @type : String
}

class CharacteristicRelationship  <<Ref>> {
    href : Uri
    id : String
    relationshipType : String
    @baseType : String
    @schemaLocation : Uri
    @type : String
}

class RelatedParty  {
    href : Uri
    id : String [1]
    name : String
    role : String
    @baseType : String
    @referredType : String [1]
    @schemaLocation : Uri
    @type : String
}

Event *-right-> "0..*" Characteristic : analyticCharacteristic

Event *-->  "0..*" RelatedParty : relatedParty

Characteristic *-->  "0..*" CharacteristicRelationship : characteristicRelationship

@enduml