@startuml
hide circle
hide methods
hide stereotype
show <<Enumeration>> stereotype
skinparam class {
   BackgroundColor<<Enumeration>> #E6F5F7
   BackgroundColor<<Ref>> #FFFFE0
   BackgroundColor<<Pivot>> #FFFFFFF
   BackgroundColor<<SimpleType>> #E2F0DA
   BackgroundColor #FCF2E3
}

class AdjustProductStock <<Pivot>> {
    adjustReason : String
    completedAdjustProductStockDate : DateTime
    creationDate : DateTime
    description : String
    href : String
    id : String
    instantSyncAdjust : Boolean
    requestedAdjustProductStockDate : DateTime
    state : TaskStateType
    @baseType : String
    @schemaLocation : Uri
    @type : String
}

class AdjustProductStockItem  {
    adjustProductStockQuantity : Quantity
    href : Uri
    id : String
    state : TaskStateType
    @baseType : String
    @schemaLocation : Uri
    @type : String
}

class ProductStockRef  <<Ref>> {
    href : Uri
    id : String [1]
    name : String
    @baseType : String
    @referredType : String
    @schemaLocation : Uri
    @type : String
}

class TaskStateType <<Enumeration>> {
    accepted
    terminatedWithError
    inProgress
    done
}

AdjustProductStock *-right-> "1..*" AdjustProductStockItem : adjustProductStockItem

TaskStateType <-left[hidden]- AdjustProductStock

AdjustProductStockItem *-->  "0..1" ProductStockRef : productStockTarget

@enduml