@startuml
hide circle
hide methods
hide stereotype
show <<Enumeration>> stereotype
skinparam class {
   BackgroundColor<<Enumeration>> #E6F5F7
   BackgroundColor<<Ref>> #FFFFE0
   BackgroundColor<<Pivot>> #FFFFFFF
   BackgroundColor<<SimpleType>> #E2F0DA
   BackgroundColor #FCF2E3
}

class Customer360AccountVO <<Pivot>> {
    accountType : String
    creditLimit : Money
    description : String
    href : String
    id : String
    lastModified : DateTime
    name : String [1]
    state : String
    @baseType : String
    @schemaLocation : Uri
    @type : String
}

class AccountRelationship  <<Ref>> {
    href : Uri
    id : String
    relationshipType : String [1]
    validFor : TimePeriod
    @baseType : String
    @schemaLocation : Uri
    @type : String
}

class AccountRef  <<Ref>> {
    description : String
    href : String
    id : String [1]
    name : String
    @baseType : String
    @referredType : String
    @schemaLocation : Uri
    @type : String
}

Customer360AccountVO *-->  "0..*" AccountRelationship : accountRelationship

AccountRelationship *-->  "0..1" AccountRef : account

@enduml