@startuml
hide circle
hide methods
hide stereotype
show <<Enumeration>> stereotype
skinparam class {
   BackgroundColor<<Enumeration>> #E6F5F7
   BackgroundColor<<Ref>> #FFFFE0
   BackgroundColor<<Pivot>> #FFFFFFF
   BackgroundColor<<SimpleType>> #E2F0DA
   BackgroundColor #FCF2E3
}

class Usage <<Pivot>> {
    description : String
    href : Uri
    id : String
    status : UsageStatusType
    usageDate : DateTime
    usageType : String
    @baseType : String
    @schemaLocation : Uri
    @type : String
}

class RelatedParty  {
    href : Uri
    id : String [1]
    name : String
    role : String
    @baseType : String
    @referredType : String [1]
    @schemaLocation : Uri
    @type : String
}

class RatedProductUsage  {
    bucketValueConvertedInAmount : Money
    isBilled : Boolean
    isTaxExempt : Boolean
    offerTariffType : String
    ratingAmountType : String
    ratingDate : DateTime
    taxExcludedRatingAmount : Money
    taxIncludedRatingAmount : Money
    taxRate : Float
    usageRatingTag : String
    @baseType : String
    @schemaLocation : Uri
    @type : String
}

class ProductRef  <<Ref>> {
    href : Uri
    id : String [1]
    name : String
    @baseType : String
    @referredType : String
    @schemaLocation : Uri
    @type : String
}

class UsageSpecificationRef  <<Ref>> {
    href : Uri
    id : String [1]
    name : String
    @baseType : String
    @referredType : String
    @schemaLocation : Uri
    @type : String
}

class UsageCharacteristic  {
    id : String
    name : String [1]
    value : Any [1]
    valueType : String
    @baseType : String
    @schemaLocation : Uri
    @type : String
}

class CharacteristicRelationship  <<Ref>> {
    href : Uri
    id : String
    relationshipType : String
    @baseType : String
    @schemaLocation : Uri
    @type : String
}

class UsageStatusType <<Enumeration>> {
    received
    rejected
    recycled
    guided
    rated
    rerated
    billed
}

Usage -right[hidden]-> UsageStatusType

RelatedParty "0..*" <--* Usage : relatedParty

UsageSpecificationRef "0..1" <--* Usage : usageSpecification

Usage *-->  "0..*" RatedProductUsage : ratedProductUsage

Usage *-->  "0..*" UsageCharacteristic : usageCharacteristic

RatedProductUsage *-->  "0..1" ProductRef : productRef

UsageCharacteristic *-->  "0..*" CharacteristicRelationship : characteristicRelationship

@enduml