@startuml
hide circle
hide methods
hide stereotype
show <<Enumeration>> stereotype
skinparam class {
   BackgroundColor<<Enumeration>> #E6F5F7
   BackgroundColor<<Ref>> #FFFFE0
   BackgroundColor<<Pivot>> #FFFFFFF
   BackgroundColor<<SimpleType>> #E2F0DA
   BackgroundColor #FCF2E3
}

class TopologyDiscoveryJob <<Pivot>> {
    completionDate : DateTime
    creationDate : DateTime
    href : Uri
    id : String
    status : TaskStateType
    @baseType : String
    @schemaLocation : Uri
    @type : String
}

class TaskStateType <<Enumeration>> {
    accepted
    terminatedWithError
    inProgress
    done
}

TopologyDiscoveryJob -right[hidden]-> TaskStateType

@enduml