@startuml
hide circle
hide methods
hide stereotype
show <<Enumeration>> stereotype
skinparam class {
   BackgroundColor<<Enumeration>> #E6F5F7
   BackgroundColor<<Ref>> #FFFFE0
   BackgroundColor<<Pivot>> #FFFFFFF
   BackgroundColor<<SimpleType>> #E2F0DA
   BackgroundColor #FCF2E3
}

class PerformanceAlarmSpecification <<Pivot>> {
    perfAlarmSpecAdditionalText : String
    perfAlarmSpecAlarmType : String
    perfAlarmSpecProbableCause : String
    perfAlarmSpecSeverity : PerceivedSeverity
    perfAlarmSpecSpecificProblem : String
    perfAlarmThresholdCrossingDescription : String
}

class PerceivedSeverity <<Enumeration>> {
    CRITICAL
    MAJOR
    MINOR
    WARNING
    INDETERMINATE
    CLEARED
}

class PerformanceConsequence  {
    description : String
    href : Uri
    id : String
    name : String
    prescribedAction : String
    @baseType : String
    @schemaLocation : Uri
    @type : String
}

PerformanceAlarmSpecification -right[hidden]-> PerceivedSeverity

PerformanceAlarmSpecification *-->  "0..1" PerformanceConsequence : performanceConsequence

PerformanceAlarmSpecification "0..1" <--* PerformanceConsequence : alarmSpecification

@enduml