= AckAlarms

[#domain]
== Domain

This schema is part of Resource

[#description]
== Description
Task resource for the acknowledge alarms operation


[#data_model]
== Data model

A JSON Schema corresponding to this data model can be found https://tmforum.org[here].

The data model is defined as shown below:


=== id
description: The identifier of the task

type: string


=== href
description: A reference to the task

type: string


=== state
description: Current state of the operation task

type: string


=== ackSystemId
description: Name of the acknowledging system

type: string


=== ackUserId
description: Name of the acknowledging user

type: string


=== ackTime
description: Time of the acknowledgement

type: string


=== alarmPattern
description: Alarm patterns to match target alarms. An alarm will match if all of the sttributes in any of the patterns compare equal to those attributes of the alarm.

type: array


=== ackedAlarm
description: The successfully acknowledged alarms

type: array

