= AlternateProductStock

[#domain]
== Domain

This schema is part of Resource

[#description]
== Description

AlternateProductStock is used to log and execute Alternate about product  stock availability


[#data_model]
== Data model

A JSON Schema corresponding to this data model can be found https://tmforum.org[here].

The data model is defined as shown below:


=== alternateAvailabilityDate
description: Alternate date when the product stock is available.

type: string


=== id
description: identifier of the Alternate product stock 

type: string


=== alternateQuantity
description: Alternate quantity available

$ref of: xref:v4.2@schemas:Resource:Quantity.adoc[]


=== alternatePlace
description: Alternate place where product stock is available

$ref of: xref:v4.2@schemas:Resource:PlaceRefOrValue.adoc[]


=== alternateStock
description: Alternate product stock available

$ref of: xref:v4.2@schemas:Resource:ProductStockRef.adoc[]


=== alternateProduct
description: Alternat product available

$ref of: xref:v4.2@schemas:Resource:ProductRefOrValue.adoc[]


[#all_of]
== All Of

This schema extends: xref:v4.2@schemas:Resource:Extensible.adoc[]
