= CheckProductStock

[#domain]
== Domain

This schema is part of Resource

[#description]
== Description

CheckProductStock is used to log and execute check about product stock availability


[#data_model]
== Data model

A JSON Schema corresponding to this data model can be found https://tmforum.org[here].

The data model is defined as shown below:


=== creationDate
description: Date when the CheckProductStock was created (whatever its status).

type: string


=== requestedCheckProductStockDate
description: Date when the requester wished to have a response for this product stock check query.

type: string


=== completedCheckProductStockDate
description: Date when the CheckProductStock was completed.

type: string


=== requestedAvailabilityDate
description: Date when the stock availability should be check.

type: string


=== id
description: Unique identifier of the CheckProductStock

type: string


=== href
description: Reference of the CheckProductStock

type: string


=== instantSyncCheck
description: An indicator which when the value is &quot;true&quot; means that requester expects to get result immediately in the response. If the indicator is true then the response code of 200 indicates the operation is successful otherwise a task is created with a response 201.

type: boolean


=== state
description: State of the CheckProductStock (acknowledged, inProgress, terminatedWithError, done)

$ref of: xref:4.0.0@schemas:Resource:TaskStateType.adoc[]


=== provideAlternative
description: When the value is TRUE means that alternative proposal should be provided (from other product stock, different date or quantity)

type: boolean


=== checkProductStockItem
description: A list of check product stock  item

type: array


=== relatedParty
description: A list of related party references (RelatedParty [*]). A related party defines party or party role linked to this CheckProductStock

type: array


=== place
description: Used to define a geographical place where requester wants to check stock availability 

$ref of: xref:4.0.0@schemas:Resource:PlaceRefOrValue.adoc[]


= All Of 
This schema extends: xref:4.0.0@schemas:Resource:Entity.adoc[]
