= ClearAlarms

[#domain]
== Domain

This schema is part of Resource

[#description]
== Description

Task resource for clear alarms operation


[#data_model]
== Data model

A JSON Schema corresponding to this data model can be found https://tmforum.org[here].

The data model is defined as shown below:


=== id
description: The identifier of the task

type: string


=== href
description: A reference to the task

type: string


=== state
description: Current state of the operation task

type: string


=== clearSystemId
description: Name of the clearing system

type: string


=== clearUserId
description: Name of the clearing user

type: string


=== alarmClearedTime
description: Time of the alarm clearing

type: string


=== alarmPattern
description: Alarm patterns to match target alarms. An alarm will match if all of the sttributes in any of the patterns compare equal to those attributes of the alarm.

type: array


=== clearedAlarm
description: The successfully cleared alarms

type: array


[#all_of]
== All Of

