= ResourceCategory

[#domain]
== Domain

This schema is part of Resource

[#description]
== Description
The (resource) category resource is used to group resource candidates in logical containers. Categories can contain other categories.


[#data_model]
== Data model

A JSON Schema corresponding to this data model can be found https://tmforum.org[here].

The data model is defined as shown below:


=== id
description: Unique identifier of the category

type: string


=== href
description: Hyperlink reference to the category

type: string


=== name
description: Name of the category

type: string


=== description
description: Description of the category

type: string


=== version
description: Category version

type: string


=== validFor
description: The period for which the category is valid

$ref of: xref:4.0.0@schemas:Resource:TimePeriod.adoc[]


=== lifecycleStatus
description: Used to indicate the current lifecycle status

type: string


=== lastUpdate
description: Date and time of the last update

type: string


=== parentId
description: Unique identifier of the parent category

type: string


=== isRoot
description: If true, this Boolean indicates that the category is a root of categories

type: boolean


=== category
description: The category resource is used to group product offerings, service and resource candidates in logical containers. Categories can contain other (sub-)categories and/or product offerings.

type: array


=== resourceCandidate
description: List of resource candidates accessible via this category

type: array


=== relatedParty
description: List of parties involved in this category

type: array

