= ResourceOrder

[#domain]
== Domain

This schema is part of Resource

[#description]
== Description
A Resource Order is a request to provision a set of Resources (logical and physical) triggered by the request to provision a Service through a Service Order


[#data_model]
== Data model

A JSON Schema corresponding to this data model can be found https://tmforum.org[here].

The data model is defined as shown below:


=== id
description: Identifier of an instance of the Resource Order. Required to be unique within the resource type.

type: string


=== href
description: Hyperlink to access the order

type: string


=== cancellationDate
description: Date when the order is cancelled - if cancelled, in RFC3339 (subset of ISO8601) format

type: string


=== cancellationReason
description: Reason why the order is cancelled - if cancelled

type: string


=== externalId
description: DEPRECATED: Use externalReference Instead. ID given by the consumer (to facilitate searches afterwards)

type: string


=== externalReference
type: array


=== state
$ref of: xref:4.0.0@schemas:Resource:ResourceOrderStateType.adoc[]


=== name
description: A string used to give a name to the Resource Order

type: string


=== description
description: Free-text description of the Resource Order

type: string


=== priority
description: A way that can be used by consumers to prioritize orders in OM system (such as: 0 is the highest priority, and 4 the lowest)

type: integer


=== orderType
description: Name of the Resource Order type

type: string


=== category
description: Used to categorize the order from a business perspective that can be useful for the order management system

type: string


=== orderDate
description: Date when the order was created, in RFC3339 (subset of ISO8601) format

type: string


=== requestedStartDate
description: Order start date wished by the requestor, in RFC3339 (subset of ISO8601) format

type: string


=== requestedCompletionDate
description: Requested delivery date from the requestor perspective, in RFC3339 (subset of ISO8601) format

type: string


=== startDate
description: Date when the order was actually started, in RFC3339 (subset of ISO8601) format

type: string


=== completionDate
description: Date when the order was actually completed, in RFC3339 (subset of ISO8601) format

type: string


=== expectedCompletionDate
description: Date when the order is expected to be completed, in RFC3339 (subset of ISO8601) format

type: string


=== orderItem
type: array


=== note
type: array


=== relatedParty
type: array

