@startuml
hide circle
hide methods
hide stereotype
show <<Enumeration>> stereotype
skinparam class {
   BackgroundColor<<Enumeration>> #E6F5F7
   BackgroundColor<<Ref>> #FFFFE0
   BackgroundColor<<Pivot>> #FFFFFFF
   BackgroundColor<<SimpleType>> #E2F0DA
   BackgroundColor #FCF2E3
}

class AgreementSpecCharacteristic <<Pivot>> {
    configurable : Boolean
    description : String
    href : Uri
    id : String
    name : String
    validFor : TimePeriod
    valueType : String
    @baseType : String
    @schemaLocation : Uri
    @type : String
}

class AgreementSpecCharacteristicValue  {
    default : Boolean
    href : Uri
    id : String
    unitOfMeasure : String
    validFor : TimePeriod
    value : Any
    valueFrom : String
    valueTo : String
    valueType : String
    @baseType : String
    @schemaLocation : Uri
    @type : String
}

AgreementSpecCharacteristic *-->  "0..*" AgreementSpecCharacteristicValue : specCharacteristicValue

@enduml