= RelatedServiceOrderItem

[#domain]
== Domain

This schema is part of Service

[#description]
== Description

RelatedServiceOrderItem (a ServiceOrder item) .The service order item which triggered service creation/change/termination.


[#data_model]
== Data model

A JSON Schema corresponding to this data model can be found https://tmforum.org[here].

The data model is defined as shown below:


=== @referredType
description: The actual type of the target instance when needed for disambiguation.

type: string


=== serviceOrderHref
description: Reference of the related entity.

type: string


=== serviceOrderId
description: Unique identifier of a related entity.

type: string


=== itemAction
description: Action of the order item for this service

$ref of: xref:4.0.0@schemas:Service:OrderItemActionType.adoc[]


=== itemId
description: Identifier of the order item where the service was managed

type: string


=== role
description: role of the service order item for this service

type: string

