= ServiceProblemEventRecord

[#domain]
== Domain

This schema is part of Service

[#description]
== Description

A record of an event (related to a service problem) received from another system


[#data_model]
== Data model

A JSON Schema corresponding to this data model can be found https://tmforum.org[here].

The data model is defined as shown below:


=== eventTime
description: Time at which the event occurred

type: string


=== eventType
description: Type of the recorded event

type: string


=== href
description: reference to this resource

type: string


=== id
description: Identifier of the service problem event record.

type: string


=== recordTime
description: Time at which the record was created

type: string


=== serviceProblem
description: The service problem to which this record applies

$ref of: xref:4.0.0@schemas:Service:ServiceProblemRef.adoc[]


=== notification
description: A notification from the possible notifications for Service Problem (such as creation, status change, information required, change)

$ref of: xref:4.0.0@schemas:Service:Any.adoc[]

