= ServiceCategory

[#domain]
== Domain

This schema is part of Service

[#description]
== Description

The (service) category resource is used to group service candidates in logical containers. Categories can contain other categories.


[#data_model]
== Data model

A JSON Schema corresponding to this data model can be found https://tmforum.org[here].

The data model is defined as shown below:


=== name
description: Name of the category

type: string


=== description
description: Description of the category

type: string


=== version
description: ServiceCategory version

type: string


=== validFor
description: The period for which the category is valid

$ref of: xref:4.0.0@schemas:Service:TimePeriod.adoc[]


=== lifecycleStatus
description: Used to indicate the current lifecycle status

type: string


=== lastUpdate
description: Date and time of the last update

type: string


=== parentId
description: Unique identifier of the parent category

type: string


=== isRoot
description: If true, this Boolean indicates that the category is a root of categories

type: boolean


=== serviceCandidate
description: List of service candidates associated with this category

type: array


=== category
description: List of child categories in the tree for in this category

type: array


= All Of 
