= ServiceQualification

[#domain]
== Domain

This schema is part of Service

[#description]
== Description

ServiceQualification is used to perform a technical eligibility. It allows to retrieve a list of services that are technically available in the context of the interaction (place, party, service characteristics, ...).


[#data_model]
== Data model

A JSON Schema corresponding to this data model can be found https://tmforum.org[here].

The data model is defined as shown below:


=== href
description: Hyperlink to access the serviceQualification

type: string


=== id
description: Unique identifier of the serviceQualification resource

type: string


=== description
description: Description of the serviceQualification

type: string


=== effectiveQualificationDate
description: Effective date to serviceQualification completion

type: string


=== instantSyncQualification
description: An indicator which when the value is &quot;true&quot; means that requester expects to get qualifcation result immediately in the response. If the indicator is true then the response code of 200 indicates the operation is successful otherwise a task is created with a response 201.

type: boolean


=== estimatedResponseDate
description: Date when the requester expect to provide an answer for the qualification request.

type: string


=== expectedQualificationDate
description: A date (DateTime). Deadline date when the requester expected a qualification answer.

type: string


=== expirationDate
description: Date when the qualification response expires

type: string


=== state
description: State of the serviceQualification (acknowledged, inProgress, terminatedWithError, done)

$ref of: xref:4.0.0@schemas:Service:TaskStateType.adoc[]


=== relatedParty
description: A list of related party references, defines party or party role linked to this request.

type: array


=== externalId
description: Identifier provided by the requester

type: string


{&#x27;$ref&#x27;: &#x27;../Common/Entity.schema.json#Entity&#x27;}