= ServiceSpecification

[#domain]
== Domain

This schema is part of Service

[#description]
== Description

ServiceSpecification is a class that offers characteristics to describe a type of service.
Functionally, it acts as a template by which Services may be instantiated. By sharing the same specification, these services would therefore share the same set of characteristics.


[#data_model]
== Data model

A JSON Schema corresponding to this data model can be found https://tmforum.org[here].

The data model is defined as shown below:


=== resourceSpecification
description: A list of resource specification references (ResourceSpecificationRef [*]). The ResourceSpecification is required for a service specification with type ResourceFacingServiceSpecification (RFSS).

type: array


=== serviceLevelSpecification
description: A list of service level specifications related to this service specification, and which will need to be satisifiable for corresponding service instances; e.g. Gold, Platinum

type: array


=== serviceSpecRelationship
description: A list of service specifications related to this specification, e.g. migration, substitution, dependency or exclusivity relationship

type: array


=== featureSpecification
description: A list of Features for this specification.

type: array


= All Of 
This schema extends: xref:v4.0@schemas:Service:EntitySpecification.adoc[]
