= ServiceCandidate

[#domain]
== Domain

This schema is part of Service

[#description]
== Description

ServiceCandidate is an entity that makes a service specification available to a catalog. A
ServiceCandidate and its associated service specification may be published - made visible - in any number of service catalogs, or in none. One service specification can be composed of other service specifications.


[#data_model]
== Data model

A JSON Schema corresponding to this data model can be found https://tmforum.org[here].

The data model is defined as shown below:


=== name
description: Name given to this REST resource

type: string


=== description
description: Description of this REST resource

type: string


=== version
description: the version of service candidate

type: string


=== validFor
description: The period for which this REST resource is valid

$ref of: xref:v4.1@schemas:Service:TimePeriod.adoc[]


=== lastUpdate
description: Date and time of the last update of this REST resource

type: string


=== lifecycleStatus
description: Used to indicate the current lifecycle status of the service candidate.

type: string


=== category
description: List of categories for this candidate

type: array


=== serviceSpecification
description: The service specification implied by this candidate

$ref of: xref:v4.1@schemas:Service:ServiceSpecificationRef.adoc[]


= All Of 
This schema extends: xref:v4.1@schemas:Service:Addressable.adoc[]
This schema extends: xref:v4.1@schemas:Service:Extensible.adoc[]
