@startuml
hide circle
hide methods
hide stereotype
show <<Enumeration>> stereotype
skinparam class {
   BackgroundColor<<Enumeration>> #E6F5F7
   BackgroundColor<<Ref>> #FFFFE0
   BackgroundColor<<Pivot>> #FFFFFFF
   BackgroundColor<<SimpleType>> #E2F0DA
   BackgroundColor #FCF2E3
}

class FeatureSpecification <<Pivot>> {
    href : Uri
    id : String
    isBundle : Boolean
    isEnabled : Boolean
    name : String
    validFor : TimePeriod
    version : String
    @baseType : String
    @schemaLocation : Uri
    @type : String
}

class FeatureSpecificationRelationship  {
    featureId : String
    name : String [1]
    parentSpecificationHref : Uri
    parentSpecificationId : String
    relationshipType : String [1]
    validFor : TimePeriod
    @baseType : String
    @schemaLocation : Uri
    @type : String
}

class ConstraintRef  <<Ref>> {
    href : Uri
    id : String [1]
    name : String
    version : String
    @baseType : String
    @referredType : String
    @schemaLocation : Uri
    @type : String
}

class FeatureSpecificationCharacteristic  {
    configurable : Boolean
    description : String
    extensible : Boolean
    id : String
    isUnique : Boolean
    maxCardinality : Integer
    minCardinality : Integer
    name : String [1]
    regex : String
    validFor : TimePeriod
    valueType : String
    @baseType : String
    @schemaLocation : Uri
    @type : String
    @valueSchemaLocation : String
}

class CharacteristicValueSpecification  {
    isDefault : Boolean
    rangeInterval : String
    regex : String
    unitOfMeasure : String
    validFor : TimePeriod
    value : Any
    valueFrom : Integer
    valueTo : Integer
    valueType : String
    @baseType : String
    @schemaLocation : Uri
    @type : String
}

class FeatureSpecificationCharacteristicRelationship  <<Ref>> {
    characteristicId : String
    featureId : String
    href : Uri
    id : String
    name : String
    relationshipType : String
    resourceSpecificationHref : Uri
    resourceSpecificationId : String
    validFor : TimePeriod
    @baseType : String
    @schemaLocation : Uri
    @type : String
}

FeatureSpecification *-->  "0..*" FeatureSpecificationRelationship : featureSpecRelationship

FeatureSpecification *-->  "0..*" ConstraintRef : constraint

FeatureSpecification *-->  "0..*" FeatureSpecificationCharacteristic : featureSpecCharacteristic

FeatureSpecificationCharacteristic *-->  "0..*" FeatureSpecificationCharacteristicRelationship : featureSpecCharRelationship

FeatureSpecificationCharacteristic *-->  "0..*" CharacteristicValueSpecification : featureSpecCharacteristicValue

@enduml