@startuml
hide circle
hide methods
hide stereotype
show <<Enumeration>> stereotype
skinparam class {
   BackgroundColor<<Enumeration>> #E6F5F7
   BackgroundColor<<Ref>> #FFFFE0
   BackgroundColor<<Pivot>> #FFFFFFF
   BackgroundColor<<SimpleType>> #E2F0DA
   BackgroundColor #FCF2E3
}

class PackingType <<Pivot>> {
    packingEnumType : PackingEnumType
}

class PackingEnumType <<Enumeration>> {
    NO_PACKING
    GZIP
    TAR
    VENDOR_EXT
    MINOR_EXT
}

PackingType -right[hidden]-> PackingEnumType

@enduml