@startuml
hide circle
hide methods
hide stereotype
show <<Enumeration>> stereotype
skinparam class {
   BackgroundColor<<Enumeration>> #E6F5F7
   BackgroundColor<<Ref>> #FFFFE0
   BackgroundColor<<Pivot>> #FFFFFFF
   BackgroundColor<<SimpleType>> #E2F0DA
   BackgroundColor #FCF2E3
}

class CrossedThresholdInformation <<Pivot>> {
    direction : String
    granularity : String
    indicatorName : String
    indicatorUnit : String
    observedValue : String
    thresholdCrossingDescription : String
}

class ThresholdRef  <<Ref>> {
    href : Uri
    id : String [1]
    name : String
    @baseType : String
    @referredType : String
    @schemaLocation : Uri
    @type : String
}

CrossedThresholdInformation *-->  "0..1" ThresholdRef : threshold

@enduml