@startuml
hide circle
hide methods
hide stereotype
show <<Enumeration>> stereotype
skinparam class {
   BackgroundColor<<Enumeration>> #E6F5F7
   BackgroundColor<<Ref>> #FFFFE0
   BackgroundColor<<Pivot>> #FFFFFFF
   BackgroundColor<<SimpleType>> #E2F0DA
   BackgroundColor #FCF2E3
}

class Resolution <<Pivot>> {
    code : String
    description : String
    href : Uri
    id : String
    name : String
    @baseType : String
    @schemaLocation : Uri
    @type : String
}

class Task  {
    description : String
    href : Uri
    id : String
    name : String
    state : String
    @baseType : String
    @schemaLocation : Uri
    @type : String
}

Resolution *-->  "0..*" Task : task

@enduml