= ConsumptionSummary

[#domain]
== Domain

This schema is part of Product

[#description]
== Description

The consumption counters (called ConsumptionSummary in the SID model) detail for example the different kind of consumption done on the bucket.


[#data_model]
== Data model

A JSON Schema corresponding to this data model can be found https://tmforum.org[here].

The data model is defined as shown below:


=== consumptionPeriod
description: Consumption counter period between a start date time and an end date time. For prepaid bucket, the period of counters is between the start date of the bucket and the effective date of the usage consumption report generation. For postpaid bucket, the period of counters is between the last bill date and the effective date of the usage consumption report generation.

$ref of: xref:v4.0@schemas:Product:TimePeriod.adoc[]


=== counterType
description: Type of the consumption counter. We can give for example a counter of the used value for a bucket (counterType=used for example) or the value of the consumption done out of the bucket(s) (counterType=outOfBucket for example)

type: string


=== level
description: Counter level. The counter can be given globally for the bucket or detailed by user or by network product for example in case of shared bucket

type: string


=== user
description: Reference of the user for which the consumption counter is detailed. If the level of the counter is global (i.e. concerning all the users), the list of them is not specified. It can be found through the users listed in the network products of the bucket sub-resource

$ref of: xref:v4.0@schemas:Product:RelatedParty.adoc[]


=== value
description: Numeric value of the bucket counter in a given unit

$ref of: xref:v4.0@schemas:Product:Quantity.adoc[]


=== valueName
description: Value of the counter in a formatted string used for display needs for example

type: string


= All Of 
This schema extends: xref:v4.0@schemas:Product:Entity.adoc[]
