= POPCharge

[#domain]
== Domain

This schema is part of Product

[#description]
== Description

This is representing a product offering price (charge) based on both the basic cost to develop and produce products and the enterprises policy on revenue targets. This price may be further revised through discounting (a Product Offering Price that reflects an alteration).


[#data_model]
== Data model

A JSON Schema corresponding to this data model can be found https://tmforum.org[here].

The data model is defined as shown below:


=== name
description: Name of the productOfferingPrice

type: string


=== description
description: Description of the productOfferingPrice

type: string


=== version
description: ProductOffering version

type: string


=== validFor
description: The period for which the productOfferingPrice is valid

$ref of: xref:4.0.0@schemas:Product:TimePeriod.adoc[]


=== priceType
description: A category that describes the price charge, such as recurring, penalty, One time fee and so forth.

type: string


=== unitOfMeasure
description: A number and unit representing denominator of a rate. For example, for a data charge rate of $2 per 5 GB usage, the amount of unitOfMeasure will be 5 with units as GB.

$ref of: xref:4.0.0@schemas:Product:Quantity.adoc[]


=== recurringChargePeriod
description: The period type to repeat the application of the price
Could be month, week...

type: string


=== recurringChargePeriodLength
description: the period of the recurring charge:  1, 2, ... .It sets to zero if it is not applicable

type: integer


=== lastUpdate
description: the last update time of this ProductOfferingPrice

type: string


=== lifecycleStatus
description: the lifecycle status of this ProductOfferingPrice

type: string


=== constraint
description: The Constraint resource represents a policy/rule applied to ProductOfferingPrice.

type: array


=== priceAlteration
type: array


=== price
$ref of: xref:4.0.0@schemas:Product:ProductPriceValue.adoc[]

