= PricingLogicAlgorithm

[#domain]
== Domain

This schema is part of Product

[#description]
== Description

The PricingLogicAlgorithm entity represents an instantiation of an interface specification to external rating function (without a modeled bahavior in SID). Some of the parameters of the interface definiition may be already set (such as price per unit) and some may be gathered during the rating process from the event (such as call duration) or from ProductCharacteristicValues (such as assigned bandwidth)


[#data_model]
== Data model

A JSON Schema corresponding to this data model can be found https://tmforum.org[here].

The data model is defined as shown below:


=== description
description: Description of the PricingLogicAlgorithm

type: string


=== name
description: Name given to the PricingLogicAlgorithm

type: string


=== plaSpecId
description: id of corresponding PricingLogicAlgorithm specification

type: string


=== validFor
description: The period for which the PricingLogicAlgorithm is valid

$ref of: xref:4.0.0@schemas:Product:TimePeriod.adoc[]


= All Of 
