= ProductSpecificationCharacteristicValueUse

[#domain]
== Domain

This schema is part of Product

[#description]
== Description

A use of the ProductSpecificationCharacteristicValue by a ProductOffering to which additional properties (attributes) apply or override the properties of similar properties contained in ProductSpecificationCharacteristicValue. It should be noted that characteristics which their value(s) addressed by this object must exist in corresponding product specification. The available characteristic values for a ProductSpecificationCharacteristic in a Product specification can be modified at the ProductOffering level. For example, a characteristic &#x27;Color&#x27; might have values White, Blue, Green, and Red. But, the list of values can be restricted to e.g. White and Blue in an associated product offering. It should be noted that the list of values in &#x27;ProductSpecificationCharacteristicValueUse&#x27; is a strict subset of the list of values as defined in the corresponding product specification characteristics.


[#data_model]
== Data model

A JSON Schema corresponding to this data model can be found https://tmforum.org[here].

The data model is defined as shown below:


=== name
description: Name of the associated productSpecificationCharacteristic

type: string


=== id
description: Unique ID for the characteristic

type: string


=== description
description: A narrative that explains in detail what the productSpecificationCharacteristic is

type: string


=== valueType
description: A kind of value that the characteristic can take on, such as numeric, text and so forth

type: string


=== minCardinality
description: The minimum number of instances a CharacteristicValue can take on. For example, zero to five phone numbers in a group calling plan, where zero is the value for the minCardinality.

type: integer


=== maxCardinality
description: The maximum number of instances a CharacteristicValue can take on. For example, zero to five phone numbers in a group calling plan, where five is the value for the maxCardinality.

type: integer


=== validFor
description: The period for which the productSpecificationCharacteristic is valid

$ref of: xref:v4.1@schemas:Product:TimePeriod.adoc[]


=== productSpecCharacteristicValue
description: A number or text that can be assigned to a ProductSpecificationCharacteristic.

type: array


=== productSpecification
description: A ProductSpecification is a detailed description of a tangible or intangible object made available externally in the form of a ProductOffering to customers or other parties playing a party role.

$ref of: xref:v4.1@schemas:Product:ProductSpecificationRef.adoc[]


= All Of 
This schema extends: xref:v4.1@schemas:Product:Extensible.adoc[]
