= Product

[#domain]
== Domain

This schema is part of Product

[#description]
== Description

A product offering procured by a customer or other interested party playing a party role. A product is realized as one or more service(s) and / or resource(s).


[#data_model]
== Data model

A JSON Schema corresponding to this data model can be found https://tmforum.org[here].

The data model is defined as shown below:


=== agreement
type: array


=== billingAccount
$ref of: xref:4.0.0@schemas:Product:BillingAccountRef.adoc[]


=== description
description: Is the description of the product. It could be copied from the description of the Product Offering.

type: string


=== href
description: Reference of the product

type: string


=== id
description: Unique identifier of the product

type: string


=== isBundle
description: If true, the product is a ProductBundle which is an instantiation of a BundledProductOffering. If false, the product is a ProductComponent which is an instantiation of a SimpleProductOffering.

type: boolean


=== isCustomerVisible
description: If true, the product is visible by the customer.

type: boolean


=== name
description: Name of the product. It could be the same as the name of the product offering

type: string


=== orderDate
description: Is the date when the product was ordered

type: string


=== productCharacteristic
type: array


=== productOffering
$ref of: xref:4.0.0@schemas:Product:ProductOfferingRef.adoc[]


=== productOrderItem
type: array


=== product
type: array


=== productPrice
type: array


=== productRelationship
type: array


=== productSerialNumber
description: Is the serial number for the product. This is typically applicable to tangible products e.g. Broadband Router.

type: string


=== productSpecification
$ref of: xref:4.0.0@schemas:Product:ProductSpecificationRef.adoc[]


=== productTerm
type: array


=== realizingResource
type: array


=== realizingService
type: array


=== relatedParty
type: array


=== place
type: array


=== startDate
description: Is the date from which the product starts

type: string


=== status
description: Is the lifecycle status of the product.

$ref of: xref:4.0.0@schemas:Product:ProductStatusType.adoc[]


=== terminationDate
description: Is the date when the product was terminated

type: string


= All Of 
