= ProductOffering

[#domain]
== Domain

This schema is part of Product

[#description]
== Description

Represents entities that are orderable from the provider of the catalog, this resource includes pricing information.


[#data_model]
== Data model

A JSON Schema corresponding to this data model can be found https://tmforum.org[here].

The data model is defined as shown below:


=== description
description: Description of the productOffering

type: string


=== href
description: Reference of the ProductOffering

type: string


=== id
description: Unique identifier of the productOffering

type: string


=== isBundle
description: isBundle determines whether a productOffering represents a single productOffering (false), or a bundle of productOfferings (true).

type: boolean


=== isSellable
description: A flag indicating if this product offer can be sold stand-alone for sale or not. If this flag is false it indicates that the offer can only be sold within a bundle.

type: boolean


=== lastUpdate
description: Date and time of the last update

type: string


=== lifecycleStatus
description: Used to indicate the current lifecycle status

type: string


=== name
description: Name of the productOffering

type: string


=== statusReason
description: A string providing a complementary information on the value of the lifecycle status attribute.

type: string


=== validFor
description: The period for which the productOffering is valid

$ref of: xref:v4.1@schemas:Product:TimePeriod.adoc[]


=== version
description: ProductOffering version

type: string


=== place
description: Place defines the places where the products are sold or delivered.

type: array


=== serviceLevelAgreement
description: A service level agreement (SLA) is a type of agreement that represents a formal negotiated agreement between two parties designed to create a common understanding about products, services, priorities, responsibilities, and so forth. The SLA is a set of appropriate procedures and targets formally or informally agreed between parties in order to achieve and maintain specified Quality of Service.

$ref of: xref:v4.1@schemas:Product:SLARef.adoc[]


=== productSpecification
description: A ProductSpecification is a detailed description of a tangible or intangible object made available externally in the form of a ProductOffering to customers or other parties playing a party role.

$ref of: xref:v4.1@schemas:Product:ProductSpecificationRef.adoc[]


=== channel
description: The channel defines the channel for selling product offerings.

type: array


=== serviceCandidate
description: ServiceCandidate is an entity that makes a ServiceSpecification available to a catalog.

$ref of: xref:v4.1@schemas:Product:ServiceCandidateRef.adoc[]


=== category
description: The category resource is used to group product offerings, service and resource candidates in logical containers. Categories can contain other categories and/or product offerings, resource or service candidates.

type: array


=== resourceCandidate
description: A resource candidate is an entity that makes a ResourceSpecification available to a catalog.

$ref of: xref:v4.1@schemas:Product:ResourceCandidateRef.adoc[]


=== productOfferingTerm
description: A condition under which a ProductOffering is made available to Customers. For instance, a productOffering can be offered with multiple commitment periods.

type: array


=== productOfferingPrice
description: An amount, usually of money, that is asked for or allowed when a ProductOffering is bought, rented, or leased. The price is valid for a defined period of time and may not represent the actual price paid by a customer.

type: array


=== agreement
description: An agreement represents a contract or arrangement, either written or verbal and sometimes enforceable by law, such as a service level agreement or a customer price agreement. An agreement involves a number of other business entities, such as products, services, and resources and/or their specifications.

type: array


=== attachment
description: Complements the description of an element (for instance a product) through video, pictures...

type: array


=== marketSegment
description: provides references to the corresponding market segment as target of product offerings. A market segment is grouping of Parties, GeographicAreas, SalesChannels, and so forth.

type: array


=== bundledProductOffering
description: A type of ProductOffering that belongs to a grouping of ProductOfferings made available to the market. It inherits of all attributes of ProductOffering.

type: array


=== prodSpecCharValueUse
description: A use of the ProductSpecificationCharacteristicValue by a ProductOffering to which additional properties (attributes) apply or override the properties of similar properties contained in ProductSpecificationCharacteristicValue. It should be noted that characteristics which their value(s) addressed by this object must exist in corresponding product specification. The available characteristic values for a ProductSpecificationCharacteristic in a Product specification can be modified at the ProductOffering level. For example, a characteristic &#x27;Color&#x27; might have values White, Blue, Green, and Red. But, the list of values can be restricted to e.g. White and Blue in an associated product offering. It should be noted that the list of values in &#x27;ProductSpecificationCharacteristicValueUse&#x27; is a strict subset of the list of values as defined in the corresponding product specification characteristics.

type: array


[#all_of]
== All Of

This schema extends: xref:v4.1@schemas:Product:Addressable.adoc[]
This schema extends: xref:v4.1@schemas:Product:Extensible.adoc[]
