= PromotionCriteriaGroup

[#domain]
== Domain

This schema is part of Product

[#description]
== Description

The group of the criteria of the promotion. The logical relationship between different groups is decided by the relationTypeInGroup.


[#data_model]
== Data model

A JSON Schema corresponding to this data model can be found https://tmforum.org[here].

The data model is defined as shown below:


=== @baseType
description: The base type for use in polymorphic collections

type: string


=== @schemaLocation
description: A link to the schema describing a resource (for type extension).

type: string


=== @type
description: The class type of the actual resource (for type extension).

type: string


=== criteria
type: array


=== groupName
description: Name of the group.

type: string


=== id
description: Unique Identifier

type: string


=== relationTypeInGroup
description: AND/OR,The logical relation type amongst the various criteria inside a promotion criteria group.

type: string


[#all_of]
== All Of

