= PromotionPattern

[#domain]
== Domain

This schema is part of Product

[#description]
== Description

Detailed pattern of the promotion.The pattern decides the conditions of promotion and the benefit of the promotion to be given to the eligible customer.


[#data_model]
== Data model

A JSON Schema corresponding to this data model can be found https://tmforum.org[here].

The data model is defined as shown below:


=== @baseType
description: The base type for use in polymorphic collections

type: string


=== @schemaLocation
description: A link to the schema describing a resource (for type extension).

type: string


=== @type
description: The class type of the actual resource (for type extension).

type: string


=== action
type: array


=== criteriaGroup
type: array


=== description
description: Description

type: string


=== id
description: Unique identifier.

type: string


=== name
description: Name

type: string


=== priority
description: Priority. Smaller number means high.

type: integer


=== relationTypeAmongGroup
description: AND/OR ,The logical relation type amongst the promotion criteria group.

type: string


=== validFor
description: The period  for which the promotion pattern  is valid.

$ref of: xref:4.0.0@schemas:Product:TimePeriod.adoc[]

