= UsageVolumeBalance

[#domain]
== Domain

This schema is part of Product

[#description]
== Description

The balance (called UsageVolumeBalance in the SID model) defines the remaining allowed product usage quantity in terms of volume, time, currency or events. It corresponds to the initial allowed usage quantity minus the usage consumed on the bucket.


[#data_model]
== Data model

A JSON Schema corresponding to this data model can be found https://tmforum.org[here].

The data model is defined as shown below:


=== remainingValue
description: Numeric remaining value for the bucket given in the unit (for example 1.9). This numeric value could be used for calculation for example

$ref of: xref:v4.2@schemas:Product:Quantity.adoc[]


=== remainingValueName
description: Remaining value in a formatted string for the bucket given in the balance unit (for example 1.9 Gb). This formatted string could be used for display needs for example

type: string


=== validFor
description: Balance period between a start date time and an end date time. For prepaid bucket, the period of the balance is between the  effective date of the usage consumption report generation and the end date of the bucket. For postpaid bucket, the period of the balance is between the effective date of the usage consumption report generation and the next bill date.

$ref of: xref:v4.2@schemas:Product:TimePeriod.adoc[]


= All Of 
This schema extends: xref:v4.2@schemas:Product:Entity.adoc[]
