@startuml
hide circle
hide methods
hide stereotype
show <<Enumeration>> stereotype
skinparam class {
   BackgroundColor<<Enumeration>> #E6F5F7
   BackgroundColor<<Ref>> #FFFFE0
   BackgroundColor<<Pivot>> #FFFFFFF
   BackgroundColor<<SimpleType>> #E2F0DA
   BackgroundColor #FCF2E3
}

class ChangeRequestRelationship <<Pivot>> {
    href : Uri
    id : String
    relationshipType : String [1]
    @baseType : String
    @schemaLocation : Uri
    @type : String
}

class Characteristic  {
    id : String
    name : String [1]
    value : Any [1]
    valueType : String
    @baseType : String
    @schemaLocation : Uri
    @type : String
}

class CharacteristicRelationship  <<Ref>> {
    href : Uri
    id : String
    relationshipType : String
    @baseType : String
    @schemaLocation : Uri
    @type : String
}

class ChangeRequestRefOrValue  {
    actualEndTime : DateTime
    actualStartTime : DateTime
    budget : Money
    channel : String
    completionDate : DateTime
    description : String
    href : Uri
    id : String
    impact : String
    lastUpdateDate : DateTime
    plannedEndTime : DateTime
    plannedStartTime : DateTime
    priority : String
    requestDate : DateTime
    requestType : String
    risk : String
    riskMitigationPlan : String
    riskValue : String
    scheduledDate : DateTime
    status : ChangeRequestStatusType
    statusChangeDate : DateTime
    statusChangeReason : String
    @baseType : String
    @referredType : String
    @schemaLocation : Uri
    @type : String
}

class Note  {
    author : String
    date : DateTime
    id : String
    text : String
    @baseType : String
    @schemaLocation : Uri
    @type : String
}

class RelatedEntity  {
    href : Uri
    id : String [1]
    name : String
    role : String [1]
    @baseType : String
    @referredType : String [1]
    @schemaLocation : Uri
    @type : String
}

class Resolution  {
    code : String
    description : String
    href : Uri
    id : String
    name : String
    @baseType : String
    @schemaLocation : Uri
    @type : String
}

class Task  {
    description : String
    href : Uri
    id : String
    name : String
    state : String
    @baseType : String
    @schemaLocation : Uri
    @type : String
}

class AttachmentRefOrValue  {
    attachmentType : String
    content : string/base64
    description : String
    href : Uri
    id : String
    mimeType : String
    name : String
    size : Quantity
    url : Uri
    validFor : TimePeriod
    @baseType : String
    @referredType : String
    @schemaLocation : Uri
    @type : String
}

class WorkLog  {
    createDateTime : DateTime
    description : String
    href : Uri
    id : String
    lastUpdateDateTime : String
    @baseType : String
    @schemaLocation : Uri
    @type : String
}

class Record  {
    dateTime : DateTime
    description : String
    href : Uri
    id : String
    supportPerson : String
    @baseType : String
    @schemaLocation : Uri
    @type : String
}

class SLARef  <<Ref>> {
    href : String
    id : String [1]
    name : String
    @baseType : String
    @referredType : String
    @schemaLocation : Uri
    @type : String
}

class EntitySpecificationRef  <<Ref>> {
    href : Uri
    id : String [1]
    name : String
    version : String
    @baseType : String
    @referredType : String
    @schemaLocation : Uri
    @type : String
}

class TroubleTicketRef  <<Ref>> {
    href : Uri
    id : String [1]
    name : String
    @baseType : String
    @referredType : String
    @schemaLocation : Uri
    @type : String
}

class RelatedParty  {
    href : Uri
    id : String [1]
    name : String
    role : String
    @baseType : String
    @referredType : String [1]
    @schemaLocation : Uri
    @type : String
}

class ExternalReference  {
    externalReferenceType : String
    href : Uri
    id : String
    name : String
    @baseType : String
    @schemaLocation : Uri
    @type : String
}

class ServiceProblemRef  <<Ref>> {
    href : Uri
    id : String [1]
    name : String
    @baseType : String
    @referredType : String
    @schemaLocation : Uri
    @type : String
}

class RelatedPlaceRefOrValue  {
    href : String
    id : String
    name : String
    role : String [1]
    @baseType : String
    @referredType : String
    @schemaLocation : Uri
    @type : String
}

class ImpactEntity  {
    action : String
    href : Uri
    id : String [1]
    name : String
    role : String [1]
    @baseType : String
    @referredType : String [1]
    @schemaLocation : Uri
    @type : String
}

class ChangeRequestStatusType <<Enumeration>> {
    acknowledged
    requestForAuthorization
    waitForApproval
    approved
    scheduled
    postImplementationReview
    fallbackExecution
    cancelled
    rejected
    inProgress
    failed
    completed
}

ChangeRequestRelationship *-->  "0..*" Characteristic : changeRequestRelationshipCharacteristic

ChangeRequestRelationship *-->  "0..1" ChangeRequestRefOrValue : changeRequest

ChangeRequestRefOrValue *-right-> "0..*" Characteristic : changeRequestCharacteristic

ChangeRequestRelationship "0..*" <--* ChangeRequestRefOrValue : changeRelationship

ChangeRequestStatusType <-left[hidden]- ChangeRequestRefOrValue

ChangeRequestRefOrValue *-->  "1..*" RelatedEntity : targetEntity

ChangeRequestRefOrValue *-->  "0..*" ImpactEntity : impactEntity

ChangeRequestRefOrValue *-->  "0..*" ServiceProblemRef : problemTicket

ChangeRequestRefOrValue *-->  "0..*" ExternalReference : externalReference

ChangeRequestRefOrValue *-->  "0..*" Note : note

ChangeRequestRefOrValue *-->  "0..1" RelatedPlaceRefOrValue : location

ChangeRequestRefOrValue *-->  "0..*" TroubleTicketRef : troubleTicket

ChangeRequestRefOrValue *-->  "0..*" RelatedParty : relatedParty

ChangeRequestRefOrValue *-->  "0..1" EntitySpecificationRef : specification

ChangeRequestRefOrValue *-->  "0..*" SLARef : sla

ChangeRequestRefOrValue *-->  "0..*" AttachmentRefOrValue : attachment

ChangeRequestRefOrValue *-->  "0..*" WorkLog : workLog

ChangeRequestRefOrValue *-->  "0..1" Resolution : resolution

Characteristic *-->  "0..*" CharacteristicRelationship : characteristicRelationship

Resolution *-->  "0..*" Task : task

WorkLog *-->  "0..*" Record : record

@enduml