= AdhocCollection

[#domain]
== Domain

This schema is part of Common

[#description]
== Description




[#data_model]
== Data model

A JSON Schema corresponding to this data model can be found https://tmforum.org[here].

The data model is defined as shown below:


=== consumingApplicationId
type: string


=== producingApplicationId
type: string


=== granulatiry
$ref of: xref:4.0.0@schemas:Tmf:.adoc[]


=== outputFormat
type: string


=== collectionPeriod
$ref of: xref:4.0.0@schemas:Tmf:.adoc[]


=== trackingRecord
type: array


=== performanceIndicatorGroupSpecification
type: array


=== performanceIndicatorSpecification
type: array


=== monitoredInstancesCriteria
$ref of: xref:4.0.0@schemas:Tmf:.adoc[]


=== monitoredClassCriteria
$ref of: xref:4.0.0@schemas:Tmf:.adoc[]


{&#x27;$ref&#x27;: &#x27;../../Gc/Common/GcManagementJob.schema.json#GcManagementJob&#x27;}{&#x27;$ref&#x27;: &#x27;../../Gc/Common/GcAddressable.schema.json#GcAddressable&#x27;}{&#x27;$ref&#x27;: &#x27;../../Gc/Common/GcExtensible.schema.json#GcExtensible&#x27;}