= AgreementSpecCharacteristic

[#domain]
== Domain

This schema is part of EngagedParty

[#description]
== Description
A characteristic quality or distinctive feature of an agreement.


[#data_model]
== Data model

A JSON Schema corresponding to this data model can be found //[here].

The data model is defined as shown below:


=== configurable
description: If true, the Boolean indicates that the characteristic is configurable

type: boolean


=== description
description: A narrative that explains in detail what the characteristic is

type: string


=== name
description: Name of the characteristic being specified.

type: string


=== validFor
description: The period for which the specification characteristic is valid

$ref of: xref:v4.1@schemas:Tmf:TimePeriod.adoc[]


=== valueType
description: A kind of value that the characteristic can take on, such as numeric, text and so forth

type: string


=== specCharacteristicValue
type: array


[#all_of]
== All Of

This schema extends: xref:v4.1@schemas:Tmf:Entity.adoc[]
