= Agreement

[#domain]
== Domain

This schema is part of EngagedParty

[#description]
== Description

An agreement represents a contract or arrangement, either written or verbal and sometimes enforceable by law, such as a service level agreement or a customer price agreement. An agreement involves a number of other business entities, such as products, services, and resources and/or their specifications.


[#data_model]
== Data model

A JSON Schema corresponding to this data model can be found https://tmforum.org[here].

The data model is defined as shown below:


=== agreementPeriod
description: The time period during which the Agreement is in effect.

$ref of: xref:4.0.0@schemas:Tmf:TimePeriod.adoc[]


=== completionDate
description: Date at which the agreement is completed

$ref of: xref:4.0.0@schemas:Tmf:TimePeriod.adoc[]


=== description
description: Narrative that explains the agreement and details about the it , such as why the agreement is taking place.

type: string


=== documentNumber
description: A reference number assigned to an Agreement that follows a prescribed numbering system.

type: integer


=== href
description: Unique url identifying the agreement as a resource

type: string


=== id
description: Unique identifier for the agreement

type: string


=== initialDate
description: Date at which the agreement was initialized

type: string


=== name
description: A human-readable name for the agreement

type: string


=== statementOfIntent
description: An overview and goals of the Agreement

type: string


=== status
description: The current status of the agreement. Typical values are: in process, approved and rejected

type: string


=== agreementType
description: The type of the agreement. For example commercial

type: string


=== version
description: A string identifying the version of the agreement

type: string


=== agreementSpecification
$ref of: xref:4.0.0@schemas:Tmf:AgreementSpecificationRef.adoc[]


=== agreementItem
type: array


=== engagedParty
type: array


=== agreementAuthorization
type: array


=== characteristic
type: array


=== associatedAgreement
type: array


= All Of 
