= AlternateProductStock

[#domain]
== Domain

This schema is part of Resource

[#description]
== Description
AlternateProductStock is used to log and execute Alternate about product  stock availability


[#data_model]
== Data model

A JSON Schema corresponding to this data model can be found //[here].

== Diagram:
aaa

The data model is defined as shown below:


=== alternateAvailabilityDate
description: Alternate date when the product stock is available.

type: string


=== id
description: identifier of the Alternate product stock 

type: string


=== alternateQuantity
description: Alternate quantity available

$ref of: xref:v4.1@schemas:Tmf:Quantity.adoc[]


=== alternatePlace
description: Alternate place where product stock is available

$ref of: xref:v4.1@schemas:Tmf:PlaceRefOrValue.adoc[]


=== alternateStock
description: Alternate product stock available

$ref of: xref:v4.1@schemas:Tmf:ProductStockRef.adoc[]


=== alternateProduct
description: Alternat product available

$ref of: xref:v4.1@schemas:Tmf:ProductRefOrValue.adoc[]


[#all_of]
== All Of

This schema extends: xref:v4.1@schemas:Tmf:Extensible.adoc[]
