= ApplicableTimePeriod

[#domain]
== Domain

This schema is part of Common

[#description]
== Description
The period of time for which Capacity or CapacityDemand applies.


[#data_model]
== Data model

A JSON Schema corresponding to this data model can be found //[here].

Diagram:


The data model is defined as shown below:


=== dayOfWeek
description: A day or days representing when the schedule is applicable. For example 2, 3 represent Monday and Tuesday.

type: string


=== fromToDateTime
description: The period of time for which the schedule is applicable. 
Instance values are mutually exclusive with daysOfWeek values.

$ref of: xref:v4.2@schemas:Tmf:TimePeriod.adoc[]


=== rangeInterval
description: An indicator that specifies the inclusion or exclusion of the from and to DateTime attributes. 
Possible values are &quot;open&quot;, &quot;closed&quot;, &quot;closedBottom&quot; and &quot;closedTop&quot;.

type: string


=== validFor
$ref of: xref:v4.2@schemas:Tmf:TimePeriod.adoc[]


[#all_of]
== All Of

This schema extends: xref:v4.2@schemas:Tmf:Extensible.adoc[]
