= AppliedConsequence

[#domain]
== Domain

This schema is part of Service

[#description]
== Description
An Applied Consequence defines the action (prescribed action or notification) to take when a 
MeasureThresholdRuleViolation occurs.


[#data_model]
== Data model

A JSON Schema corresponding to this data model can be found //[here].

== Diagram:
aaa

The data model is defined as shown below:


=== appliedAction
description: The action for a violated threshold. This could be a hyperlink to 
the action.

type: string


=== description
description: A narrative that explains in detail what the consequence is.

type: string


=== name
description: A word, term, or phrase by which Consequence is known and 
distinguished from other MetricDefMeasureConsequences.

type: string


=== repeatAction
description: An indicator used to specify that a consequence should cease 
being applied if a value is in the same range as the previous value or continue being applied if a value is in the same range as the previous value.  
If the repeatAction is True, if the consequence is always applied as soon as the MetricMeasure value is in the range of values and if the repeatAction is False, the consequence is applied only if the previous MetricMeasure value was not in the same range.

type: boolean


[#all_of]
== All Of

This schema extends: xref:v4.0@schemas:Tmf:Extensible.adoc[]
