= AppliedCustomerBillingRate

[#domain]
== Domain

This schema is part of Customer

[#description]
== Description

A customer bill displays applied billing rates created before or during the billing process.


[#data_model]
== Data model

A JSON Schema corresponding to this data model can be found https://tmforum.org[here].

The data model is defined as shown below:


=== id
description: Unique identifier of the customer applied billing rate

type: string


=== href
description: Explanation: Reference of the customer applied billing rate.

type: string


=== appliedTax
type: array


=== isBilled
description: If isBilled = true then bill should be provided, if false then billingAccount should be provided

type: boolean


=== bill
$ref of: xref:4.0.0@schemas:Tmf:CustomerBillRef.adoc[]


=== date
description: Creation date of the applied billing rate

type: string


=== description
description: Additional data to be displayed on the bill for this customer applied billing rate

type: string


=== name
description: Name of the customer applied billing rate

type: string


=== periodCoverage
description: periodCoverage for RecurringCharge (RC) indicating the RC coverage period dates for different purposes, such as RC proration, display on bill, GL reporting, etc. periodCoverage for OC start and end date will be the same

$ref of: xref:4.0.0@schemas:Tmf:TimePeriod.adoc[]


=== taxExcludedAmount
$ref of: xref:4.0.0@schemas:Tmf:Money.adoc[]


=== taxIncludedAmount
$ref of: xref:4.0.0@schemas:Tmf:Money.adoc[]


=== appliedBillingRateType
description: Type of the applied billing rate : appliedBillingCharge (any kind of charge except taxation charges : recurringCharge, oneTimeCharge, usageCharge),  appliedBillingCredit (any kind of credit : rebate or productAlteration) or appliedPenaltyCharge (penalty charges such as late fees, payment rejection fees,...)

type: string


=== billingAccount
$ref of: xref:4.0.0@schemas:Tmf:BillingAccountRef.adoc[]


=== product
description: Usually this information should be provided by the PRODUCT, which implies that there is a valid reference to product. In this case, this property should be empty. For all other situations, a text or structured info could be provided using this property. Regular modelling would suggest tu use the reforvalue pattern for this case. It is not choosen here because it would generate declarational dependencies which would be hard to maintain.

$ref of: xref:4.0.0@schemas:Tmf:ProductRef.adoc[]


=== characteristic
type: array


= All Of 
