= Appointment

[#domain]
== Domain

This schema is part of Customer

[#description]
== Description

An Appointment is an arrangement to do something or meet someone at a particular time, at a place (for face to face appointment) or in a contact medium (for phone appointment).

None

[#data_model]
== Data model

A JSON Schema corresponding to this data model can be found https://tmforum.org[here].

The data model is defined as shown below:


=== attachment
type: array


=== calendarEvent
description: A calendar event reference (CalendarEventRef). The appointment is associated with a calendar event (an happening at a point of time) associated to a calendar entry.

$ref of: xref:v4.0@schemas:Tmf:CalendarEventRef.adoc[]


=== category
description: Business category : intervention for example or to be more precise after SalesIntervention, orderDeliveryIntervention,...

type: string


=== contactMedium
type: array


=== creationDate
description: Appointment creation date

type: string


=== description
description: Short free text describing the appointment

type: string


=== externalId
description: External reference known by the customer

type: string


=== href
description: Unique URI used to access to the appointment resource

type: string


=== id
description: Unique identifier of the appointment

type: string


=== lastUpdate
description: Date of last appointment update

type: string


=== note
type: array


=== relatedPlace
description: Related place defines (by reference or value) the place where the appointment will take place.

$ref of: xref:v4.0@schemas:Tmf:RelatedPlaceRefOrValue.adoc[]


=== relatedEntity
type: array


=== relatedParty
type: array


=== status
$ref of: xref:v4.0@schemas:Tmf:AppointmentStateType.adoc[]


=== validFor
description: A time period (TimePeriod). Appointment beginning date time and end date time.

$ref of: xref:v4.0@schemas:Tmf:TimePeriod.adoc[]


[#all_of]
== All Of

This schema extends: xref:v4.0@schemas:Tmf:Entity.adoc[]
