= AppUsageDataAnalytics

[#domain]
== Domain

This schema is part of Analytics

[#description]
== Description
No description on schema


[#data_model]
== Data model

A JSON Schema corresponding to this data model can be found //[here].



The data model is defined as shown below:


=== startTimestamp
description: The beginning of the measurement interval 
START_TIMESTAMP to END_TIME_STAMP defines define the period for which the measurement is done

type: string


=== endTimestamp
description: The beginning of the measurement interval 
START_TIMESTAMP to END_TIME_STAMP defines define the period for which the measurement is done

type: string


=== appInstalledTimestamp
description: The TIMESTAMP of the APP installation (empty if not in the period START_TIMESTAMP-END_TIMESTAMP)

type: string


=== appUpdatedTimestamp
description: The TIMESTAMP of the APP update (empty if not in the period START_TIMESTAMP-END_TIMESTAMP)

type: string


=== dataCreationTimestamp
description: Time stamp for data creation (e.g. system dump creation, event generation…)

type: string


=== runTimestamp
description: Time stamp for data upload run

type: string


=== validFromTimestamp
description: Time stamp for business validity of entity record

type: string


[#all_of]
== All Of

This schema extends: xref:v4.0@schemas:Tmf:Entity.adoc[]
