= Association

[#domain]
== Domain

This schema is part of Common

[#description]
== Description
Association is the class that describes a relationship between two or more entities or entity specifications based on a given association specification (relationship type). The role of each endpoint in the relationship is given by an association role. The type of endpoints in the relationship should match the ones as defined in the corresponding association role specification.
 A relationship between entity/ entity specifications may be governed by conditions and rules which are addressed by constraint references in this resource. Constraints for a relationship may include new rules and conditions in addition to those defined for the corresponding association specification


[#data_model]
== Data model

A JSON Schema corresponding to this data model can be found //[here].

Diagram:
aaa

The data model is defined as shown below:


=== description
description: Description of the association

type: string


=== lastUpdate
description: The last modified date of this association object

type: string


=== lifecycleStatus
description: Indicates the current lifecycle status

type: string


=== name
description: Name given to this association

type: string


=== validFor
description: The period for which this association is valid

$ref of: xref:v4.1@schemas:Tmf:TimePeriod.adoc[]


=== version
description: Version of this REST resource

type: string


=== associationSpec
description: The specification of this association

$ref of: xref:v4.1@schemas:Tmf:AssociationSpecificationRef.adoc[]


=== associationRole
description: The end point roles of this association

type: array


=== constraint
description: Any constraints in this association

type: array


[#all_of]
== All Of

This schema extends: xref:v4.1@schemas:Tmf:Addressable.adoc[]
This schema extends: xref:v4.1@schemas:Tmf:Extensible.adoc[]
