= AssociationRoleSpecification

[#domain]
== Domain

This schema is part of Common

[#description]
== Description

This embedded object represents the role and type of each entity involved in a relationship.


[#data_model]
== Data model

A JSON Schema corresponding to this data model can be found https://tmforum.org[here].

The data model is defined as shown below:


=== aggregation
description: A flag indicates that if this role is an aggregation or a simple relationship

type: string


=== defaultQuantity
description: Default quantity of the association role

type: integer


=== entityType
description: The target (root) entity type associated with this role

type: string


=== isNavigable
description: A flag indicating if access from the other end of association is allowed or not

type: boolean


=== isSource
description: A flag indicating if the participant involved in a uni-directional relationship is the source or not. This flag is true If the association is bi-directional

type: boolean


=== maxQuantity
description: Maximum allowed quantity of the association role

type: integer


=== minQuantity
description: Minimum allowed quantity of the association role

type: integer


=== role
description: The association role of this relationship participant

type: string


= All Of 
