= Attachment

[#domain]
== Domain

This schema is part of Common

[#description]
== Description

Complements the description of an element (for instance a product) through video, pictures...


[#data_model]
== Data model

A JSON Schema corresponding to this data model can be found https://tmforum.org[here].

The data model is defined as shown below:


=== name
description: The name of the attachment

type: string


=== description
description: A narrative text describing the content of the attachment

type: string


=== url
description: Uniform Resource Locator, is a web page address (a subset of URI)

type: string


=== content
description: The actual contents of the attachment object, if embedded, encoded as base64

type: string


=== size
description: The size of the attachment.

$ref of: xref:v5.0@schemas:Core:Quantity.adoc[]


=== validFor
description: The period of time for which the attachment is valid

$ref of: xref:v5.0@schemas:Core:TimePeriod.adoc[]


= All Of 
This schema extends: xref:v5.0@schemas:Gc:GcAttachment.adoc[]
