= Attachment

[#domain]
== Domain

This schema is part of Common

[#description]
== Description
Complements the description of an element (for instance a product) through video, pictures...


[#data_model]
== Data model

A JSON Schema corresponding to this data model can be found //[here].

== Diagram:
aaa

The data model is defined as shown below:


=== id
description: Unique identifier for this particular attachment

type: string


=== href
description: URI for this Attachment

type: string


=== name
description: The name of the attachment

type: string


=== description
description: A narrative text describing the content of the attachment

type: string


=== attachmentType
description: Attachment type such as video, picture

type: string


=== url
description: Uniform Resource Locator, is a web page address (a subset of URI)

type: string


=== mimeType
description: Attachment mime type such as extension file for video, picture and document

type: string


=== content
description: The actual contents of the attachment object, if embedded, encoded as base64

type: string


=== size
description: The size of the attachment.

$ref of: xref:v4.2@schemas:Tmf:Quantity.adoc[]


=== validFor
description: The period of time for which the attachment is valid

$ref of: xref:v4.2@schemas:Tmf:TimePeriod.adoc[]


[#all_of]
== All Of

This schema extends: xref:v4.2@schemas:Tmf:Entity.adoc[]
