= BalanceUnreserve

[#domain]
== Domain

This schema is part of Customer

[#description]
== Description
The Balance Unreserve Operation resource is a detailed description of a balance unreserve operation requested over a subscription


[#data_model]
== Data model

A JSON Schema corresponding to this data model can be found //[here].

THE DIAGRAM WILL BE IN HERE !!!
aaa

The data model is defined as shown below:


=== description
description: Description of the unreserve operation

type: string


=== href
description: A resource URI pointing to the resource in the OB that stores the detailed information about a unreserve

type: string


=== id
description: Unique Identifier within the server for the unreserve operation request

type: string


=== balanceReserve
$ref of: xref:v4.0@schemas:Tmf:BalanceReserveRef.adoc[]


=== bucketBalance
description: A reference to the bucket involved in the balance-related operation

$ref of: xref:v4.0@schemas:Tmf:BucketBalanceRef.adoc[]


=== relatedParty
$ref of: xref:v4.0@schemas:Tmf:RelatedParty.adoc[]


=== requestor
$ref of: xref:v4.0@schemas:Tmf:RelatedParty.adoc[]


=== product
$ref of: xref:v4.0@schemas:Tmf:ProductRef.adoc[]


[#all_of]
== All Of

This schema extends: xref:v4.0@schemas:Tmf:BalanceAction.adoc[]
