= BalanceAction

[#domain]
== Domain

This schema is part of Customer

[#description]
== Description
an abstract resource. example extensions are TopupBalance, AdjustBalance


[#data_model]
== Data model

A JSON Schema corresponding to this data model can be found //[here].



The data model is defined as shown below:


=== id
description: Unique Identifier for the resource

type: string


=== href
description: A reference to the resource

type: string


=== reason
description: Text describing the reason for the action/task

type: string


=== description
description: Description of the recharge operation

type: string


=== channel
description: Indicator for the channel used to request the transfer operation. Structure including at least attribute name

$ref of: xref:v4.1@schemas:Tmf:ChannelRef.adoc[]


=== amount
description: Indicate the amount on the bucket. This is always a postive value. If part of an AdjustBalance then the adjustType will indicate if the amount is to be credited or debited

$ref of: xref:v4.1@schemas:Tmf:Quantity.adoc[]


=== usageType
description: defines the type of the underlying Balance eg data,voice, any currency eg EUR, USD etc

type: string


=== impactedBucket
description: A reference to the bucket impacted by the request or the value itself.

type: array


=== bucket
description: A reference to the bucket impacted by the request or the value itself.

$ref of: xref:v4.1@schemas:Tmf:BucketRef.adoc[]


=== requestor
description: Identifier for the user/customer/entity that performs the top-up action. This can be used to indicate the identifier of an agent that performs the operation on behalf of a user via a customer service channel. Structure including at least attributes role and name.

$ref of: xref:v4.1@schemas:Tmf:RelatedParty.adoc[]


=== requestedDate
description: Date when the deduction request was received in the server

type: string


=== confirmationDate
description: Date when the deduction was confirmed in the server

type: string


=== logicalResource
description: A reference to the logical resource that can be used to identify the bucket balance for example where product ids are not unique.

$ref of: xref:v4.1@schemas:Tmf:LogicalResourceRef.adoc[]


=== product
description: A reference to the Product associated with this bucket

$ref of: xref:v4.1@schemas:Tmf:ProductRef.adoc[]


=== status
description: Status of the operation

type: string


=== partyAccount
description: A reference to the account that owns the bucket impacted by the balance related operation

$ref of: xref:v4.1@schemas:Tmf:PartyAccountRef.adoc[]


=== relatedParty
description: Used to provide information about any other entity with relation to the operation

type: array


[#all_of]
== All Of

This schema extends: xref:v4.1@schemas:Tmf:Entity.adoc[]
