= BankAccountDebit

[#domain]
== Domain

This schema is part of Customer

[#description]
== Description
A bank account debit method of payment. This could be extended to add any required authorization fields to allow recurring payments


[#data_model]
== Data model

A JSON Schema corresponding to this data model can be found //[here].

The data model is defined as shown below:


=== accountNumber
description: The Bank Account Number (this could refer to the IBAN or SWIFT number)

type: string


=== accountNumberType
description: The type of account number (e.g.: IBAN, SWIFT, ...)

type: string


=== BIC
description: The Business Identifier Code/Swift code of the financial institution where the account is located.

type: string


=== owner
description: The owner of the bank account. This is also the account name.

type: string


=== bank
description: The display name of the bank.

type: string


=== @type
type: string


[#all_of]
== All Of

This schema extends: xref:v4.2@schemas:Tmf:PaymentMethod.adoc[]
