= BankAccountDebitDetails

[#domain]
== Domain

This schema is part of EngagedParty

[#description]
== Description
Detailed information for a bank account debit. Bear in mind that this could be extended to add any required authorization fields to allow recurring payments


[#data_model]
== Data model

A JSON Schema corresponding to this data model can be found //[here].

THE DIAGRAM WILL BE IN HERE !!!
aaa

The data model is defined as shown below:


=== accountNumber
description: Bank Account Number (this could refer to the IBAN or SWIFT number)

type: integer


=== accountNumberType
description: Type of account number (e.g.: IBAN, SWIFT, ...)

type: string


=== BIC
description: Business Identifier Code/Swift code of the financial institution where the account is located

type: string


=== blank
description: Display name of the bank

type: string


=== owner
description: Owner of the bank account

type: string


[#all_of]
== All Of

This schema extends: xref:v4.1@schemas:Tmf:Entity.adoc[]
