= BankCard

[#domain]
== Domain

This schema is part of Customer

[#description]
== Description
A bank card method of payment.


[#data_model]
== Data model

A JSON Schema corresponding to this data model can be found //[here].

THE DIAGRAM WILL BE IN HERE !!!


The data model is defined as shown below:


=== brand
description: The card brand

type: string


=== cardType
description: The type of card e.g. Credit, debit etc.

type: string


=== cardNumber
description: The bank card number.

type: string


=== expirationDate
description: Expiration date of the bank card.

type: string


=== cvv
description: The security code (e.g.: CVV, CVV2) of the card.

type: string


=== lastFourDigits
description: The last four digits of the credit card.

type: string


=== nameOnCard
description: The name on the card.

type: string


=== bank
description: The bank that issued the card.

type: string


=== @type
type: string


[#all_of]
== All Of

This schema extends: xref:v4.2@schemas:Tmf:PaymentMethod.adoc[]
