= BaseEvent

[#domain]
== Domain

This schema is part of Common

[#description]
== Description
Base event with common attributes.


[#data_model]
== Data model

A JSON Schema corresponding to this data model can be found //[here].

Diagram:
aaa

The data model is defined as shown below:


=== event
$ref of: xref:v4.1@schemas:Tmf:Any.adoc[]


=== eventId
description: The identifier of the notification.

type: string


=== eventTime
description: Time of the event occurrence.

type: string


=== eventType
description: The type of the notification.

type: string


=== correlationId
description: The correlation id for this event.

type: string


=== domain
description: The domain of the event.

type: string


=== title
description: The title of the event.

type: string


=== description
description: An explnatory of the event.

type: string


=== priority
description: A priority.

type: string


=== timeOcurred
description: The time the event occured.

type: string


[#all_of]
== All Of

This schema extends: xref:v4.1@schemas:Tmf:Entity.adoc[]
