= BaseProductRefOrValue

[#domain]
== Domain

This schema is part of Product

[#description]
== Description
In the context of a product order or a product offering qualification, this data structure captures the product information useful to order or qualified  an existing subscribed product or to a new one. This is a subset of relevant product attributes for ordering and qualification


[#data_model]
== Data model

A JSON Schema corresponding to this data model can be found //[here].

THE DIAGRAM WILL BE IN HERE !!!


The data model is defined as shown below:


=== href
description: Reference of the product

type: string


=== id
description: Unique identifier of the product

type: string


=== isRef
description: indicate if ref pattern is used

type: boolean


=== name
description: This is the name of the product.

type: string


=== productCharacteristic
type: array


=== realizingResource
type: array


=== realizingService
type: array


=== isBundle
description: If true, the product is a ProductBundle which is an instantiation of a BundledProductOffering. If false, the product is a ProductComponent which is an instantiation of a SimpleProductOffering.

type: boolean


=== productRelationship
type: array


=== relatedParty
type: array


=== productSpecification
$ref of: xref:v4.2@schemas:Tmf:ProductSpecificationRef.adoc[]


=== relatedPlace
type: array


[#all_of]
== All Of

This schema extends: xref:v4.2@schemas:Tmf:Entity.adoc[]
