= BaseService

[#domain]
== Domain

This schema is part of Service

[#description]
== Description
In the context of a service order and depending on the action requested (add/modify/delete/noChange) this data structure captures the configuration to apply to an existing subscribed service or to a new one


[#data_model]
== Data model

A JSON Schema corresponding to this data model can be found //[here].

The data model is defined as shown below:


=== id
description: Unique identifier of the service

type: string


=== href
description: Reference of the service

type: string


=== serviceType
description: Business type of the service

type: string


=== name
description: Name of the service

type: string


=== state
description: The life cycle state of the service, such as: [feasibilityChecked], [designed]

$ref of: xref:v4.1@schemas:Tmf:ServiceStateType.adoc[]


=== category
description: Is it a customer facing or resource facing service

type: string


=== serviceSpecification
description: The specification from which this service was instantiated

$ref of: xref:v4.1@schemas:Tmf:ServiceSpecificationRef.adoc[]


=== serviceCharacteristic
description: A list of characteristics that characterize this service (ServiceCharacteristic [*]) 

type: array


=== serviceRelationship
description: A list of service relationships (ServiceRelationship [*]). Describes links with other service(s) in the inventory (useful for describing relies-on, relies-from between CFS for example).

type: array


=== supportingService
description: A list of supporting services (SupportingService [*]). A collection of services that support this service (bundling, link CFS to RFS)

type: array


=== supportingResource
description: A list of supporting resources (SupportingResource [*]).Note: only Service of type RFS can be associated with Resources

type: array


=== relatedParty
description: A list of related party references (RelatedParty [*]). A related party defines party or party role linked to a specific entity

type: array


=== place
description: A list of places (Place [*]). Used to define a place useful for the service (for example a delivery geographical place)

type: array


[#all_of]
== All Of

This schema extends: xref:v4.1@schemas:Tmf:Entity.adoc[]
