= BillingCycleSpecificationRef

[#domain]
== Domain

This schema is part of Customer

[#description]
== Description
BillingCycleSpecification reference. A description of when to initiate a billing cycle and the various sub steps of a billing cycle.


[#data_model]
== Data model

A JSON Schema corresponding to this data model can be found //[here].



The data model is defined as shown below:


=== dateShift
description: An offset of a billing/settlement date. The offset is expressed as number of days with regard to the start of the billing/settlement period.

type: integer


=== frequency
description: Frequency of the billing cycle (monthly for instance)

type: string


=== href
description: Reference of the billing cycle specification

type: string


=== id
description: Unique identifier of the billing cycle specification

type: string


=== name
description: A short descriptive name

type: string


=== @referredType
description: The actual type of the target instance when needed for disambiguation.

type: string


[#all_of]
== All Of

This schema extends: xref:v4.2@schemas:Tmf:Entity.adoc[]
