= BillCycleSpecification

[#domain]
== Domain

This schema is part of Customer

[#description]
== Description
A detailed description of a billing cycle and the various sub steps of a billing cycle.


[#data_model]
== Data model

A JSON Schema corresponding to this data model can be found //[here].

Diagram:


The data model is defined as shown below:


=== billingDateShift
description: An offset of a billing/settlement date. The offset is expressed as number of days with regard to the start of the billing/settlement period.

type: integer


=== billingPeriod
description: A billing time period. It can be recurring, for example: week, month, quarter of year, year .

type: string


=== chargeDateOffset
description: An offset of a date through which charges previously received by the billing system will appear on the bill. The offset is expressed as number of days with regard to the start of the BillingPeriod.

type: integer


=== creditDateOffset
description: An offset of a date through which credits previously received by the billing system will appear on the bill. The offset is expressed as number of days with regard to the start of the BillingPeriod.

type: integer


=== description
description: An explanation regarding this billing cycle. If necessary.

type: string


=== frequency
description: Frequency of the billing cycle (monthly for instance)

type: string


=== href
description: Reference of the billing cycle

type: string


=== id
description: Unique identifier of the billing cycle.

type: string


=== mailingDateOffset
description: An offset of a customer bill mailing date. The offset is expressed as number of days with regard to the start of the BillingPeriod.

type: integer


=== name
description: A short descriptive name of the actual billing cycle

type: string


=== paymentDueDateOffset
description: An offset of a payment due date. The offset is expressed as number of days with regard to the start of the BillingPeriod.

type: integer


=== validFor
description: The period for which the billing cycle is valid, expressed in a formatted structured way.

$ref of: xref:v4.2@schemas:Tmf:TimePeriod.adoc[]


[#all_of]
== All Of

This schema extends: xref:v4.2@schemas:Tmf:Entity.adoc[]
