= Bucket

[#domain]
== Domain

This schema is part of Customer

[#description]
== Description

A bucket (called UsageVolumProduct in the SID Model) represents and tracks a quantity of usage (remaining or consumed). It could be either a quantity or an amount in a currency. It can represent a fixed number of SMS,MMS, call minutes, quantity of data and so on


[#data_model]
== Data model

A JSON Schema corresponding to this data model can be found https://tmforum.org[here].

The data model is defined as shown below:


=== id
description: Unique Identifier within the server for the bucket

type: string


=== href
description: A resource URI pointing to the resource in the OB that stores the detailed information for the bucket

type: string


=== name
description: Friendly name to identify the bucket

type: string


=== description
description: Text describing the contents of the balance managed by the bucket

type: string


=== usageType
description: defines the type of the underlying Balance eg data,voice, any currency eg EUR, USD etc

type: string


=== isShared
description: True if the bucket is shared between several devices or users

type: boolean


=== relatedParty
description: Used to provide information about any other entity with relation to the balance, for instance to define customer hierarchy for the balance (e.g.: customerId, userId, )

type: array


=== partyAccount
description: A reference to the account that owns the bucket

$ref of: xref:4.0.0@schemas:Tmf:PartyAccountRef.adoc[]


=== product
type: array


=== logicalResource
type: array


=== reservedValue
description: Indicate the amount reserved on the bucket

$ref of: xref:4.0.0@schemas:Tmf:Quantity.adoc[]


=== remainingValue
description: Indicate the amount on the bucket

$ref of: xref:4.0.0@schemas:Tmf:Quantity.adoc[]


=== remainingValueName
description: Remaining amount in a formatted string for the bucket given in the balance unit (for example 1.9 Gb). This formatted string could be used for display needs for example

type: string


=== status
description: status for the bucket. active, expired, suspended

type: string


=== validFor
description: The period for which the balance in the bucket is valid

$ref of: xref:4.0.0@schemas:Tmf:TimePeriod.adoc[]


= All Of 
