= BundledProductOffering

[#domain]
== Domain

This schema is part of Product

[#description]
== Description

A type of ProductOffering that belongs to a grouping of ProductOfferings made available to the market. It inherits of all attributes of ProductOffering.


[#data_model]
== Data model

A JSON Schema corresponding to this data model can be found https://tmforum.org[here].

The data model is defined as shown below:


=== href
description: Unique reference of the BundledProductOffering

type: string


=== id
description: Unique identifier of the BundledProductOffering

type: string


=== lifecycleStatus
description: Used to indicate the current lifecycle status

type: string


=== name
description: Name of the BundledProductOffering

type: string


=== bundledProductOfferingOption
description: A set of numbers that specifies the lower and upper limits for a ProductOffering that can be procured as part of the related BundledProductOffering. Values can range from 0 to unbounded.

$ref of: xref:4.0.0@schemas:Tmf:BundledProductOfferingOption.adoc[]

