= BundledProductOfferingOption

[#domain]
== Domain

This schema is part of Product

[#description]
== Description

A set of numbers that specifies the lower and upper limits for a ProductOffering that can be procured as part of the related BundledProductOffering. Values can range from 0 to unbounded


[#data_model]
== Data model

A JSON Schema corresponding to this data model can be found https://tmforum.org[here].

The data model is defined as shown below:


=== numberRelOfferDefault
description: Default number of produc offereings that should be procured as part of the related BundledProductOffering

type: integer


=== numberRelOfferLowerLimit
description: lower limit for a product offering that can be procured as part of the related BundledProductOffering

type: integer


=== numberRelOfferUpperLimit
description: upper limit for a product offering that can be procured as part of the related BundledProductOffering

type: integer


[#all_of]
== All Of

This schema extends: xref:v4.2@schemas:Tmf:Extensible.adoc[]
