= CancelOrder

[#domain]
== Domain

This schema is part of Product

[#description]
== Description
A Order cancel is a type of task which  can  be used to place a request to cancel an order


[#data_model]
== Data model

A JSON Schema corresponding to this data model can be found //[here].

The data model is defined as shown below:


=== requestedCancellationDate
description: Date when the submitter wants the order to be cancelled

type: string


=== href
description: Hyperlink to access the cancellation request

type: string


=== id
description: id of the cancellation request (this is not an order id)

type: string


=== effectiveCancellationDate
description: Date when the order is cancelled.

type: string


=== cancellationReason
description: Reason why the order is cancelled.

type: string


=== state
description: Tracks the lifecycle status of the cancellation request, such as Acknowledged, Rejected, InProgress, Pending and so on.

$ref of: xref:v4.1@schemas:Tmf:TaskStateType.adoc[]


[#all_of]
== All Of

This schema extends: xref:v4.1@schemas:Tmf:Entity.adoc[]
