= CapacityAmount

[#domain]
== Domain

This schema is part of Common

[#description]
== Description
Quantity that defines the Capacity.


[#data_model]
== Data model

A JSON Schema corresponding to this data model can be found //[here].

THE DIAGRAM WILL BE IN HERE !!!


The data model is defined as shown below:


=== capacityAmount
description: A value and units that define the CapacityAmount, such as 10000 ea, 10B Mb. Instance values are mutually exclusive with From and To capacityAmounts and range interval.

type: string


=== capacityAmountFrom
description: The low range value that a Capacity Amount can take on.

type: string


=== capacityAmountTo
description: The upper range value that CapacityAmount can take on.

type: string


=== rangeInterval
description: An indicator that specifies the inclusion or exclusion of the capacityAmount From and capacityAmountTo attributes. 
Possible values are &quot;open&quot;, &quot;closed&quot;, &quot;closedBottom&quot; and &quot;closedTop&quot;.

type: string


[#all_of]
== All Of

This schema extends: xref:v4.2@schemas:Tmf:Extensible.adoc[]
