= Capacity

[#domain]
== Domain

This schema is part of Common

[#description]
== Description
Specific ability of an entity measured in quantity and units of quantity over an extended period.


[#data_model]
== Data model

A JSON Schema corresponding to this data model can be found https://tmforum.org[here].

The data model is defined as shown below:


=== applicableTimePeriod
description: The period of time for which Capacity or CapacityDemand applies.

type: array


=== capacityAmount
description: quantity that defines the Capacity.

$ref of: xref:4.0.0@schemas:Tmf:CapacityAmount.adoc[]


=== capacitySpec
description: capacity specification.

$ref of: xref:4.0.0@schemas:Tmf:CapacitySpecRef.adoc[]


=== place
description: Used to define a place useful for the resource. 
Used to indicate reserved resources.

$ref of: xref:4.0.0@schemas:Tmf:PlaceRefOrValue.adoc[]


=== plannedOrActualCapacity
description: An indicator that specifies whether the capacity is planned or actual.

type: string


=== relatedCapacity
description: related capacity.

type: array

