= CartPrice

[#domain]
== Domain

This schema is part of Customer

[#description]
== Description
An amount, usually of money, that represents the actual price paid by the customer for this item. May represent the total price of the shopping cart or the total of the cart item depending on the relation


[#data_model]
== Data model

A JSON Schema corresponding to this data model can be found https://tmforum.org[here].

The data model is defined as shown below:


=== description
description: A narrative that explains in detail the semantics of this order item price.

type: string


=== name
description: A short descriptive name such as &quot;Subscription price&quot;.

type: string


=== priceType
description: A category that describes the price, such as recurring, discount, allowance, penalty, and so forth

type: string


=== productOfferingPrice
description: An amount, usually of money, that is asked for or allowed when a ProductOffering is bought, rented, or leased. The price is valid for a defined period of time.

$ref of: xref:4.0.0@schemas:Tmf:ProductOfferingPriceRef.adoc[]


=== recurringChargePeriod
description: Could be month, week...

type: string


=== unitOfMeasure
description: Could be minutes, GB...

type: string


=== price
$ref of: xref:4.0.0@schemas:Tmf:Price.adoc[]


=== priceAlteration
type: array

