= Catalog

[#domain]
== Domain

This schema is part of Product

[#description]
== Description
A collection of Product Offerings, intended for a specific DistributionChannel, enhanced with additional information such as SLA parameters, invoicing and shipping details


[#data_model]
== Data model

A JSON Schema corresponding to this data model can be found //[here].

Diagram:


The data model is defined as shown below:


=== href
description: Unique reference of the catalog

type: string


=== id
description: Unique identifier of the Catalog

type: string


=== description
description: Description of this catalog

type: string


=== lastUpdate
description: Date and time of the last update

type: string


=== lifecycleStatus
description: Used to indicate the current lifecycle status

type: string


=== name
description: Name of the catalog

type: string


=== catalogType
description: Indicates if the catalog is a product, service or resource catalog

type: string


=== validFor
description: The period for which the catalog is valid

$ref of: xref:v4.1@schemas:Tmf:TimePeriod.adoc[]


=== version
description: Catalog version

type: string


=== relatedParty
description: List of parties involved in this catalog

type: array


=== category
description: List of root categories contained in this catalog

type: array


[#all_of]
== All Of

This schema extends: xref:v4.1@schemas:Tmf:Addressable.adoc[]
This schema extends: xref:v4.1@schemas:Tmf:Extensible.adoc[]
