= ChangeRequest

[#domain]
== Domain

This schema is part of Common

[#description]
== Description

Change Request is a type of request which can be used for the management and control of Change Management 
process between a customer and a service provider or between a service provider and a partner and vice versa.


[#data_model]
== Data model

A JSON Schema corresponding to this data model can be found https://tmforum.org[here].

The data model is defined as shown below:


=== actualEndTime
description: Date and time when the change implementation actually finished

type: string


=== actualStartTime
description: Date and time when the change implementation actually started

type: string


=== budget
description: The budget reserved for the change

type: string


=== channel
description: A channel represents the way the Change Request was created

type: string


=== completionDate
description: Date and time when the change request is confirmed to be completed

type: string


=== currency
description: The used currency related with cost

type: string


=== description
description: Description of the change request

type: string


=== externalId
description: ID given by the requestor to facilitate the relationship set up and subsequent searches

type: string


=== href
description: Hyperlink to access a change request

type: string


=== id
description: Identifier of a Change Request. It is created on repository side (a Change Management system)

type: string


=== impact
description: Indicates the impact of this change

type: string


=== plannedEndTime
description: Date and time when the change implementation is planned to be finished

type: string


=== plannedStartTime
description: Date and time when the change implementation is planned to be started

type: string


=== priority
description: Used by consumers to prioritize a change request in Change Management system

type: string


=== requestDate
description: Date and time when the change request is raised

type: string


=== requestType
description: Indicates the type of the change request

type: string


=== risk
description: The risk to implement this change request

type: string


=== riskMitigationPlan
description: The risk mitigation plan

type: string


=== riskValue
description: The additional cost if the risk will happen

type: string


=== scheduledDate
description: Date and time that the schedule is made

type: string


=== status
description: Status of the change request and its sub-state

type: string


=== attachment
description: The attachments of the communication message (when it is email type)

type: array


=== workLog
$ref of: xref:4.0.0@schemas:Tmf:WorkLog.adoc[]


=== incident
type: array


=== changeRequestSpecification
$ref of: xref:4.0.0@schemas:Tmf:ChangeRequestSpecification.adoc[]


=== impactEntity
type: array


=== changeRequestCharacteristic
type: array


=== targetEntity
type: array


=== relatedParty
description: The parties involved in the change request

type: array


=== resolution
$ref of: xref:4.0.0@schemas:Tmf:Resolution.adoc[]


=== sla
type: array


=== relateChangeRequest
type: array


=== category
type: array


=== note
type: array


=== location
description: The place at which the change request occurred

$ref of: xref:4.0.0@schemas:Tmf:GeographicAddressRef.adoc[]


= All Of 
This schema extends: xref:4.0.0@schemas:Tmf:Entity.adoc[]
