= CharacteristicSpecificationBase

[#domain]
== Domain

This schema is part of Common

[#description]
== Description
This class defines a characteristic specification.


[#data_model]
== Data model

A JSON Schema corresponding to this data model can be found //[here].

Diagram:


The data model is defined as shown below:


=== name
description: A word, term, or phrase by which this characteristic specification is known and distinguished from other characteristic specifications.

type: string


=== id
description: Unique ID for the characteristic

type: string


=== description
description: A narrative that explains the CharacteristicSpecification.

type: string


=== valueType
description: A kind of value that the characteristic can take on, such as numeric, text and so forth

type: string


=== configurable
description: If true, the Boolean indicates that the target Characteristic is configurable

type: boolean


=== validFor
description: The period of time for which a characteristic is applicable.

$ref of: xref:v4.2@schemas:Tmf:TimePeriod.adoc[]


=== minCardinality
description: The minimum number of instances a CharacteristicValue can take on. For example, zero to five phone numbers in a group calling plan, where zero is the value for the minCardinality.

type: integer


=== maxCardinality
description: The maximum number of instances a CharacteristicValue can take on. For example, zero to five phone numbers in a group calling plan, where five is the value for the maxCardinality.

type: integer


=== isUnique
description: An indicator that specifies if a value is unique for the specification. Possible values are; &quot;unique while value is in effect&quot; and &quot;unique whether value is in effect or not&quot;

type: boolean


=== regex
description: A rule or principle represented in regular expression used to derive the value of a characteristic value.

type: string


=== extensible
description: An indicator that specifies that the values for the characteristic can be extended by adding new values when instantiating a characteristic for a resource.

type: boolean


=== @valueSchemaLocation
description: This (optional) field provides a link to the schema describing the value type.

type: string


[#all_of]
== All Of

This schema extends: xref:v4.2@schemas:Tmf:Extensible.adoc[]
