= CharacteristicValueSpecification

[#domain]
== Domain

This schema is part of Common

[#description]
== Description

specification of a value (number or text or an object) that can be assigned to a Characteristic.


[#data_model]
== Data model

A JSON Schema corresponding to this data model can be found https://tmforum.org[here].

The data model is defined as shown below:


=== valueType
description: A kind of value that the characteristic value can take on, such as numeric, text and so forth

type: string


=== isDefault
description: If true, the Boolean Indicates if the value is the default value for a characteristic

type: boolean


=== value
description: A discrete value that the characteristic can take on, or the actual value of the characteristic

$ref of: xref:4.0.0@schemas:Tmf:Any.adoc[]


=== unitOfMeasure
description: A length, surface, volume, dry measure, liquid measure, money, weight, time, and the like. In general, a determinate quantity or magnitude of the kind designated, taken as a standard of comparison for others of the same kind, in assigning to them numerical values, as 1 foot, 1 yard, 1 mile, 1 square foot.

type: string


=== validFor
description: The period of time for which a value is applicable.

$ref of: xref:4.0.0@schemas:Tmf:TimePeriod.adoc[]


=== valueFrom
description: The low range value that a characteristic can take on

type: integer


=== valueTo
description: The upper range value that a characteristic can take on

type: integer


=== rangeInterval
description: An indicator that specifies the inclusion or exclusion of the valueFrom and valueTo attributes. If applicable, possible values are &quot;open&quot;, &quot;closed&quot;, &quot;closedBottom&quot; and &quot;closedTop&quot;.

type: string


=== regex
description: A regular expression constraint for given value

type: string


= All Of 
