= CheckServiceQualificationItem

[#domain]
== Domain

This schema is part of Service

[#description]
== Description

A ServiceQualificationItem relates to a specific service being checked in a qualification operation.


[#data_model]
== Data model

A JSON Schema corresponding to this data model can be found https://tmforum.org[here].

The data model is defined as shown below:


=== qualificationResult
description: Qualification result for serviceQualification item. It could be: - qualified (request service are available), - unqualified (requested not available and not alternate available), - alternate (requested not available but proposal available)

type: string


=== state
description: State of the serviceQualification item (acknowledged, inProgress, terminatedWithError, done)

type: string


=== qualificationRelationship
description: Structure used to describe relationship between serviceQualification item from the same serviceQualification.

type: array


=== eligibilityUnavailabilityReason
description: A list of eligibility unavailability reasons (EligibilityUnavailabilityReason [*]). Reason for eligibility result if the serviceQualification result is no (meaning the service is not available).

type: array


=== qualificationItemRelationship
description: A list of qualification item relationships used to describe relationship between serviceQualification item from the same serviceQualification.

type: array


=== terminationError
description: If qualificationItem has not been done properly this lists the error(s) that caused termination of the qualification.

type: array


=== alternateServiceProposal
description: Alternate service proposal is used when the requested service is not available with characteristic and date asked for. An alternate proposal could be a distinct service Spec close to requested one or same as requested but with a different availability date.

type: array


= All Of 
This schema extends: xref:v4.1@schemas:Tmf:ServiceQualificationItem.adoc[]
