= CheckServiceQualification

[#domain]
== Domain

This schema is part of Service

[#description]
== Description
CheckServiceQualification is used to perform a technical eligibility on service configuration(s). It allows to retrieve services that are technically available in the context of the interaction (place, party, service characteristics, ...).


[#data_model]
== Data model

A JSON Schema corresponding to this data model can be found //[here].

== Diagram:
aaa

The data model is defined as shown below:


=== serviceQualificationItem
description: A list of service qualification items.

type: array


=== provideAlternative
description: When the value is TRUE means that alternative solutions should be provided

type: boolean


=== provideUnavailabilityReason
description: When the value is TRUE means that unavailability reason are expected for non available service.

type: boolean


=== qualificationResult
description: Qualification result for this serviceQualification. It could be:  qualified (all qualification item are qualified), alternate (At least one item alternate and no item with  unqualified), unqualified (At least one item unqualified)

type: string


=== checkServiceQualificationDate
description: Date when the serviceQualification was submitted

type: string


[#all_of]
== All Of

This schema extends: xref:v4.2@schemas:Tmf:ServiceQualification.adoc[]
