= CheckShipmentQualificationItem

[#domain]
== Domain

This schema is part of EngagedParty

[#description]
== Description
A ShipmentQualificationItem relates to a specific shipment being checked in a qualification operation.


[#data_model]
== Data model

A JSON Schema corresponding to this data model can be found //[here].

The data model is defined as shown below:


=== qualificationResult
description: Qualification result for shipmentQualification item. It could be: - qualified (requested shipment is valid), - unqualified (requested shipment not valid and not alternative available), - alternate (requested shipment not valid but alternate proposal available)

type: string


=== state
description: State of the qualification item (acknowledged, inProgress, terminatedWithError, done)

type: string


=== terminationError
description: If qualificationItem has not been done properly this lists the error(s) that caused termination of the qualification.

type: array


=== qualificationRelationship
description: Structure used to describe relationship between shipementQualification item from the same shipementQualification .

type: array


=== qualificationItemRelationship
description: A list of qualification item relationships used to describe relationship between shipmentQualification item from the same shipmentQualification.

type: array


=== eligibilityUnavailabilityReason
description: A list of eligibility unavailability reasons. Reason for eligibility result if the shipmentQualification result is no (meaning the shipment is not valid).

type: array


=== alternateShipmentProposal
description: Alternate shipment proposal is used when the requested shipment is not valid as specified in the request. An alternate proposal could be a distinct shipmentSpecification close to the requested one or the same specification as requested but with a different carrier or shipping options

type: array


[#all_of]
== All Of

This schema extends: xref:v4.1@schemas:Tmf:ShipmentQualificationItem.adoc[]
