= CheckProductStockItem

[#domain]
== Domain

This schema is part of Resource

[#description]
== Description
CheckProductStockItem is used to log and execute query about one product (or configured product) stock availability


[#data_model]
== Data model

A JSON Schema corresponding to this data model can be found //[here].



The data model is defined as shown below:


=== id
description: Unique identifier of the Check Product Stock item

type: string


=== availabilityResult
description: Result of the availability like available, notAvailable, alternate

type: string


=== state
description: State of the CheckProductStockItem (acknowledged, inProgress, terminatedWithError, done)

$ref of: xref:v4.1@schemas:Tmf:TaskStateType.adoc[]


=== requestedQuantity
description: Requested quantity to be checked for this product

$ref of: xref:v4.1@schemas:Tmf:Quantity.adoc[]


=== checkedProductStock
description: the product stock too be checked

$ref of: xref:v4.1@schemas:Tmf:ProductStock.adoc[]


=== provideAlternative
description: When the value is TRUE means that alternative proposal should be provided (from other product stock, different date or quantity)

type: boolean


=== alternate
description: A list of alternate availability - from other product stock , different date or quantity

type: array


[#all_of]
== All Of

This schema extends: xref:v4.1@schemas:Tmf:Extensible.adoc[]
