= CheckWorkQualification

[#domain]
== Domain

This schema is part of EngagedParty

[#description]
== Description
CheckWorkQualification is used to validate specific units of work


[#data_model]
== Data model

A JSON Schema corresponding to this data model can be found //[here].



The data model is defined as shown below:


=== checkWorkQualificationDate
description: Date when the workQualification was submitted

type: string


=== provideAlternative
description: When the value is TRUE means that alternative solutions should be provided

type: boolean


=== provideUnavailabilityReason
description: When the value is TRUE means that unavailability reason are expected for non available units of work.

type: boolean


=== qualificationResult
description: Qualification result for this workQualification. It could be:  qualified (all qualification item are qualified), alternate (At least one item alternate and no item with  unqualified), unqualified (At least one item unqualified)

type: string


=== workQualificationItem
type: array


[#all_of]
== All Of

This schema extends: xref:v4.0@schemas:Tmf:WorkQualification.adoc[]
