= Customer

[#domain]
== Domain

This schema is part of Customer

[#description]
== Description
No description on schema


[#data_model]
== Data model

A JSON Schema corresponding to this data model can be found //[here].

Diagram:


The data model is defined as shown below:


=== href
description: Url used to reference the customer.

type: string


=== id
description: Unique identifier for Customers

type: string


=== name
description: A word, term, or phrase by which the Customer is known and distinguished from other Customers.

type: string


=== status
description: Used to track the lifecycle status of the customer.

type: string


=== statusReason
description: A string providing an explanation on the value of the status lifecycle. For instance if the status is Rejected, statusReason will provide the reason for rejection.

type: string


=== validFor
description: The time period that the Customer is valid for.

$ref of: xref:v4.1@schemas:Tmf:TimePeriod.adoc[]


=== engagedParty
description: The party - an organization or an individual - that is engaged as a customer.

$ref of: xref:v4.1@schemas:Tmf:RelatedParty.adoc[]


=== account
type: array


=== paymentMethod
type: array


=== contactMedium
type: array


=== characteristic
description: Describes the characteristic of a customer.

type: array


=== creditProfile
type: array


=== agreement
type: array


=== relatedParty
type: array


[#all_of]
== All Of

This schema extends: xref:v4.1@schemas:Tmf:Entity.adoc[]
