= Customer360LoyaltyBalanceVO

[#domain]
== Domain

This schema is part of Customer360

[#description]
== Description
A loyalty balance, containing a balance unit and value.


[#data_model]
== Data model

A JSON Schema corresponding to this data model can be found //[here].

THE DIAGRAM WILL BE IN HERE !!!


The data model is defined as shown below:


=== id
description: Unique identifier for the loyalty balance.

type: string


=== href
description: A reference to the loyalty member’s loyalty balance.

type: string


=== quantity
description: Unit and value of the balance.

type: object

$ref of: xref:v4.0@schemas:Tmf:Money.adoc[]


=== loyaltyProgramMember
description: Reference to the loyaltyProgramMember to whom the loyaltyAccount belongs.

type: object

$ref of: xref:v4.0@schemas:Tmf:LoyaltyProgramMemberRef.adoc[]


=== validFor
description: The validity period in which loyalty can be burned using the account.

type: object

$ref of: xref:v4.0@schemas:Tmf:TimePeriod.adoc[]


[#all_of]
== All Of

