= Customer360ProductOrderVO

[#domain]
== Domain

This schema is part of Customer360

[#description]
== Description
A Product Order is a type of order which  can  be used to place an order between a customer and a service provider or between a service provider and a partner and vice versa,


[#data_model]
== Data model

A JSON Schema corresponding to this data model can be found //[here].



The data model is defined as shown below:


=== cancellationDate
description: Date when the order is cancelled. This is used when order is cancelled. 

type: string


=== cancellationReason
description: Reason why the order is cancelled. This is used when order is cancelled. 

type: string


=== category
description: Used to categorize the order from a business perspective that can be useful for the OM system (e.g. &quot;enterprise&quot;, &quot;residential&quot;, ...)

type: string


=== completionDate
description: Date when the order was completed

type: string


=== description
description: Description of the product order

type: string


=== expectedCompletionDate
description: Expected delivery date amended by the provider

type: string


=== externalId
description: ID given by the consumer and only understandable by him (to facilitate his searches afterwards)

type: string


=== href
description: Hyperlink to access the order

type: string


=== id
description: ID created on repository side (OM system)

type: string


=== notificationContact
description: Contact attached to the order to send back information regarding this order

type: string


=== orderDate
description: Date when the order was created

type: string


=== priority
description: A way that can be used by consumers to prioritize orders in OM system (from 0 to 4 : 0 is the highest priority, and 4 the lowest)

type: string


=== requestedCompletionDate
description: Requested delivery date from the requestor perspective

type: string


=== requestedStartDate
description: Order fulfillment start date wished by the requestor. This is used when, for any reason, requestor cannot allow seller to begin to operationally begin the fulfillment before a date. 

type: string


=== state
description: Tracks the lifecycle status of the product order, such as Acknowledged, Rejected, InProgress, Pending and so on.

$ref of: xref:v4.1@schemas:Tmf:ProductOrderStateType.adoc[]


[#all_of]
== All Of

This schema extends: xref:v4.1@schemas:Tmf:Entity.adoc[]
