= Customer360ServiceProblemVO

[#domain]
== Domain

This schema is part of Customer360

[#description]
== Description
The problem information for Middle B which is abstracted in the service layer from the issued event information by First B


[#data_model]
== Data model

A JSON Schema corresponding to this data model can be found //[here].

The data model is defined as shown below:


=== affectedLocation
description: A list of the locations affected by the problem. At least one of affectedResource, affectedService or affectedLocation should be present.

type: array


=== affectedNumberOfServices
description: Number of affected services

type: integer


=== affectedService
description: List of affected services. At least one of affectedResource, affectedService or affectedLocation should be present.

type: array


=== category
description: Classifier for the problem. Settable. For example, this is used for distinguish the category of problem originator in [role].[category] format. Example: serviceProvider.declarer, supplier.originated, system.originated

type: string


=== correlationId
description: Additional identifier coming from an external system

type: string


=== description
description: Free form text describing the Service Problem

type: string


=== extensionInfo
description: A generic list of any type of elements. Used for vendor Extensions or loose element encapsulation from other namespaces

type: array


=== href
description: Reference to the Service Problem

type: string


=== id
description: Identifier of the service problem

type: string


=== impactImportanceFactor
description: Impact Importance is characterized by an Impact Importance Factor: overall importance of the impact of all the affected services, e.g. 0 (zero impact) to 100 (worst impact). The Impact Importance is a calculated field which is set by the OSS determining the impact.

type: string


=== originatingSystem
description: Indicates where the problem was generated

type: string


=== priority
description: An indication varying from 1 (highest) to 10 (lowest) of how important it is for the service provider to correct the Service Problem.

type: integer


=== problemEscalation
description: Indicates if this service problem has been escalated or not. Possible values are 0 to 10. A value of zero means no escalation. The meanings of values 1-10 are to be determined by the user of the interface, but they show increasing levels of escalation.

type: string


=== reason
description: Free text or optionally structured text. It can be Unknown.

type: string


=== relatedObject
description: List of objects associated to this problem

type: array


=== responsibleParty
description: Individual or organization responsible for handling this problem

$ref of: xref:v4.2@schemas:Tmf:RelatedParty.adoc[]


=== relatedParty
description: List of parties or party roles playing a role within the service problem

type: array


=== rootCauseResource
description: Resource(s) that are associated to the underlying service problems that are the Root Cause of this one if any (used only if applicable).

type: array


=== resolutionDate
description: Time the problem was resolved

type: string


=== status
description: The current status of the service problem. Possible values are Submitted, Rejected, Acknowledged, In Progress [Held, Pending], Resolved, Closed, and Cancelled.

type: string


=== statusChangeDate
description: Time the problem was last status changed

type: string


=== statusChangeReason
description: The reason of state change

type: string


=== timeChanged
description: Time the problem was last changed

type: string


=== timeRaised
description: Time the problem was raised

type: string


=== underlyingProblem
description: A list of underlying problems. Relevant only if this problem is derived from other problems.

type: array


[#all_of]
== All Of

This schema extends: xref:v4.2@schemas:Tmf:Entity.adoc[]
