= Customer360RecommendationVO

[#domain]
== Domain

This schema is part of Customer360

[#description]
== Description
Recommendation API is used to recommend offering quickly based on the history and real-time context of customer. It is a real-time and personalized recommendation API. It is usually provided by e-commerce or BSS, CRM system in omni-channel.


[#data_model]
== Data model

A JSON Schema corresponding to this data model can be found //[here].

THE DIAGRAM WILL BE IN HERE !!!


The data model is defined as shown below:


=== description
type: string


=== href
description: Hypertext Reference of the recommendation

type: string


=== id
description: Unique identifier of recommendation

type: string


=== name
description: Name of recommendation

type: string


=== recommendationType
description: The type of recommendation

type: string


=== validFor
description: The period in which the recommendation is valid

$ref of: xref:v4.2@schemas:Tmf:TimePeriod.adoc[]


=== order
$ref of: xref:v4.2@schemas:Tmf:ProductOrderRef.adoc[]


=== location
description: The geographic location which the recommendation is related to

$ref of: xref:v4.2@schemas:Tmf:GeographicLocationRef.adoc[]


=== channel
$ref of: xref:v4.2@schemas:Tmf:ChannelRef.adoc[]


=== category
description: The category for grouping recommendations

$ref of: xref:v4.2@schemas:Tmf:CategoryRef.adoc[]


=== shoppingCart
description: The shopping cart which the recommendation is related to

$ref of: xref:v4.2@schemas:Tmf:ShoppingCartRef.adoc[]


=== party
$ref of: xref:v4.2@schemas:Tmf:RelatedParty.adoc[]


=== item
type: array


[#all_of]
== All Of

This schema extends: xref:v4.2@schemas:Tmf:Entity.adoc[]
