= CustomerHealthStatsAnalytics

[#domain]
== Domain

This schema is part of Analytics

[#description]
== Description
No description on schema


[#data_model]
== Data model

A JSON Schema corresponding to this data model can be found //[here].

THE DIAGRAM WILL BE IN HERE !!!


The data model is defined as shown below:


=== dateOfBirthDate
description: Date of birth

type: string


=== bodyWeightKg
description: the weight of people in kg

type: number


=== bodyHeightCm
description: the height of people in cm

type: number


=== weightHeightReadingDate
description: Date when test or reading was taken

type: string


=== bpReadingDate
description: Date when test or reading was taken

type: string


=== restingHeartRateBpm
description: Resting heart rate in beats per minute (BPM)

type: number


=== heartRateReadingDate
description: Date when test or reading was taken

type: string


=== bodyTemperatureCelsius
description: Body temperature in Celsius

type: number


=== bodyTempReadingDate
description: Date when test or reading was taken

type: string


=== bloodSugarReadingDate
description: Date when test or reading was taken

type: string


=== cholesterolReadingDate
description: Date when test or reading was taken

type: string


=== restingRespirationRateBpm
description: Number of breaths while resting in breaths per minute (BPM)

type: number


=== respirationReadingDate
description: Date when test or reading was taken

type: string


=== dataCreationTimestamp
description: Time stamp for data creation (e.g. system dump creation, event generation…)

type: string


=== runTimestamp
description: Time stamp for data upload run

type: string


=== validFromTimestamp
description: Time stamp for business validity of entity record

type: string


[#all_of]
== All Of

This schema extends: xref:v4.1@schemas:Tmf:Entity.adoc[]
