= DeviceAnalytics

[#domain]
== Domain

This schema is part of Analytics

[#description]
== Description
No description on schema


[#data_model]
== Data model

A JSON Schema corresponding to this data model can be found https://tmforum.org[here].

The data model is defined as shown below:


=== timestamp
type: string


=== manufacturedDated
description: manufactoring date

type: string


=== purchaseDate
description: customer purchase date

type: string


=== activationDate
description: date the device was activated

type: string


=== firstUseDate
description: date the device was first used on the network

type: string


=== guranteeExpirationDate
description: the date the device guarantee expires

type: string


=== dataCreationTimestamp
description: Time stamp for data creation (e.g. system dump creation, event generation…)

type: string


=== runTimestamp
description: Time stamp for data upload run

type: string


=== validFromTimestamp
description: Time stamp for business validity of entity record

type: string

