= DigitalIdentity

[#domain]
== Domain

This schema is part of EngagedParty

[#description]
== Description
DigitalIdentity is a class that allow to describe a digital identity for an individual or a resource or a specific party role. One of these three MUST be provided. If an individual is provided, this identity will be for all her/his partyRole. To avoid confusion it is recommended in this case to not provide partyRoleIdentified.


[#data_model]
== Data model

A JSON Schema corresponding to this data model can be found //[here].



The data model is defined as shown below:


=== creationDate
description: Date and time of the Digital Identity creation (timestamp)

type: string


=== lastUpdate
description: Date and time of the Digital Identity last update (timestamp)

type: string


=== status
description: Used to indicate the current lifecycle status of this digital identity (unknown, active, suspended, archived).

type: string


=== nickname
description: Nickname associated to this digital identity (like Juanito17 or the QuebecMoose etc...).

type: string


=== validFor
description: The period for which this digial identity is valid.

$ref of: xref:v4.1@schemas:Tmf:TimePeriod.adoc[]


=== credential
description: A list of credential/authentification method that are used for this digital identity.

type: array


=== contactMedium
description: List of contact medium associated with the digital identity.

type: array


=== attachment
description: List of attachment associated with this digital identity. Could be use to link a cute cat or moose picture to a digital identity for example.

type: array


=== relatedParty
description: Parties who have an interest in this digital identity (like the organization in charge of providing identity). This is NOT the party identified by this digital identity.

type: array


=== partyRoleIdentified
description: Related Parties who are identified by this digital identity.

type: array


=== individualIdentified
description: Individual identified by this digital identity. In this case the digitial identity is for all her/his role. It is recommended to not provide partyRoleIdentified if individualIdentified provided 

$ref of: xref:v4.1@schemas:Tmf:PartyRef.adoc[]


=== resourceIdentified
description: Resource identified by this digital identity. It is recommended to no provided individualIdentified or partyRoleIdentified if resourceIdentified provided.

$ref of: xref:v4.1@schemas:Tmf:ResourceRef.adoc[]


[#all_of]
== All Of

This schema extends: xref:v4.1@schemas:Tmf:Entity.adoc[]
This schema extends: xref:v4.1@schemas:Tmf:Addressable.adoc[]
