= EligibilityOfferAnalytics

[#domain]
== Domain

This schema is part of Analytics

[#description]
== Description

No description on schema

None

[#data_model]
== Data model

A JSON Schema corresponding to this data model can be found https://tmforum.org[here].

The data model is defined as shown below:


=== eligibilityCreationDate
description: Date when Eligibility Offer was created

type: string


=== eligibilityStartDate
description: Eligibility Offer start or effective date

type: string


=== eligibilityEndDate
description: Eligibility Offer end or termination date

type: string


=== eligibilityValueAmt
description: When required, captures the value, number, percentage, etc. of the Eligibility Offer.

type: number


=== sizeOfHouseholdCount
description: Number of people in household

type: number


=== disposableIncomeAmt
$ref of: xref:v4.0@schemas:Tmf:Money.adoc[]


=== dataCreationTimestamp
description: Time stamp for data creation (e.g. system dump creation, event generation…)

type: string


=== runTimestamp
description: Time stamp for data upload run

type: string


=== validFromTimestamp
description: Time stamp for business validity of entity record

type: string


[#all_of]
== All Of

This schema extends: xref:v4.0@schemas:Tmf:Entity.adoc[]
