= EntitySpecRelationship

[#domain]
== Domain

This schema is part of Common

[#description]
== Description

A migration, substitution, dependency or exclusivity relationship between/among entity specifications.


[#data_model]
== Data model

A JSON Schema corresponding to this data model can be found https://tmforum.org[here].

The data model is defined as shown below:


=== href
description: Reference of the target EntitySpecification

type: string


=== id
description: Unique identifier of target EntitySpecification

type: string


=== name
description: The name given to the target entity specification instance

type: string


=== role
description: The association role for this entity specification

type: string


=== relationshipType
description: Type of relationship such as migration, substitution, dependency, exclusivity

type: string


=== validFor
description: The period for which the entitySpecRelationship is valid

$ref of: xref:v4.0@schemas:Tmf:TimePeriod.adoc[]


=== associationSpec
$ref of: xref:v4.0@schemas:Tmf:AssociationSpecRef.adoc[]


= All Of 
This schema extends: xref:v4.0@schemas:Tmf:Entity.adoc[]
