= EntityAttachment

[#domain]
== Domain

This schema is part of Common

[#description]
== Description
Complements the description of an entity through video, pictures...


[#data_model]
== Data model

A JSON Schema corresponding to this data model can be found //[here].

== Diagram:
aaa

The data model is defined as shown below:


=== description
description: A narrative text describing the content of the attachment

type: string


=== href
description: Reference of the attachment

type: string


=== id
description: Unique identifier of the attachment

type: string


=== mimeType
description: Attachment mime type such as extension file for video, picture and document

type: string


=== name
description: name given to the attachment

type: string


=== uri
description: Uniform Resource Identifier (URI) of the attachment

type: string


=== validFor
description: The period for which this attachment is valid

$ref of: xref:v4.0@schemas:Tmf:TimePeriod.adoc[]


[#all_of]
== All Of

This schema extends: xref:v4.0@schemas:Tmf:Entity.adoc[]
