= EntityCatalogItem

[#domain]
== Domain

This schema is part of Common

[#description]
== Description

An EntityCatalogItem is an entity that allows any ProductOffering, ServiceCandidate, ResourceCandidate, or even any object inheriting from RootEntity, to be available to a catalog. The CatalogSpecification and Policy of the catalog governs the content of the EntityCatalogItem. This API addresses only EntitySpecification items extended from RootEntity as EntityCatalogItem.
The EntityCatalogItem resource (JSON format) represents a set of characteristics that define the values given by the EntityCatalogItem.


[#data_model]
== Data model

A JSON Schema corresponding to this data model can be found https://tmforum.org[here].

The data model is defined as shown below:


=== description
description: Description of this REST resource

type: string


=== lastUpdate
description: Date and time of the last update of this REST resource

type: string


=== lifecycleStatus
description: Used to indicate the current lifecycle status of this catalog item

type: string


=== name
description: Name given to this REST resource

type: string


=== validFor
description: The period for which this REST resource is valid

$ref of: xref:v4.0@schemas:Tmf:TimePeriod.adoc[]


=== category
type: array


=== specification
description: The specification implied by this candidate

$ref of: xref:v4.0@schemas:Tmf:EntitySpecificationRef.adoc[]


=== version
description: EntityCatalogItem version

type: string


= All Of 
This schema extends: xref:v4.0@schemas:Tmf:Addressable.adoc[]
This schema extends: xref:v4.0@schemas:Tmf:Extensible.adoc[]
