= eUICCUsageAnalytics

[#domain]
== Domain

This schema is part of Analytics

[#description]
== Description

No description on schema


[#data_model]
== Data model

A JSON Schema corresponding to this data model can be found https://tmforum.org[here].

The data model is defined as shown below:


=== customerStatusDate
description: Date when status was set or changed last time

type: string


=== customerCreationDate
description: Date when customer was created

type: string


=== customerBirthDate
description: Date of birth

type: string


=== arpuAmount
$ref of: xref:v4.1@schemas:Tmf:Money.adoc[]


=== dataPeriodStart
description: The statrt of the period for which the usage info  is collected

type: string


=== dataPeriodEnd
description: The end of the period for which the usage info  is collected

type: string


=== activityMostRecentDate
description: Most recent activity date indicating recency of information

type: string


=== dataCreationTimestamp
description: Time stamp for data creation (e.g. system dump creation, event generation…)

type: string


=== runTimestamp
description: Time stamp for data upload run

type: string


=== validFromTimestamp
description: Time stamp for business validity of entity record

type: string


[#all_of]
== All Of

This schema extends: xref:v4.1@schemas:Tmf:Entity.adoc[]
