= Event

[#domain]
== Domain

This schema is part of Common

[#description]
== Description
event with common attributes.


[#data_model]
== Data model

A JSON Schema corresponding to this data model can be found //[here].



The data model is defined as shown below:


=== eventId
description: The identifier of the notification.

type: string


=== eventTime
description: Time of the event occurrence.

type: string


=== eventType
description: The type of the notification.

type: string


=== correlationId
description: The correlation id for this event.

type: string


=== domain
description: The domain of the event.

type: string


=== title
description: The title of the event.

type: string


=== description
description: An explnatory of the event.

type: string


=== priority
description: A priority.

type: string


=== timeOccurred
description: The time the event occurred.

type: string


=== source
description: Source Entity described by EntityRef

$ref of: xref:v4.0@schemas:Tmf:EntityRef.adoc[]


=== reportingSystem
description: Reporting System described by EntityRef

$ref of: xref:v4.0@schemas:Tmf:EntityRef.adoc[]


=== relatedParty
type: array


=== analyticCharacteristic
type: array


=== event
description: The event linked to the involved resource object

$ref of: xref:v4.0@schemas:Tmf:Any.adoc[]


[#all_of]
== All Of

This schema extends: xref:v4.0@schemas:Tmf:Entity.adoc[]
