= FeatureSpecificationCharacteristicRelationship

[#domain]
== Domain

This schema is part of Common

[#description]
== Description
An aggregation, migration, substitution, dependency or exclusivity relationship between/among FeatureSpecificationCharacteristics.


[#data_model]
== Data model

A JSON Schema corresponding to this data model can be found //[here].

THE DIAGRAM WILL BE IN HERE !!!


The data model is defined as shown below:


=== relationshipType
description: Type of relationship such as aggregation, migration, substitution, dependency, exclusivity

type: string


=== name
description: Name of the target characteristic

type: string


=== characteristicId
description: Unique identifier of the characteristic within the the target feature specification

type: string


=== featureId
description: Unique identifier of the target feature specification within the resource specification.

type: string


=== resourceSpecificationId
description: Unique identifier of the resource specification containing the target feature and feature characteristic

type: string


=== resourceSpecificationHref
description: Hyperlink reference to the resource specification containing the target feature and feature characteristic

type: string


=== validFor
description: The period for which the object is valid

$ref of: xref:v4.1@schemas:Tmf:TimePeriod.adoc[]


[#all_of]
== All Of

This schema extends: xref:v4.1@schemas:Tmf:Entity.adoc[]
