= FeatureSpecificationRelationship

[#domain]
== Domain

This schema is part of Common

[#description]
== Description
Relationship between feature specifications


[#data_model]
== Data model

A JSON Schema corresponding to this data model can be found //[here].

THE DIAGRAM WILL BE IN HERE !!!


The data model is defined as shown below:


=== relationshipType
description: This is the type of the feature specification relationship.

type: string


=== featureId
description: Unique identifier of the target feature specification.

type: string


=== parentSpecificationId
description: Unique identifier of the parent specification containing the target feature

type: string


=== parentSpecificationHref
description: Hyperlink reference to the parent specification containing the target feature

type: string


=== name
description: This is the name of the target feature specification.

type: string


=== validFor
description: The period for which this feature spoecification relationship is valid.

$ref of: xref:v4.1@schemas:Tmf:TimePeriod.adoc[]


[#all_of]
== All Of

This schema extends: xref:v4.1@schemas:Tmf:Extensible.adoc[]
