= FilterAssetGroup

[#domain]
== Domain

This schema is part of Common

[#description]
== Description
Defines a group of assets (entities) to which access can be controlled, using a filter expression. Any entities matching the filter are implicitly included in the group. The embedded example implies all Products owned by a specific customer


[#data_model]
== Data model

A JSON Schema corresponding to this data model can be found //[here].

Diagram:
aaa

The data model is defined as shown below:


=== entityType
description: The type of entity in the group, equivalent to @type in the entity definition. Must be a top-level managed entity. The filter expression is applied to this entity type.

type: string


=== filter
description: The filter expression that defines the entities covered by a permission set, format of the filter is as per the simple query parameter filter as defined in TMF630

type: string


[#all_of]
== All Of

This schema extends: xref:v4.2@schemas:Tmf:AssetGroup.adoc[]
