= GeographicLocation

[#domain]
== Domain

This schema is part of Common

[#description]
== Description
A GeographicLocation is a pure-virtual super-class to the GeoJSON-aligned geometries of Point (addresses and locations), MultiPoint, LineString (streets, highways and boundaries), MultiLineString and Polygon (countries, provinces, tracts of land). Use the @type attribute to specify which of these is being specified by the geometry attribute.


[#data_model]
== Data model

A JSON Schema corresponding to this data model can be found //[here].

Diagram:


The data model is defined as shown below:


=== id
description: Unique identifier of the geographic location

type: string


=== href
description: An URI used to access to the geographic location resource

type: string


=== @type
description: The name of the GeoJSON structure used in the geometry attribute

type: string


=== bbox
description: A bounding box array that contains the geometry. The axes order follows the axes order of the geometry

type: array


[#all_of]
== All Of

This schema extends: xref:v4.2@schemas:Tmf:Place.adoc[]
