= GeographicAddressValidation

[#domain]
== Domain

This schema is part of Common

[#description]
== Description
This resource is used to manage address validation request and response


[#data_model]
== Data model

A JSON Schema corresponding to this data model can be found //[here].

The data model is defined as shown below:


=== href
description: An URI used to access to the address validation resource

type: string


=== id
description: Unique identifier of the Address Validation

type: string


=== provideAlternative
description: Indicator provided by the requester to specify if alternate addresses must be provided in case of partial or fail result.

type: boolean


=== state
$ref of: xref:v4.0@schemas:Tmf:TaskStateType.adoc[]


=== validationDate
description: Date when the address validation is performed

type: string


=== validationResult
description: Result of the address validation (success, partial, fails)

type: string


=== submittedGeographicAddress
description: the address as submitted to validation

$ref of: xref:v4.0@schemas:Tmf:GeographicAddress.adoc[]


=== validGeographicAddress
description: the correct form of the validated address in case of validation success

$ref of: xref:v4.0@schemas:Tmf:GeographicAddress.adoc[]


=== alternateGeographicAddress
type: array


[#all_of]
== All Of

This schema extends: xref:v4.0@schemas:Tmf:Entity.adoc[]
