= ImpactedBucket

[#domain]
== Domain

This schema is part of Customer

[#description]
== Description
A resource that references other buckets that have been impacted by the action of type TopupBalance,AdjustBalance,TransferBalance or ReserveBalance


[#data_model]
== Data model

A JSON Schema corresponding to this data model can be found //[here].

Diagram:


The data model is defined as shown below:


=== name
description: Friendly name to identify the bucket

type: string


=== description
description: Text describing the contents of the balance managed by the bucket

type: string


=== amountBefore
description: Indicates the amount remaiing on the impacted bucket

$ref of: xref:v4.0@schemas:Tmf:Quantity.adoc[]


=== amountAfter
description: Indicates the amount after on the impacted bucket after the action has completed.

$ref of: xref:v4.0@schemas:Tmf:Quantity.adoc[]


=== requestedDate
description: Date when the deduction request was received in the server

type: string


=== confirmationDate
description: Date when the deduction was confirmed in the server

type: string


=== bucket
description: A reference to the bucket impacted by the request or the value itself.

$ref of: xref:v4.0@schemas:Tmf:BucketRef.adoc[]


=== item
type: array


[#all_of]
== All Of

This schema extends: xref:v4.0@schemas:Tmf:Entity.adoc[]
