= ImportJob

[#domain]
== Domain

This schema is part of Common

[#description]
== Description
Represents a task used to import resources from a file


[#data_model]
== Data model

A JSON Schema corresponding to this data model can be found //[here].

The data model is defined as shown below:


=== completionDate
description: Date at which the job was completed

type: string


=== contentType
description: Indicates the format of the imported data

type: string


=== creationDate
description: Date at which the job was created

type: string


=== errorLog
description: Reason for failure if status is failed

type: string


=== href
description: Reference of the import job

type: string


=== id
description: Identifier of the import job

type: string


=== path
description: URL of the root resource where the content of the file specified by the import job must be applied

type: string


=== status
description: Status of the import job (not started, running, succeeded, failed)

$ref of: xref:v4.2@schemas:Tmf:JobStateType.adoc[]


=== url
description: URL of the file containing the data to be imported

type: string


[#all_of]
== All Of

This schema extends: xref:v4.2@schemas:Tmf:Entity.adoc[]
