= IndividualIdentification

[#domain]
== Domain

This schema is part of EngagedParty

[#description]
== Description

Represents our registration of information used as proof of identity by an individual (passport, national identity card, drivers license, social security number, birth certificate)


[#data_model]
== Data model

A JSON Schema corresponding to this data model can be found https://tmforum.org[here].

The data model is defined as shown below:


=== identificationId
description: Identifier

type: string


=== issuingAuthority
description: Authority which has issued the identifier, such as: social security, town hall

type: string


=== issuingDate
description: Date at which the identifier was issued

type: string


=== identificationType
description: Identification type (passport, national identity card, drivers license, social security number, birth certificate)

type: string


=== validFor
description: The period for which the identification information is valid.

$ref of: xref:v4.1@schemas:Tmf:TimePeriod.adoc[]


=== attachment
$ref of: xref:v4.1@schemas:Tmf:AttachmentRefOrValue.adoc[]


[#all_of]
== All Of

This schema extends: xref:v4.1@schemas:Tmf:Entity.adoc[]
