= JeopardyAlert

[#domain]
== Domain

This schema is part of Common

[#description]
== Description
A JeopardyAlert represents a predicted exception during a process that may cause a risk to complete successfully the process.


[#data_model]
== Data model

A JSON Schema corresponding to this data model can be found //[here].

== Diagram:
aaa

The data model is defined as shown below:


=== id
description: identifier of the JeopardyAlert

type: string


=== alertDate
description: A date time( DateTime). The date that the alert issued

type: string


=== name
description: A string used to give a name to the jeopardy alert

type: string


=== jeopardyType
description: A string represents the type of jeopardy/risk like Normal, Hazard, Critical, ...

type: string


=== exception
description:  The exception associated with this jeopardy alert

type: string


=== message
description: A string represents the message of the alert

type: string


[#all_of]
== All Of

This schema extends: xref:v4.2@schemas:Tmf:Extensible.adoc[]
