= JSONPathAssetGroup

[#domain]
== Domain

This schema is part of Common

[#description]
== Description
Defines a group of assets (entities) to which access can be controlled, using a JSON Path expression. Any entities matching the JSON Path expression are implicitly included in the group. The embedded example implies all TroubleTickets with status Pending


[#data_model]
== Data model

A JSON Schema corresponding to this data model can be found //[here].

Diagram:
aaa

The data model is defined as shown below:


=== entityType
description: The type of entity in the group, equivalent to @type in the entity definition. Must be a top-level managed entity. The JSON Path expression is applied to this entity type.

type: string


=== JSONPath
description: The JSON Path expression that defines the entities covered by a permission set, format of the filter is as per the JSON Path query parameter filter as defined in TMF630

type: string


[#all_of]
== All Of

This schema extends: xref:v4.1@schemas:Tmf:AssetGroup.adoc[]
