= LoyaltyProgramProductSpec

[#domain]
== Domain

This schema is part of Product

[#description]
== Description

A reference to a loyalty program specification.


[#data_model]
== Data model

A JSON Schema corresponding to this data model can be found https://tmforum.org[here].

The data model is defined as shown below:


=== brand
description: The manufacturer or trademark of the specification.

type: string


=== description
description: A narrative that explains in detail what the product specification is.

type: string


=== id
description: Unique identifier for the product specification.

type: string


=== href
description: A reference to the product specification.

type: string


=== lifeCycleStatus
description: The condition of the product specification, such as active, inactive, planned.

type: string


=== name
description: The name of the product specification.

type: string


=== needsLoyaltyAccount
description: A narrative that explains in detail what the product specification is.

type: boolean


=== productNumber
type: string


=== validFor
$ref of: xref:v4.0@schemas:Tmf:TimePeriod.adoc[]


= All Of 
