= LoyaltyProgramProduct

[#domain]
== Domain

This schema is part of Product

[#description]
== Description

An instance of a loyalty program specification, linked to a specified loyalty member.

None

[#data_model]
== Data model

A JSON Schema corresponding to this data model can be found https://tmforum.org[here].

The data model is defined as shown below:


=== id
description: Unique identifier for the loyalty program product.

type: string


=== href
description: A reference to the loyalty account.

type: string


=== name
description: A word, term, or phrase by which the product is known and distinguished from other products.

type: string


=== description
description: An explanation of what the product is.

type: string


=== productStatus
description: The condition of the product, such as planned, designed, activated, disconnected.

type: string


=== characteristic
description: Name value pairs of product characteristics.

type: array


=== loyaltyProgramProductSpec
type: object

$ref of: xref:v4.1@schemas:Tmf:LoyaltyProgramProductSpecRef.adoc[]


=== loyaltyAccount
type: object

$ref of: xref:v4.1@schemas:Tmf:LoyaltyAccountRef.adoc[]


=== validFor
$ref of: xref:v4.1@schemas:Tmf:TimePeriod.adoc[]


[#all_of]
== All Of

This schema extends: xref:v4.1@schemas:Tmf:Entity.adoc[]
