= LoyaltyAction

[#domain]
== Domain

This schema is part of Product

[#description]
== Description
Contains information on a loyalty action that should be applied should certain conditions be met for a loyalty rule and program.


[#data_model]
== Data model

A JSON Schema corresponding to this data model can be found //[here].

THE DIAGRAM WILL BE IN HERE !!!
aaa

The data model is defined as shown below:


=== id
description: Unique identifier for the loyalty event type.

type: string


=== href
description: A reference to the loyalty event type.

type: string


=== actionType
description: The type of loyalty action.

type: string


=== actionAttributes
description: Additional attributes required to perform the action. These attributes will depend on the type of the loyalty action. For example, if it is a LoyaltyEarn action, there will be a “quantity” attribute value pair indicating how many points should be earned.

type: object

$ref of: xref:v4.1@schemas:Tmf:Any.adoc[]


=== body
description: The body if the request that is made when this action i executed. The body is assumed to be of type text/json. Any tokens denoted with {} will be replaced by attributes present in: Member profile, actionAttributes or event attributes in the loyalty event request.

type: object

$ref of: xref:v4.1@schemas:Tmf:Any.adoc[]


=== headers
description: The HTTP headers that is added to the action call.

type: object

$ref of: xref:v4.1@schemas:Tmf:Any.adoc[]


=== version
description: A string that identifies the version of the loyalty action.

type: string


=== commonName
description: A user-friendly identifier of the loyalty execution point.

type: string


=== description
description: A free-form description of the loyalty execution point.

type: string


=== action
description: The HTTP operation to be used when calling the endpoint

type: string


=== endpoint
description: The endpoint to call to trigger a BusinessInteraction, CustomerOrder or LoyaltyEarn.

type: string


[#all_of]
== All Of

