= ManagedEntity

[#domain]
== Domain

This schema is part of Common

[#description]
== Description

ManagedEntity represents an entity that describes the common set of attributes shared by all concrete entities (e.g. Resource, Service, ..) in the Entity Inventory. A ManagedEntity may concern a simple concept, such as a logical point of communication, or a complex concept, such as an Application or System 


[#data_model]
== Data model

A JSON Schema corresponding to this data model can be found https://tmforum.org[here].

The data model is defined as shown below:


=== description
description: free-text description of the entity

type: string


=== validFor
description: The period for which this REST resource is valid

$ref of: xref:4.0.0@schemas:Tmf:TimePeriod.adoc[]


=== isBundle
description: isBundle determines whether an entity represents a single entity (false), or a bundle of entities(true).

type: boolean


=== isExternal
description: isExternal determines whether an entity represents an external entity in the inventory.

type: boolean


=== lastUpdate
description: Date and time of the last update of this REST resource

type: string


=== lifecycleStatus
description: Used to indicate the current lifecycle status of this managed entity

type: string


=== statusChangeDate
description: A date time( DateTime). The date that the entity status changed to the current one

type: string


=== name
description: A string used to give a name to the entity

type: string


=== context
description: A string used to give a context to the entity

type: string


=== version
description: A field that identifies the specific version of an instance of an entity.

type: string


=== entitySpecification
$ref of: xref:4.0.0@schemas:Tmf:EntitySpecificationRef.adoc[]


=== entityRelationship
description: A list of entities related to this entity

type: array


=== characteristic
type: array


=== relatedParty
type: array


=== attachment
description: Attachments that may be of relevance to this entity, such as picture, document, media

type: array


=== note
type: array


= All Of 
This schema extends: xref:4.0.0@schemas:Tmf:Entity.adoc[]
