= MeasurementProductionJobAVCN

[#domain]
== Domain

This schema is part of Common

[#description]
== Description

This is a notification generated from the entity MeasurementProductionJob

None

[#data_model]
== Data model

A JSON Schema corresponding to this data model can be found https://tmforum.org[here].

The data model is defined as shown below:


=== granularity
$ref of: xref:v4.1@schemas:Tmf:ExecutionState.adoc[]


=== monitoredInstancesCriteria
type: array


=== monitoredClassCriteria
type: array


=== lastModifiedTime
description: The last time that a measurement job was modified.

type: string


=== adminState
$ref of: xref:v4.1@schemas:Tmf:AdministrativeState.adoc[]


=== jobPriority
description: The priority of the management job. The way the management application will use the JobPriority to schedule job execution is application specific and outside the scope. Integer, limited to a range of 1 to 10.

type: integer


=== executionState
$ref of: xref:v4.1@schemas:Tmf:ExecutionState.adoc[]


=== scheduleDefinition
type: array


[#all_of]
== All Of

