= MeasurementJob

[#domain]
== Domain

This schema is part of Common

[#description]
== Description

A PM measurement job is the administrative entity defined by a client application to perform a periodic activity related to PM data.  The PM activities may be production of measurements, collection of measurements or PM objective monitoring (scheduled evaluation of thresholds).


[#data_model]
== Data model

A JSON Schema corresponding to this data model can be found https://tmforum.org[here].

The data model is defined as shown below:


=== consumingApplicationId
description: The identifier of the application that consumes performance indicators.

type: string


=== producingApplicationId
description: The identifier of the application that produces performance indicators.

type: string


=== granularity
$ref of: xref:v4.2@schemas:Tmf:.adoc[]


=== performanceIndicatorGroupSpecification
type: array


=== performanceIndicatorSpecification
type: array


=== trackingRecord
type: array


=== monitoredInstancesCriteria
$ref of: xref:v4.2@schemas:Tmf:.adoc[]


=== monitoredClassCriteria
$ref of: xref:v4.2@schemas:Tmf:.adoc[]


= All Of 
This schema extends: xref:v4.2@schemas:Tmf:ManagementJob.adoc[]
