= MeasureThresholdRuleViolation

[#domain]
== Domain

This schema is part of Service

[#description]
== Description
A measureThresholdRuleViolation is a violation of a rule that defines the in the 
MericDefMeasureThresholdRule.


[#data_model]
== Data model

A JSON Schema corresponding to this data model can be found //[here].

THE DIAGRAM WILL BE IN HERE !!!
aaa

The data model is defined as shown below:


=== conformanceComparatorLower
description: An operator that when applied on a value specifies whether a 
threshold is crossed or ceased to be crossed. This operator is used to compare with the conformanceTargetLower if used.

type: string


=== conformanceComparatorExact
description: An operator that when applied on a value specifies whether it 
is the same target value or not. This operator is used to compare with the conformanceTargetExact if used.

type: boolean


=== conformanceComparatorUpper
description: An operator that when applied on a value specifies whether a 
threshold is crossed or ceased to be crossed. This operator is used to compare with the conformanceTargetUpper if used.

type: string


=== conformanceTargetLower
description: A value used to determine if the threshold is crossed or ceases 
to be crossed. It represents the lower limit. The value should be less than the conformanceTargetUpper if used. The conformance comparators should also be logically defined so as to not lead to a logically impossible condition.

type: string


=== conformanceTargetUpper
description: A value used to determine if the threshold is crossed or ceases 
to be crossed. It represents the Upper limit. The value should be greater than the conformanceTargetLower if used. The conformance comparators should also be logically defined so as to not lead to a logically impossible condition.

type: string


=== description
description: Description for the MetricDefMeasureThresholdRule .

type: string


=== name
description: Name for the MetricDefMeasureThresholdRule .

type: string


=== numberOfAllowedCrossing
description: The number of allowed crossing occurrences in reference to the 
tolerancePeriod without a consequence being initiated.

type: integer


=== thresholdRuleSeverity
description: A threshold can be generated in different severity levels. A 
crossing for each level may require a different condition and possibly trigger a different consequence.

type: string


=== conformanceTargetExact
description: To cater for values that are not numerical test metrics (e.g. a DSL line can be Synchronised or Unsynchronised. If the latter, the test should result in a rule violation).The allowed value can contain a REGEX expression.

type: string


=== tolerancePeriod
description: An interval of time of allowed crossing occurrences before a 
consequence being initiated.

$ref of: xref:v4.2@schemas:Tmf:Duration.adoc[]


=== appliedConsequence
description: An Applied Consequence defines the action (prescribed action or notification) to take when a MeasureThresholdRuleViolation occurs.

type: array


[#all_of]
== All Of

This schema extends: xref:v4.2@schemas:Tmf:Extensible.adoc[]
