= MetricDefMeasureConsequence

[#domain]
== Domain

This schema is part of Service

[#description]
== Description

A MetricDefMeasureConsequence defines the action (prescribed action or notification) to take when a 
MetricDefMeasureThresholdRule is crossed.


[#data_model]
== Data model

A JSON Schema corresponding to this data model can be found https://tmforum.org[here].

The data model is defined as shown below:


=== description
description: A narrative that explains in detail what the consequence is.

type: string


=== name
description: A word, term, or phrase by which a 
MetricDefMeasureConsequence is known and distinguished from other MetricDefMeasureConsequences.

type: string


=== prescribeAction
description: Recommended remedy for a violated threshold. This could be 
the hyperlink to the action.

type: string


=== repeatAction
description: An indicator used to specify that a consequence should cease 
being applied if a value is in the same range as the previous value or continue being applied if a value is in the same range as the previous value. 
If the repeatAction is True, if the consequence is always applied as soon as the MetricMeasure value is in the range of values and if the repeatAction is False, the consequence is applied only if the previous MetricMeasure value was not in the same range.

type: boolean


=== validFor
description: A valid duration of a thing.

$ref of: xref:4.0.0@schemas:Tmf:TimePeriod.adoc[]

