= Monitor

[#domain]
== Domain

This schema is part of Common

[#description]
== Description
Monitoring of resources


[#data_model]
== Data model

A JSON Schema corresponding to this data model can be found //[here].

THE DIAGRAM WILL BE IN HERE !!!
aaa

The data model is defined as shown below:


=== href
description: reference to this monitor

type: string


=== id
description: Identifier of an instance of the monitor. Required to be unique within the resource type.  Used in URIs as the identifier for specific instances of a type

type: string


=== request
description: Represents the request

$ref of: xref:v4.0@schemas:Tmf:Request.adoc[]


=== response
description: Represents the response

$ref of: xref:v4.0@schemas:Tmf:Response.adoc[]


=== sourceHref
description: The monitored resource href

type: string


=== state
description: The Monitor state of the resource.  InProgress, InError, Completed

type: string


[#all_of]
== All Of

This schema extends: xref:v4.0@schemas:Tmf:Entity.adoc[]
