= OrderLineItemAnalytics

[#domain]
== Domain

This schema is part of Analytics

[#description]
== Description
No description on schema


[#data_model]
== Data model

A JSON Schema corresponding to this data model can be found //[here].

Diagram:
aaa

The data model is defined as shown below:


=== orderTime
description: time the order was placed

type: string


=== totalQuantity
description: A line item might include several items of the same type, e.g. 5 iPhone X

type: number


=== statusSubmittedQuantity
description: The number of items in this line item in submitted status

type: number


=== statusProvisionedQuantity
description: The number of items in this line item in provisioned status

type: number


=== statusActivatedQuantity
description: The number of items in this line item in activated status

type: number


=== statusDeliveredQuantity
description: The number of items in this line item in delivered status

type: number


=== statusReturnedQuantity
description: The number of items in this line item in returned status

type: number


=== statusCanceledQuantity
description: The number of items in this line item in cancelled status

type: number


=== statusFailureQuantity
description: The number of items in this line item in failure status

type: number


=== statusUpdateTime
description: when the status was last updated

type: string


=== priceChargeTotalAmt
description: Offering Recurrent amount

type: number


=== priceChargeTotalOcAmt
description: Offering One time amount

type: number


=== dataCreationTimestamp
description: Time stamp for data creation (e.g. system dump creation, event generation…)

type: string


=== runTimestamp
description: Time stamp for data upload run

type: string


=== validFromTimestamp
description: Time stamp for business validity of entity record

type: string


[#all_of]
== All Of

This schema extends: xref:v4.1@schemas:Tmf:Entity.adoc[]
