= OrderPrice

[#domain]
== Domain

This schema is part of Customer

[#description]
== Description

An amount, usually of money, that represents the actual price paid by the Customer for this item or this order

None

[#data_model]
== Data model

A JSON Schema corresponding to this data model can be found https://tmforum.org[here].

The data model is defined as shown below:


=== description
description: A narrative that explains in detail the semantics of this order item price.

type: string


=== name
description: A short descriptive name such as &quot;Subscription price&quot;.

type: string


=== productOfferingPrice
description: An amount, usually of money, that is asked for or allowed when a ProductOffering is bought, rented, or leased. The price is valid for a defined period of time.

$ref of: xref:v5.0@schemas:Tmf:ProductOfferingPriceRef.adoc[]


=== recurringChargePeriod
description: Could be month, week...

type: string


=== unitOfMeasure
description: Could be minutes, GB...

type: string


=== billingAccount
description: A reference to a billing account used for paid the order price charge

$ref of: xref:v5.0@schemas:Tmf:BillingAccountRef.adoc[]


=== priceAlteration
description: a strucuture used to describe a price alteration

type: array


[#all_of]
== All Of

This schema extends: xref:v5.0@schemas:Gc:GcOrderPrice.adoc[]
This schema extends: xref:v5.0@schemas:Core:SchemaContext.adoc[]
