= OrderItemPrice

[#domain]
== Domain

This schema is part of Customer

[#description]
== Description
An amount, usually of money, that represents the actual price paid by the Customer for this item or this order


[#data_model]
== Data model

A JSON Schema corresponding to this data model can be found //[here].

THE DIAGRAM WILL BE IN HERE !!!
aaa

The data model is defined as shown below:


=== description
description: A narrative that explains in detail the semantics of this order item price.

type: string


=== name
description: Name of the order item price

type: string


=== productOfferingPrice
$ref of: xref:v4.1@schemas:Tmf:ProductOfferingPriceRef.adoc[]


=== priceType
description: A category that describes the price, such as recurring, discount, allowance, penalty, and so forth

type: string


=== recurringChargePeriod
description: Could be month, week...

type: string


=== unitOfMeasure
description: Could be minutes, GB...

type: string


=== billingAccount
$ref of: xref:v4.1@schemas:Tmf:BillingAccountRef.adoc[]


=== price
$ref of: xref:v4.1@schemas:Tmf:Price.adoc[]


=== priceAlteration
type: array


[#all_of]
== All Of

This schema extends: xref:v4.1@schemas:Tmf:Entity.adoc[]
