= Organization

[#domain]
== Domain

This schema is part of EngagedParty

[#description]
== Description

Organization represents a group of people identified by shared interests or purpose. Examples include business, department and enterprise. Because of the complex nature of many businesses, both organizations and organization units are represented by the same data.


[#data_model]
== Data model

A JSON Schema corresponding to this data model can be found https://tmforum.org[here].

The data model is defined as shown below:


=== isLegalEntity
description: If value is true, the organization is a legal entity known by a national referential.

type: boolean


=== isHeadOffice
description: If value is true, the organization is the head office

type: boolean


=== organizationType
description: Type of Organization (company, department...)

type: string


=== existsDuring
$ref of: xref:4.0.0@schemas:Tmf:TimePeriod.adoc[]


=== name
description: Organization name (department name for example)

type: string


=== nameType
description: Type of the name : Co, Inc, Ltd,…

type: string


=== status
description: Status of the organization

$ref of: xref:4.0.0@schemas:Tmf:OrganizationStateType.adoc[]


=== otherName
type: array


=== organizationIdentification
type: array


=== organizationChildRelationship
type: array


=== organizationParentRelationship
$ref of: xref:4.0.0@schemas:Tmf:OrganizationParentRelationship.adoc[]


{&#x27;$ref&#x27;: &#x27;../../Gc/EngagedParty/GcParty.schema.json#GcParty&#x27;}{&#x27;$ref&#x27;: &#x27;../../Gc/Common/GcEntity.schema.json#GcEntity&#x27;}