= Organization

[#domain]
== Domain

This schema is part of EngagedParty

[#description]
== Description
Organization represents a group of people identified by shared interests or purpose. Examples include business, department and enterprise. Because of the complex nature of many businesses, both organizations and organization units are represented by the same data.


[#data_model]
== Data model

A JSON Schema corresponding to this data model can be found //[here].

THE DIAGRAM WILL BE IN HERE !!!


The data model is defined as shown below:


=== isLegalEntity
description: If value is true, the organization is a legal entity known by a national referential.

type: boolean


=== isHeadOffice
description: If value is true, the organization is the head office

type: boolean


=== organizationType
description: Type of Organization (company, department...)

type: string


=== tradingName
description: Name that the organization (unit) trades under

type: string


=== existsDuring
$ref of: xref:v4.2@schemas:Tmf:TimePeriod.adoc[]


=== name
description: Organization name (department name for example)

type: string


=== nameType
description: Type of the name : Co, Inc, Ltd,…

type: string


=== status
description: Status of the organization

$ref of: xref:v4.2@schemas:Tmf:OrganizationStateType.adoc[]


=== otherName
type: array


=== organizationIdentification
type: array


=== organizationChildRelationship
type: array


=== organizationParentRelationship
$ref of: xref:v4.2@schemas:Tmf:OrganizationParentRelationship.adoc[]


[#all_of]
== All Of

This schema extends: xref:v4.2@schemas:Tmf:Party.adoc[]
This schema extends: xref:v4.2@schemas:Tmf:Entity.adoc[]
