= OtherName

[#domain]
== Domain

This schema is part of EngagedParty

[#description]
== Description
To keep track of other names (for example the old name of a woman before marriage or an artist name)


[#data_model]
== Data model

A JSON Schema corresponding to this data model can be found //[here].



The data model is defined as shown below:


=== familyName
description: Last name

type: string


=== formattedName
description: A formatted name useful for specific contexts (chinese, japanese, korean...)

type: string


=== fullName
description: Full name flatten (first, middle, and last name)

type: string


=== givenName
description: First name

type: string


=== middleName
description: Middle name

type: string


=== nameType
description: Co., Inc., Ltd., Plc., Gmbh.

type: string


=== title
description: useful for titles (aristocratic, social...) Dr, Pr, Sir...

type: string


=== tradingName
description: The name that the organization trades under

type: string


=== validFor
description: The period for which the other name is valid

$ref of: xref:v4.2@schemas:Tmf:TimePeriod.adoc[]


[#all_of]
== All Of

This schema extends: xref:v4.2@schemas:Tmf:Entity.adoc[]
