= PartyInteraction

[#domain]
== Domain

This schema is part of EngagedParty

[#description]
== Description
No description on schema


[#data_model]
== Data model

A JSON Schema corresponding to this data model can be found //[here].

Diagram:


The data model is defined as shown below:


=== id
description: Unique identifier of the party interaction

type: string


=== href
description: Hyperlink to access the party interaction

type: string


=== interactionDate
description: The period during which the interaction took place. Start and end will be different in case of a call or a store visit. They will be the same (or only one will appear) in case of a message or other momentary interactions.

$ref of: xref:v4.2@schemas:Tmf:TimePeriod.adoc[]


=== description
description: Description of the interaction

type: string


=== reason
description: Reason why the interaction happened

type: string


=== status
description: Status of the interaction (opened, inProgress, completed)

type: string


=== statusChangeDate
description: Last time the status changed

type: string


=== direction
description: Specifies who started the interaction. It might be the party or the enterprise exposing this API. Possible values are “inbound” and “outbound”

type: string


=== creationDate
description: Date when the interaction is created in the system

type: string


=== channel
description: Where the interaction took place (e.g. web, mobile app, store, kiosk, etc.)

type: array


=== relatedParty
type: array


=== attachment
type: array


=== note
type: array


=== interactionItem
type: array


=== interactionRelationship
type: array


[#all_of]
== All Of

This schema extends: xref:v4.2@schemas:Tmf:Entity.adoc[]
