= PartyRole

[#domain]
== Domain

This schema is part of EngagedParty

[#description]
== Description
The part played by a party in a given context.


[#data_model]
== Data model

A JSON Schema corresponding to this data model can be found //[here].

THE DIAGRAM WILL BE IN HERE !!!
aaa

The data model is defined as shown below:


=== href
description: Url used to reference the party role.

type: string


=== id
description: Unique identifier for PartyRoles

type: string


=== name
description: A word, term, or phrase by which the PartyRole is known and distinguished from other PartyRoles.

type: string


=== status
description: Used to track the lifecycle status of the party role.

type: string


=== statusReason
description: A string providing an explanation on the value of the status lifecycle. For instance if the status is Rejected, statusReason will provide the reason for rejection.

type: string


=== validFor
description: The time period that the PartyRole is valid for.

$ref of: xref:v4.2@schemas:Tmf:TimePeriod.adoc[]


=== engagedParty
$ref of: xref:v4.2@schemas:Tmf:PartyRef.adoc[]


=== roleType
$ref of: xref:v4.2@schemas:Tmf:RoleTypeRef.adoc[]


=== account
type: array


=== paymentMethod
type: array


=== contactMedium
type: array


=== characteristic
description: Describes the characteristic of a party role.

type: array


=== creditProfile
type: array


=== agreement
type: array


=== relatedParty
type: array


[#all_of]
== All Of

This schema extends: xref:v4.2@schemas:Tmf:Entity.adoc[]
