= PartyPrivacyProfile

[#domain]
== Domain

This schema is part of EngagedParty

[#description]
== Description
A Party Privacy Profile represents the set of Privacy settings defined for a Party


[#data_model]
== Data model

A JSON Schema corresponding to this data model can be found //[here].

THE DIAGRAM WILL BE IN HERE !!!
aaa

The data model is defined as shown below:


=== applicableForParty
description: The party to whom the privacy profile applies. Could be a minor where the agreeing party is a parent, an organization where the agreeing party is authorized to make such agreements, or some individual for whom the agreeing party has authorization (e.g. power of attorney). If empty, the agreeing party is the party to whom the profile applies.

$ref of: xref:v4.2@schemas:Tmf:RelatedParty.adoc[]


=== agreedByParty
description: The party who agreed to the privacy profile. Not necessarily the party to whom the profile applies.

$ref of: xref:v4.2@schemas:Tmf:RelatedParty.adoc[]


=== agreement
description: An agreement under which the privacy profile was produced.

$ref of: xref:v4.2@schemas:Tmf:PartyPrivacyAgreementRef.adoc[]


=== creationDate
description: The date on which the PartyPrivacyProfile was created

type: string


=== description
description: Description of the privacy profile

type: string


=== href
description: URI reference of the privacy profile allowing navigation to the resource

type: string


=== id
description: Unique identifier of the privacy profile

type: string


=== name
description: Name of the privacy profile

type: string


=== partyPrivacyProfileCharacteristic
description: List of characteristics of the privacy profile

type: array


=== partyPrivacyProfileSpecification
description: The specification from which this profile was instantiated

$ref of: xref:v4.2@schemas:Tmf:PartyPrivacyProfileSpecificationRef.adoc[]


=== status
description: The status of this profile (for example: created, terminated, etc.)

type: string


=== validFor
description: The period of time for which this profile is valid, depending on regulations or business consideration the profile may expire and need to be renegotiated.

$ref of: xref:v4.2@schemas:Tmf:TimePeriod.adoc[]


[#all_of]
== All Of

This schema extends: xref:v4.2@schemas:Tmf:Entity.adoc[]
