= PartyPrivacyProfileSpecificationCharacteristic

[#domain]
== Domain

This schema is part of EngagedParty

[#description]
== Description

A characteristic of the party privacy profile, whose value(s) would be supplied at runtime. For example, email address


[#data_model]
== Data model

A JSON Schema corresponding to this data model can be found https://tmforum.org[here].

The data model is defined as shown below:


=== id
type: string


=== name
description: Name of the characteristic

type: string


=== description
description: Description of the characteristic

type: string


=== criticalityLevel
description: Level of criticality for this characteristic of personal identifiable information (e.g. in terms of the damage if this item was breached), such as low, medium, high.

type: string


=== privacyUsagePurpose
description: Defines the purpose authorized or refused for the characteristic (e.g. ADMIN, INFORMATION, MARKETING, RESEARCH).

type: string


=== privacyType
description: Type of privacy (e.g. Internal Purpose, External Purpose, Internal Retention, External Retention)

type: string


=== allowedRole
description: A list of roles in the organization who are allowed access to this characteristic

type: array


=== partyPrivacyProfileSpecCharacteristicValue
description: List of values that can be assigned to this characteristic at runtime

type: array


=== validFor
description: The period of time for which this characteristic specification is valid.

$ref of: xref:v4.0@schemas:Tmf:TimePeriod.adoc[]


= All Of 
