= PartnershipSpecification

[#domain]
== Domain

This schema is part of EngagedParty

[#description]
== Description
A partnership specification contains all the information for the setup of a partnership of a given kind. This includes the list of identified role types for the partnership with the corresponding agreement specifications.


[#data_model]
== Data model

A JSON Schema corresponding to this data model can be found //[here].

== Diagram:
aaa

The data model is defined as shown below:


=== description
description: An explanatory text regarding this partnership specification

type: string


=== href
description: The reference url for this partnership specification

type: string


=== id
description: The identifier of the partnership specification

type: string


=== name
description: An identifying name for the partnership specification.

type: string


=== roleSpecification
description: The list of roles specifications a engaged party will be able to play for this kind of partnership

type: array


[#all_of]
== All Of

This schema extends: xref:v4.0@schemas:Tmf:Entity.adoc[]
