= PartyPrivacyProfileSpecification

[#domain]
== Domain

This schema is part of EngagedParty

[#description]
== Description

Party Privacy Profile Specification serves as a template for creating Privacy Profiles. The specification defines characteristics for the profile. For example there might be a profile specification for residential customers, and a different specification for partners.


[#data_model]
== Data model

A JSON Schema corresponding to this data model can be found https://tmforum.org[here].

The data model is defined as shown below:


=== description
description: Description of the specification

type: string


=== applicableRole
description: A list of roles to which this specification can apply. For example: Shop Agent, Call Center Agent.

type: array


=== lastUpdate
description: Date and time when the specification was last updated

type: string


=== status
description: Lifecycle status of the specification (for example: In Design, Active, Rejected, Retired)

type: string


=== name
description: Name of the specification

type: string


=== productOffering
type: array


=== relatedParty
description: List of parties or party roles involved in the definition or management of the specification

type: array


=== validFor
description: The period of time for which the specification is valid

$ref of: xref:4.0.0@schemas:Tmf:TimePeriod.adoc[]


=== version
description: The version of the specification, in case it is desired to maintain multiple versions of profile specifications

type: string


