= Partner

[#domain]
== Domain

This schema is part of EngagedParty

[#description]
== Description

The part played by a party in a given context.

None

[#data_model]
== Data model

A JSON Schema corresponding to this data model can be found https://tmforum.org[here].

The data model is defined as shown below:


=== href
description: Url used to reference the partner.

type: string


=== id
description: Unique identifier for Partners

type: string


=== name
description: A word, term, or phrase by which the Partner is known and distinguished from other Partners.

type: string


=== status
description: Used to track the lifecycle status of the partner.

type: string


=== statusReason
description: A string providing an explanation on the value of the status lifecycle. For instance if the status is Rejected, statusReason will provide the reason for rejection.

type: string


=== validFor
description: The time period that the Partner is valid for.

$ref of: xref:v4.0@schemas:Tmf:TimePeriod.adoc[]


=== engagedParty
description: The reference to the party engaged in this partnership.

$ref of: xref:v4.0@schemas:Tmf:RelatedParty.adoc[]


=== account
type: array


=== paymentMethod
type: array


=== contactMedium
type: array


=== characteristic
description: Describes the characteristic of a partner.

type: array


=== creditProfile
type: array


=== agreement
type: array


=== relatedParty
type: array


[#all_of]
== All Of

This schema extends: xref:v4.0@schemas:Tmf:Entity.adoc[]
