= PartyPrivacyProfileSpecification

[#domain]
== Domain

This schema is part of EngagedParty

[#description]
== Description
Party Privacy Profile Specification serves as a template for creating Privacy Profiles. The specification defines characteristics for the profile. For example there might be a profile specification for residential customers, and a different specification for partners.


[#data_model]
== Data model

A JSON Schema corresponding to this data model can be found //[here].

Diagram:
aaa

The data model is defined as shown below:


=== description
description: Description of the specification

type: string


=== applicableRole
description: A list of roles to which this specification can apply. For example: Shop Agent, Call Center Agent.

type: array


=== href
description: URI reference of the specification allowing navigation to the resource

type: string


=== id
description: Unique identifier of the specification

type: string


=== lastUpdate
description: Date and time when the specification was last updated

type: string


=== status
description: Lifecycle status of the specification (for example: In Design, Active, Rejected, Retired)

type: string


=== name
description: Name of the specification

type: string


=== partyPrivacyProfileSpecCharacteristic
description: List of characteristics of the specification, whose values would typically be supplied when the profile is instantiated

type: array


=== productOffering
type: array


=== relatedParty
description: List of parties or party roles involved in the definition or management of the specification

type: array


=== validFor
description: The period of time for which the specification is valid

$ref of: xref:v4.0@schemas:Tmf:TimePeriod.adoc[]


=== version
description: The version of the specification, in case it is desired to maintain multiple versions of profile specifications

type: string


[#all_of]
== All Of

