= PartyRoleProductOfferingRiskAssessment

[#domain]
== Domain

This schema is part of Customer

[#description]
== Description
This is a task resource allowing assessment of the risks associated with a party or party role that considers acquiring a specific product offering


[#data_model]
== Data model

A JSON Schema corresponding to this data model can be found //[here].

THE DIAGRAM WILL BE IN HERE !!!
aaa

The data model is defined as shown below:


=== partyRole
description: The party or party role for which the assessment is to be carried out, must be supplied as input to the task, with the attribute id populated

$ref of: xref:v4.2@schemas:Tmf:RelatedParty.adoc[]


=== productOffering
description: The product offering for which the assessment is to be carried out, must be supplied as input to the task, with the attribute id populated

$ref of: xref:v4.2@schemas:Tmf:ProductOfferingRef.json.adoc[]


[#all_of]
== All Of

This schema extends: xref:v4.2@schemas:Tmf:RiskAssessment.adoc[]
