= PaymentPlan

[#domain]
== Domain

This schema is part of Customer

[#description]
== Description
Defines a plan for payment (when a party wants to spread his payments)


[#data_model]
== Data model

A JSON Schema corresponding to this data model can be found //[here].

Diagram:


The data model is defined as shown below:


=== numberOfPayments
description: Number of payments used to spread the global payment

type: integer


=== paymentFrequency
description: Frequency of the payments, such as monthly and bimonthly

type: string


=== priority
description: Priority of the payment plan

type: integer


=== status
description: Status of the payment plan (effective, ineffective)

type: string


=== totalAmount
description: Amount paid

$ref of: xref:v4.0@schemas:Tmf:Money.adoc[]


=== planType
description: Type of payment plan

type: string


=== validFor
description: Validity period of the payment plan

$ref of: xref:v4.0@schemas:Tmf:TimePeriod.adoc[]


=== paymentMethod
$ref of: xref:v4.0@schemas:Tmf:PaymentMethodRef.adoc[]


[#all_of]
== All Of

This schema extends: xref:v4.0@schemas:Tmf:Entity.adoc[]
