= PaymentMethod

[#domain]
== Domain

This schema is part of Customer

[#description]
== Description

A Payment Method is a pure-virtual super-class that defines a specific method of payment such as Direct Debit, Cash, Digital Wallet,Tokenized Card, Bank Account Transfer, Bank Account Debit, Bank Card, Voucher, Check, Bucket PaymentMethod, Account PaymentMethod, and Loyalty PaymentMethod with all details associated. Use the @type attribute to specify the concrete type in the API calls.

None

[#data_model]
== Data model

A JSON Schema corresponding to this data model can be found https://tmforum.org[here].

The data model is defined as shown below:


=== name
description: Friendly name assigned to the payment method

type: string


=== description
description: Text description of the contents of the payment method

type: string


=== isPreferred
description: If the method is the preferred one by the owner. Typically used when querying for the payment methods of a specific customer or account

type: boolean


=== authorizationCode
description: Review: Authorization code provided by a financial institution. Typically this would be populated for recurring payments using the method, as payments have an authorization code of their own.

type: string


=== status
description: Status of the payment method

type: string


=== statusDate
description: The last time the payment method status changed.

type: string


=== statusReason
description: The reason for the last status change.

type: string


=== validFor
description: Date interval in which the payment method is valid

$ref of: xref:v4.0@schemas:Tmf:TimePeriod.adoc[]


=== @type
description: Type of payment method (e.g.: bank card, cash, voucher, etc).

type: string


=== relatedParty
description: Reference to the customer or party that owns that payment method or can use it.

$ref of: xref:v4.0@schemas:Tmf:RelatedParty.adoc[]


=== relatedPlace
description: Reference to a place for billing or delivery address, if different to that of the related party.

$ref of: xref:v4.0@schemas:Tmf:RelatedPlace.adoc[]


=== account
description: Reference to the accounts that are linked to the payment method. May be a party account or a financial account.

type: array


[#all_of]
== All Of

This schema extends: xref:v4.0@schemas:Tmf:Entity.adoc[]
