= PerformanceIndicatorSpecification

[#domain]
== Domain

This schema is part of Common

[#description]
== Description

Holds the definition of the requested Performance indicator including: its name, value type, collection type, description and units.


[#data_model]
== Data model

A JSON Schema corresponding to this data model can be found https://tmforum.org[here].

The data model is defined as shown below:


=== id
description: A unique identifier for the PerformanceIndicatorSpecification.

type: string


=== name
description: A word, term, or phrase by which a PerformanceIndicatorSpecification is known and distinguished from other PerformanceIndicatorSpecifications.

type: string


=== description
description: A narrative that explains in detail what the PerformanceIndicatorSpecification is.

type: string


=== perspective
description: The point of view for the PerformanceIndicatorSpecification, such as a single user instance or aggregation.

type: string


=== indicatorCategory
description: A grouping or set of PerformanceIndicatorSpecifications that are classified together because of common characteristics, such as technology specific, service specific, or technology/service independent.

type: string


=== indicatorType
description: A kind of value that the PerformanceIndicator can take; double float,int, string.

$ref of: xref:4.0.0@schemas:Tmf:.adoc[]


=== derivationAlgorithm
description: A step-by-step procedure used to calculate the value of PerformanceIndicator.

type: string


=== derivationMethod
description: For simple calculations, the method used to calculate the value of a PerformanceIndicator, such as average, minimum, maximum, sum and so forth.

type: string


=== validFor
description: The period of time during which the PerformanceIndicatorSpecification is applicable.

$ref of: xref:4.0.0@schemas:Tmf:.adoc[]


=== collectionType
description: The type of collection: gauge, cumulative,delta,discrete event,status inspection. Indicators can be produced using these methods.

$ref of: xref:4.0.0@schemas:Tmf:.adoc[]


=== indicatorUnit
description: The unit by which the indicator is measured. For example, seconds, KBs, rate per second, etc.

type: string


=== performanceIndicatorSpecRelationship
type: array

