= Permission

[#domain]
== Domain

This schema is part of Common

[#description]
== Description
The Permission resource represents the entitlement given by an individual (granter) to another individual (user) to get access to a set of his owned manageable assets. One single permission resource can hold information referring to privileges granted for multiple manageable assets.


[#data_model]
== Data model

A JSON Schema corresponding to this data model can be found //[here].

THE DIAGRAM WILL BE IN HERE !!!
aaa

The data model is defined as shown below:


=== id
description: Unique identifier of the permission

type: string


=== href
description: Hypertext Reference of the permission

type: string


=== creationDate
description: Date when the payment was performed

type: string


=== description
description: Text describing the contents of the payment

type: string


=== validFor
description: The period for which the permission is valid

$ref of: xref:v4.1@schemas:Tmf:TimePeriod.adoc[]


=== user
$ref of: xref:v4.1@schemas:Tmf:RelatedParty.adoc[]


=== granter
$ref of: xref:v4.1@schemas:Tmf:RelatedParty.adoc[]


=== privilege
type: array


=== assetUserRole
type: array


[#all_of]
== All Of

This schema extends: xref:v4.1@schemas:Tmf:Entity.adoc[]
