= PhysicalResource

[#domain]
== Domain

This schema is part of Resource

[#description]
== Description

Physical resource is a type of resource that describes the common set of attributes shared by all concrete physical resources (e.g. EQUIPMENT) in the inventory.


[#data_model]
== Data model

A JSON Schema corresponding to this data model can be found https://tmforum.org[here].

The data model is defined as shown below:


=== manufactureDate
description: This is a string attribute that defines the date of manufacture of this item in the fixed format &quot;dd/mm/yyyy&quot;. This is an optional attribute.

type: string


=== powerState
description: This defines the current power status of the hardware item. Values include:

  0:  Unknown
  1:  Not Applicable
  2:  No Power Applied
  3: Full Power Applied
  4:  Power Save - Normal
  5:  Power Save - Degraded
  6:  Power Save - Standby
  7:  Power Save - Critical
  8:  Power Save - Low Power Mode
  9:  Power Save - Unknown
 10: Power Cycle
 11: Power Warning
 12: Power Off

type: string


=== serialNumber
description: This is a string that represents a manufacturer-allocated number used to identify different instances of the same hardware item. The ModelNumber and PartNumber attributes are used to identify different types of hardware items. This is a REQUIRED attribute.

type: string


=== versionNumber
description: This is a string that identifies the version of this physical resource. This is an optional attribute.

type: string


[#all_of]
== All Of

This schema extends: xref:v4.1@schemas:Tmf:Resource.adoc[]
