= PointOfInteraction

[#domain]
== Domain

This schema is part of Customer

[#description]
== Description
POI consists of hardware and software which enables a Cardholder and/or an Acceptor to perform a Local Card transaction. This is also referred to as a Physical/EMV Terminal. It may be Attended or Unattended.


[#data_model]
== Data model

A JSON Schema corresponding to this data model can be found //[here].

Diagram:
aaa

The data model is defined as shown below:


=== resource
description: A POI is a Physical POI or a Remote POI, as a resource.

$ref of: xref:v4.0@schemas:Tmf:ResourceRef.adoc[]


=== modeOfEntry
description: Key entry code that tells the processor how the transaction was captured.

type: string


=== retrievalReferenceNumber
description: The reference number used to identify a given transaction that allow the Acceptor or Acquirer to keep track of their transactions

type: string


=== transactionDate
description: Date time related to the POI transaction.

type: string


[#all_of]
== All Of

This schema extends: xref:v4.0@schemas:Tmf:Entity.adoc[]
