= PriceAlteration

[#domain]
== Domain

This schema is part of Product

[#description]
== Description

Is an amount, usually of money, that modifies the price charged for an order item.

None

[#data_model]
== Data model

A JSON Schema corresponding to this data model can be found https://tmforum.org[here].

The data model is defined as shown below:


=== applicationDuration
description: Duration during which the alteration applies on the order item price (for instance 2 months free of charge for the recurring charge)

type: integer


=== description
description: A narrative that explains in detail the semantics of this order item price alteration

type: string


=== name
description: Name of the order item price alteration

type: string


=== productOfferingPrice
$ref of: xref:v4.0@schemas:Tmf:ProductOfferingPriceRef.adoc[]


=== priceType
description: A category that describes the price such as recurring, one time and usage.

type: string


=== priority
description: Priority level for applying this alteration among all the defined alterations on the order item price

type: integer


=== recurringChargePeriod
description: Could be month, week...

type: string


=== unitOfMeasure
description: Could be minutes, GB...

type: string


=== price
$ref of: xref:v4.0@schemas:Tmf:Price.adoc[]


[#all_of]
== All Of

This schema extends: xref:v4.0@schemas:Tmf:Entity.adoc[]
