= ProblemUnacknowledgement

[#domain]
== Domain

This schema is part of Service

[#description]
== Description
Task resource that requests unacknowledgement of problems, rolling back the status of the problems from Acknowledged to Submitted.


[#data_model]
== Data model

A JSON Schema corresponding to this data model can be found //[here].

THE DIAGRAM WILL BE IN HERE !!!
aaa

The data model is defined as shown below:


=== href
description: Reference to this task resource

type: string


=== id
description: Unique identifier of this task resource

type: string


=== problem
description: The problems to be unacknowledged, relevant in the input to this task

type: array


=== unackProblem
description: The problems that were unacknowledged, populated in the output to this task

type: array


=== trackingRecord
description: A record of the action taken in this acknowledgement

$ref of: xref:v4.1@schemas:Tmf:TrackingRecord.adoc[]


[#all_of]
== All Of

This schema extends: xref:v4.1@schemas:Tmf:Entity.adoc[]
