= ProcessFlow

[#domain]
== Domain

This schema is part of Common

[#description]
== Description

No description on schema


[#data_model]
== Data model

A JSON Schema corresponding to this data model can be found https://tmforum.org[here].

The data model is defined as shown below:


=== channel
description: A list of channel(s) where this processFlow is executed

type: array


=== characteristic
description: A list of characteristic(s) associated to this processFlow

type: array


=== href
description: Reference of the ProcessFlow

type: string


=== id
description: Identifier of the Process flow

type: string


=== processFlowDate
description: Is the date when the processFlow was created in basse (timestamp)

type: string


=== processFlowSpecification
description: Specification of the processFlow.

type: string


=== relatedEntity
description: A list of related entity(ies) to this processFlow

type: array


=== relatedParty
description: A list of related party(ies) to this processFlow

type: array


=== state
description: State of the ProcessFlow: described in the state machine diagram.

$ref of: xref:v4.2@schemas:Tmf:ProcessFlowStateType.adoc[]


=== taskFlow
description: A list of taskflow related to this processFlow

type: array


[#all_of]
== All Of

This schema extends: xref:v4.2@schemas:Tmf:Entity.adoc[]
