= ProductOfferingQualificationItem

[#domain]
== Domain

This schema is part of Product

[#description]
== Description

No description on schema


[#data_model]
== Data model

A JSON Schema corresponding to this data model can be found https://tmforum.org[here].

The data model is defined as shown below:


=== expectedActivationDate
description: Date when the requester look for productOfferingQualification activation

type: string


=== id
description: Id of the productOfferingQualification item

type: string


=== action
description: Can be &quot;add&quot; / &quot;modify&quot; / &quot;no_change&quot;/ &quot;delete&quot; - by default add is considered

$ref of: xref:4.0.0@schemas:Tmf:ProductActionType.adoc[]


=== qualificationItemResult
description: Qualification result for this productOfferingQualification item. It could be:

 qualified (request productOffering or productSpecification are available), 
 unqualified (requested not available and not alternate available),
 alternate (requested not available but proposal available)


type: string


=== state
description: State of the productOfferingQualification item defined in the state engine

$ref of: xref:4.0.0@schemas:Tmf:TaskStateType.adoc[]


=== eligibilityUnavailabilityReason
type: array


=== qualificationItemRelationship
type: array


=== note
type: array


=== product
$ref of: xref:4.0.0@schemas:Tmf:ProductRefOrValue.adoc[]


=== terminationError
type: array


=== productOffering
$ref of: xref:4.0.0@schemas:Tmf:ProductOfferingRef.adoc[]


=== alternateProductOfferingProposal
type: array


{&#x27;$ref&#x27;: &#x27;../Common/Entity.schema.json#Entity&#x27;}