= ProductValue

[#domain]
== Domain

This schema is part of Product

[#description]
== Description
A product offering procured by a customer or other interested party playing a party role. A product is realized as one or more service(s) and / or resource(s).


[#data_model]
== Data model

A JSON Schema corresponding to this data model can be found //[here].

Diagram:
aaa

The data model is defined as shown below:


=== href
description: Hyperlink reference

type: string


=== id
description: unique identifier

type: string


=== agreementItem
type: array


=== billingAccount
$ref of: xref:v5.0@schemas:Tmf:BillingAccountRef.adoc[]


=== creationDate
description: Date and time when the product was created

type: string


=== description
description: Is the description of the product. It could be copied from the description of the Product Offering.

type: string


=== isBundle
description: If true, the product is a ProductBundle which is an instantiation of a BundledProductOffering. If false, the product is a ProductComponent which is an instantiation of a SimpleProductOffering.

type: boolean


=== isCustomerVisible
description: If true, the product is visible by the customer.

type: boolean


=== name
description: Name of the product. It could be the same as the name of the product offering

type: string


=== orderDate
description: Is the date when the product was ordered

type: string


=== productCharacteristic
type: array


=== productOffering
$ref of: xref:v5.0@schemas:Tmf:ProductOfferingRef.adoc[]


=== productOrderItem
type: array


=== product
type: array


=== productPrice
type: array


=== productRelationship
type: array


=== productSerialNumber
description: Is the serial number for the product. This is typically applicable to tangible products e.g. Broadband Router.

type: string


=== productSpecification
$ref of: xref:v5.0@schemas:Tmf:ProductSpecificationRef.adoc[]


=== productTerm
type: array


=== realizingResource
type: array


=== realizingService
type: array


=== relatedParty
type: array


=== place
type: array


=== startDate
description: Is the date from which the product starts

type: string


=== status
description: Is the lifecycle status of the product.

$ref of: xref:v5.0@schemas:Tmf:ProductStatusType.adoc[]


=== terminationDate
description: Is the date when the product was terminated

type: string


[#all_of]
== All Of

This schema extends: xref:v5.0@schemas:Gc:GcProductValue.adoc[]
This schema extends: xref:v5.0@schemas:Core:SchemaContext.adoc[]
