= ProductStock

[#domain]
== Domain

This schema is part of Resource

[#description]
== Description
ProductStock is a base class for defining a product (or configured product with values characteristic) stock level.


[#data_model]
== Data model

A JSON Schema corresponding to this data model can be found https://tmforum.org[here].

The data model is defined as shown below:


=== description
description: Free-text description of the ProductStock

type: string


=== creationDate
description: Date when the ProductStock was created (whatever its status).

type: string


=== lastUpdate
description: Last date when the ProductStock record was updated.

type: string


=== lastInventoryDate
description: Last inventory count date for this ProductStock.

type: string


=== replenishmentDate
description: Planned date for future replenishment for this ProductStock.

type: string


=== id
description: Unique identifier of the ProductStock

type: string


=== href
description: Reference of the ProductStock

type: string


=== stockLevelCategory
description: Category of the ProductStock

type: string


=== name
description: Name of the ProductStock

type: string


=== productStockStatusType
description: The status of the ProductStock, such as available, unavailable, reserved, unknown

$ref of: xref:4.0.0@schemas:Tmf:ProductStockStatusType.adoc[]


=== productStockUsageType
description: The usage type of the  ProductStock, such as inTransit, damaged, onDisplay, etc..

$ref of: xref:4.0.0@schemas:Tmf:ProductStockUsageType.adoc[]


=== productStockLevel
$ref of: xref:4.0.0@schemas:Tmf:Quantity.adoc[]


=== minStockLevel
$ref of: xref:4.0.0@schemas:Tmf:Quantity.adoc[]


=== maxStockLevel
$ref of: xref:4.0.0@schemas:Tmf:Quantity.adoc[]


=== stockLevelAlert
$ref of: xref:4.0.0@schemas:Tmf:Quantity.adoc[]


=== reorderQuantity
$ref of: xref:4.0.0@schemas:Tmf:Quantity.adoc[]


=== productStockRelationship
description: relationship to other product stock

type: array


=== stockedProduct
description: Product stocked in this product stock  - could be via a productSpecification, a ProductSpecification + valued characteristic, etc. 

$ref of: xref:4.0.0@schemas:Tmf:ProductRefOrValue.adoc[]


=== resource
description: The Resource managed through this ProductStock is used

type: array


=== channel
type: array


=== marketSegment
description: provides references to the corresponding market segment as target of a product stock. A market segment is grouping of Parties, GeographicAreas, SalesChannels, and so forth.

type: array


=== relatedParty
description: A list of related party references (RelatedParty [*]). A related party defines party or party role linked to a specific entity

type: array


=== place
description: Used to define a place useful for the ProductStock for example a geographical place where the Product Stock is located

$ref of: xref:4.0.0@schemas:Tmf:RelatedPlaceRefOrValue.adoc[]

