= ProductSpecificationCharacteristic

[#domain]
== Domain

This schema is part of Product

[#description]
== Description
A characteristic quality or distinctive feature of a ProductSpecification.  The characteristic can be take on a discrete value, such as color, can take on a range of values, (for example, sensitivity of 100-240 mV), or can be derived from a formula (for example, usage time (hrs) = 30 - talk time *3). Certain characteristics, such as color, may be configured during the ordering or some other process.


[#data_model]
== Data model

A JSON Schema corresponding to this data model can be found //[here].

THE DIAGRAM WILL BE IN HERE !!!
aaa

The data model is defined as shown below:


=== productSpecCharacteristicValue
description: A ProductSpecificationCharacteristicValue object is used to define a set of attributes, each of which can be assigned to a corresponding set of attributes in a ProductSpecificationCharacteristic object. The values of the attributes in the ProductSpecificationCharacteristicValue object describe the values of the attributes that a corresponding ProductSpecificationCharacteristic object can take on.

type: array


=== productSpecCharRelationship
description: An aggregation, migration, substitution, dependency or exclusivity relationship between/among Specification Characteristics.

type: array


[#all_of]
== All Of

This schema extends: xref:v4.2@schemas:Tmf:CharacteristicSpecificationBase.adoc[]
