= ProductOfferingPrice

[#domain]
== Domain

This schema is part of Product

[#description]
== Description
Is based on both the basic cost to develop and produce products and the enterprises policy on revenue targets. This price may be further revised through discounting (a Product Offering Price that reflects an alteration). The price, applied for a productOffering may also be influenced by the productOfferingTerm, the customer selected, eg: a productOffering can be offered with multiple terms, like commitment periods for the contract. The price may be influenced by this productOfferingTerm. A productOffering may be cheaper with a 24 month commitment than with a 12 month commitment.


[#data_model]
== Data model

A JSON Schema corresponding to this data model can be found //[here].

== Diagram:
aaa

The data model is defined as shown below:


=== id
description: unique id of this resource

type: string


=== href
description: Reference of the ProductOfferingPrice

type: string


=== name
description: Name of the productOfferingPrice

type: string


=== description
description: Description of the productOfferingPrice

type: string


=== version
description: ProductOffering version

type: string


=== validFor
description: The period for which the productOfferingPrice is valid

$ref of: xref:v4.1@schemas:Tmf:TimePeriod.adoc[]


=== priceType
description: A category that describes the price, such as recurring, discount, allowance, penalty, and so forth.

type: string


=== unitOfMeasure
description: A number and unit representing how many (for instance 1 dozen) of an ProductOffering is available at the offered price. Its meaning depends on the priceType. It could be a price, a rate, or a discount.

$ref of: xref:v4.1@schemas:Tmf:Quantity.adoc[]


=== recurringChargePeriodType
description: The period to repeat the application of the price
Could be month, week...

type: string


=== recurringChargePeriodLength
description: the period of the recurring charge:  1, 2, ... .It sets to zero if it is not applicable

type: integer


=== @type
description: The class type of this Product offering

type: string


=== @baseType
description: the immediate base class type of this product offering

type: string


=== @schemaLocation
description: hyperlink reference to the schema describing this resource

type: string


=== lastUpdate
description: the last update time of this ProductOfferingPrice

type: string


=== isBundle
description: A flag indicating if this ProductOfferingPrice is composite (bundle) or not

type: boolean


=== lifecycleStatus
description: the lifecycle status of this ProductOfferingPrice

type: string


=== price
description: The amount of money that characterizes the price.

$ref of: xref:v4.1@schemas:Tmf:Money.adoc[]


=== percentage
description: Percentage to apply if this Product Offering Price is an Alteration (such as a Discount)

type: number


=== bundledPopRelationship
description: this object represents a bundle relationship from a bundle product offering price (parent) to a simple product offering price (child). A simple product offering price may participate in more than one bundle relationship.

type: array


=== popRelationship
description: Product Offering Prices related to this Product Offering Price, for example a price alteration such as allowance or discount

type: array


=== prodSpecCharValueUse
description: A use of the ProductSpecificationCharacteristicValue by a ProductOfferingPrice to which additional properties (attributes) apply or override the properties of similar properties contained in ProductSpecificationCharacteristicValue. It should be noted that characteristics which their value(s) addressed by this object must exist in corresponding product specification. The available characteristic values for a ProductSpecificationCharacteristic in a Product specification can be modified at the ProductOffering and ProcuctOfferingPrice level. The list of values in ProductSpecificationCharacteristicValueUse is a strict subset of the list of values as defined in the corresponding product specification characteristics.

type: array


=== productOfferingTerm
description: A list of conditions under which a ProductOfferingPrice is made available to Customers. For instance, a Product Offering Price can be offered with multiple commitment periods.

type: array


=== place
description: Place defines the places where the products are sold or delivered.

type: array


=== constraint
description: The Constraint resource represents a policy/rule applied to ProductOfferingPrice.

type: array


=== pricingLogicAlgorithm
description: The PricingLogicAlgorithm entity represents an instantiation of an interface specification to external rating function (without a modeled behavior in SID). Some of the parameters of the interface definition may be already set (such as price per unit) and some may be gathered during the rating process from the event (such as call duration) or from ProductCharacteristicValues (such as assigned bandwidth).

type: array


=== tax
description: An amount of money levied on the price of a Product by a legislative body.

type: array


[#all_of]
== All Of

This schema extends: xref:v4.1@schemas:Tmf:Addressable.adoc[]
This schema extends: xref:v4.1@schemas:Tmf:Extensible.adoc[]
