= ProductOfferingPriceAlteration

[#domain]
== Domain

This schema is part of Product

[#description]
== Description

A discount is a reduction in price. It could be a flat fee such as 10 dollars or a percentage, such as 50% off. A discount always applies to, and thus is associated with, one or more other ProdOfferPrices. So a discount would be 10 dollars off the installation fee or 50% off the per-minute rate.


[#data_model]
== Data model

A JSON Schema corresponding to this data model can be found https://tmforum.org[here].

The data model is defined as shown below:


=== applicationDuration
description: The period for which the productOfferingPriceAlteration is applicable

$ref of: xref:v4.2@schemas:Tmf:Duration.adoc[]


=== percentage
description: Percentage to apply (such as a Discount)

type: number


=== priority
description: Priority level for applying this alteration among all the defined alterations on the order item price

type: integer


[#all_of]
== All Of

This schema extends: xref:v4.2@schemas:Tmf:ProductOfferingPrice.adoc[]
