= ProductSpecification

[#domain]
== Domain

This schema is part of Product

[#description]
== Description
Is a detailed description of a tangible or intangible object made available externally in the form of a ProductOffering to customers or other parties playing a party role.


[#data_model]
== Data model

A JSON Schema corresponding to this data model can be found //[here].

THE DIAGRAM WILL BE IN HERE !!!
aaa

The data model is defined as shown below:


=== brand
description: The manufacturer or trademark of the specification

type: string


=== description
description: A narrative that explains in detail what the product specification is

type: string


=== href
description: Reference of the product specification

type: string


=== id
description: Unique identifier of the product specification

type: string


=== isBundle
description: isBundle determines whether a productSpecification represents a single productSpecification (false), or a bundle of productSpecification (true).

type: boolean


=== lastUpdate
description: Date and time of the last update

type: string


=== lifecycleStatus
description: Used to indicate the current lifecycle status

type: string


=== name
description: Name of the product specification

type: string


=== productNumber
description: An identification number assigned to uniquely identity the specification

type: string


=== validFor
description: The period for which the product specification is valid

$ref of: xref:v4.0@schemas:Tmf:TimePeriod.adoc[]


=== version
description: Product specification version

type: string


=== relatedParty
description: A related party defines party or party role linked to a specific entity.

type: array


=== productSpecCharacteristic
description: A characteristic quality or distinctive feature of a ProductSpecification.  The characteristic can be take on a discrete value, such as color, can take on a range of values, (for example, sensitivity of 100-240 mV), or can be derived from a formula (for example, usage time (hrs) = 30 - talk time *3). Certain characteristics, such as color, may be configured during the ordering or some other process.

type: array


=== serviceSpecification
description: ServiceSpecification(s) required to realize a ProductSpecification.

type: array


=== productSpecificationRelationship
description: A migration, substitution, dependency or exclusivity relationship between/among product specifications.

type: array


=== resourceSpecification
description: The ResourceSpecification is required to realize a ProductSpecification.

type: array


=== attachment
description: Complements the description of an element (for instance a product) through video, pictures...

type: array


=== bundledProductSpecification
description: A type of ProductSpecification that belongs to a grouping of ProductSpecifications made available to the market. It inherits of all attributes of ProductSpecification.

type: array


=== targetProductSchema
description: A target product schema reference. The reference object to the schema and type of target product which is described by product specification.

$ref of: xref:v4.0@schemas:Tmf:TargetProductSchema.adoc[]


[#all_of]
== All Of

This schema extends: xref:v4.0@schemas:Tmf:Addressable.adoc[]
This schema extends: xref:v4.0@schemas:Tmf:Extensible.adoc[]
