= ProductRequest

[#domain]
== Domain

This schema is part of Product

[#description]
== Description
No description on schema


[#data_model]
== Data model

A JSON Schema corresponding to this data model can be found //[here].

Diagram:
aaa

The data model is defined as shown below:


=== referredProduct
$ref of: xref:v4.2@schemas:Tmf:ProductRef.adoc[]


=== description
description: Is the description of the product. It could be copied from the description of the Product Offering.

type: string


=== href
description: Reference of the product

type: string


=== id
description: Unique identifier of the product

type: string


=== isBundle
description: If true, the product is a ProductBundle which is an instantiation of a BundledProductOffering. If false, the product is a ProductComponent which is an instantiation of a SimpleProductOffering.

type: boolean


=== isCustomerVisible
description: If true, the product is visible by the customer.

type: boolean


=== name
description: Name of the product. It could be the same as the name of the product offering

type: string


=== orderDate
description: Is the date when the product was ordered

type: string


=== productSerialNumber
description: Is the serial number for the product. This is typically applicable to tangible products e.g. Broadband Router.

type: string


=== startDate
description: Is the date from which the product starts

type: string


=== status
description: Is the lifecycle status of the product.

type: string


=== terminationDate
description: Is the date when the product was terminated

type: string


=== realizingService
type: array


=== billingAccount
type: array


=== productOffering
$ref of: xref:v4.2@schemas:Tmf:ProductOfferingRef.adoc[]


=== agreement
type: array


=== characteristic
type: array


=== productRelationship
type: array


=== realizingResource
type: array


=== relatedParty
type: array


=== productPrice
type: array


=== productSpecification
$ref of: xref:v4.2@schemas:Tmf:ProductSpecificationRef.adoc[]


=== place
type: array


[#all_of]
== All Of

This schema extends: xref:v4.2@schemas:Tmf:Entity.adoc[]
