= ProductOrderItem

[#domain]
== Domain

This schema is part of Customer

[#description]
== Description
An identified part of the order. A product order is decomposed into one or more order items.


[#data_model]
== Data model

A JSON Schema corresponding to this data model can be found //[here].

THE DIAGRAM WILL BE IN HERE !!!
aaa

The data model is defined as shown below:


=== id
description: Identifier of the line item (generally it is a sequence number 01, 02, 03, ...)

type: string


=== quantity
description: Quantity ordered

type: integer


=== action
description: The action to be carried out on the Product. Can be: add, modify, delete, noChange

$ref of: xref:v4.1@schemas:Tmf:OrderItemActionType.adoc[]


=== appointment
$ref of: xref:v4.1@schemas:Tmf:AppointmentRef.adoc[]


=== billingAccount
$ref of: xref:v4.1@schemas:Tmf:BillingAccountRef.adoc[]


=== itemPrice
type: array


=== itemTerm
type: array


=== itemTotalPrice
type: array


=== payment
type: array


=== product
$ref of: xref:v4.1@schemas:Tmf:ProductRefOrValue.adoc[]


=== productOffering
$ref of: xref:v4.1@schemas:Tmf:ProductOfferingRef.adoc[]


=== productOfferingQualificationItem
$ref of: xref:v4.1@schemas:Tmf:ProductOfferingQualificationItemRef.adoc[]


=== quoteItem
$ref of: xref:v4.1@schemas:Tmf:QuoteItemRef.adoc[]


=== productOrderItem
type: array


=== productOrderItemRelationship
type: array


=== qualification
type: array


=== state
description: State of the order item : described in the state machine diagram

$ref of: xref:v4.1@schemas:Tmf:ProductOrderItemStateType.adoc[]


[#all_of]
== All Of

This schema extends: xref:v4.1@schemas:Tmf:Entity.adoc[]
