= PromotionAction

[#domain]
== Domain

This schema is part of Product

[#description]
== Description
Action of the promotion.When the customer meets the conditions in the promotion pattern, the customer can be given the benefits in the action.


[#data_model]
== Data model

A JSON Schema corresponding to this data model can be found //[here].

== Diagram:
aaa

The data model is defined as shown below:


=== @baseType
description: The base type for use in polymorphic collections

type: string


=== @schemaLocation
description: A link to the schema describing a resource (for type extension).

type: string


=== @type
description: The class type of the actual resource (for type extension).

type: string


=== actionObjectId
description: It refers to the object (entity) ID which is impacted by the promotion action. When the Promotion -&amp;gt; type is 1: Award, the actionObjectId is the sub-account ID; When the Promotion -&amp;gt; type is 2: Discount, it is the offering ID; When the Promotion -&amp;gt; type is 3: reduction, it is the offering ID.

type: string


=== actionType
description: When the Promotion -&amp;gt; type is 1: Award, the action type can be one of the following:voice (minute),data (MB),data (GB),SMS,bonus point,physical gift,voucher,promotion code,an existing offering,currency. More types of action can be extended in future.

type: string


=== actionValue
description: When the Promotion -&amp;gt; type is 1: Award, it means the amount or value of the awards decided by actionType, such as:Amount of gift,Amount of bonus,Value of discount; When the Promotion -&amp;gt; type is 2: Discount, it means the value of the discount; When the Promotion -&amp;gt; type is 3: reduction, it means the value of the reduced money .

type: number


=== id
description: Unique identifier.

type: string


[#all_of]
== All Of

