= QuoteItem

[#domain]
== Domain

This schema is part of Customer

[#description]
== Description

A quote items describe an action to be performed on a productOffering or a product in order to get pricing elements and condition.


[#data_model]
== Data model

A JSON Schema corresponding to this data model can be found https://tmforum.org[here].

The data model is defined as shown below:


=== appointment
description: A reference to appointment(s) associated with this quote item

type: array


=== attachment
description: A reference to attachment(s) associated with this quote item

type: array


=== note
description: Free form text associated with the quote item

type: array


=== product
$ref of: xref:4.0.0@schemas:Tmf:ProductRefOrValue.adoc[]


=== productOffering
$ref of: xref:4.0.0@schemas:Tmf:ProductOfferingRef.adoc[]


=== quantity
description: Quantity asked for this quote item

type: integer


=== quoteItem
description: A structure to embedded quote item within quote item

type: array


=== quoteItemAuthorization
description: Authorization related to this quote item

type: array


=== quoteItemPrice
description: Price for this quote item

type: array


=== quoteItemRelationship
description: A relationship from item within a quote

type: array


=== productOfferingQualificationItem
description: A reference to a previously done POQ with item specified

$ref of: xref:4.0.0@schemas:Tmf:ProductOfferingQualificationItemRef.adoc[]


=== state
description: State of the quote item : described in the state machine diagram

$ref of: xref:4.0.0@schemas:Tmf:QuoteStateType.adoc[]


=== relatedParty
description: A reference to a party playing a role in this quote item

type: array


{&#x27;$ref&#x27;: &#x27;../../Gc/Customer/GcQuoteItem.schema.json#GcQuoteItem&#x27;}{&#x27;$ref&#x27;: &#x27;../../Core/SchemaContext.schema.json#SchemaContext&#x27;}