= QuoteItem

[#domain]
== Domain

This schema is part of Customer

[#description]
== Description
A quote items describe an action to be performed on a productOffering or a product in order to get pricing elements and condition.


[#data_model]
== Data model

A JSON Schema corresponding to this data model can be found //[here].

Diagram:
aaa

The data model is defined as shown below:


=== action
description: Action to be performed on this quote item (add, modify, remove, etc.)

type: string


=== appointment
description: A reference to appointment(s) associated with this quote item

type: array


=== attachment
description: A reference to attachment(s) associated with this quote item

type: array


=== id
description: Identifier of the quote item (generally it is a sequence number 01, 02, 03, ...)

type: string


=== note
description: Free form text associated with the quote item

type: array


=== product
$ref of: xref:v4.1@schemas:Tmf:ProductRefOrValue.adoc[]


=== productOffering
$ref of: xref:v4.1@schemas:Tmf:ProductOfferingRef.adoc[]


=== quantity
description: Quantity asked for this quote item

type: integer


=== quoteItem
description: A structure to embedded quote item within quote item

type: array


=== quoteItemAuthorization
description: Authorization related to this quote item

type: array


=== quoteItemPrice
description: Price for this quote item

type: array


=== quoteItemRelationship
description: A relationship from item within a quote

type: array


=== productOfferingQualificationItem
description: A reference to a previously done POQ with item specified

$ref of: xref:v4.1@schemas:Tmf:ProductOfferingQualificationItemRef.adoc[]


=== relatedParty
description: A reference to a party playing a role in this quote item

type: array


=== state
description: State of the quote item : described in the state machine diagram

type: string


[#all_of]
== All Of

This schema extends: xref:v4.1@schemas:Tmf:Entity.adoc[]
