= RatedProductUsage

[#domain]
== Domain

This schema is part of Product

[#description]
== Description

An occurrence of employing a product for its intended purpose with all rating details


[#data_model]
== Data model

A JSON Schema corresponding to this data model can be found https://tmforum.org[here].

The data model is defined as shown below:


=== bucketValueConvertedInAmount
$ref of: xref:v4.0@schemas:Tmf:Money.adoc[]


=== isBilled
description: Boolean indicating if usage have been billed or not

type: boolean


=== isTaxExempt
description: Indicates if the rated amount is exempt of tax

type: boolean


=== offerTariffType
description: Type of tariff applied

type: string


=== productRef
$ref of: xref:v4.0@schemas:Tmf:ProductRef.adoc[]


=== ratingAmountType
description: Type of amount

type: string


=== ratingDate
description: Date of usage rating

type: string


=== taxExcludedRatingAmount
$ref of: xref:v4.0@schemas:Tmf:Money.adoc[]


=== taxIncludedRatingAmount
$ref of: xref:v4.0@schemas:Tmf:Money.adoc[]


=== taxRate
description: Tax rate

type: number


=== usageRatingTag
description: Tag value: [usage]: the usage is always rated outside a usage bundle
[included usage]: the usage is rated inside a usage bundle
[non included usage]: the usage bundle is exhausted. The usage is rated outside the usage bundle

type: string


= All Of 
This schema extends: xref:v4.0@schemas:Tmf:Extensible.adoc[]
