= Refund

[#domain]
== Domain

This schema is part of Customer

[#description]
== Description

The Refund resource represents a performed Refund. It contains both information about the refund and the payment method used to perform it.


[#data_model]
== Data model

A JSON Schema corresponding to this data model can be found https://tmforum.org[here].

The data model is defined as shown below:


=== id
description: Unique identifier of Refund

type: string


=== href
description: Hypertext Reference of the refund

type: string


=== correlatorId
description: Unique identifier in the client for the refund in case it is needed to correlate

type: string


=== refundDate
description: Date when the refund was performed

type: string


=== name
description: Screen name of the refund

type: string


=== description
description: Text describing the contents of the refund

type: string


=== authorizationCode
description: Authorization code retrieved from an external payment gateway that could be used for conciliation

type: string


=== status
description: Status of the refund

type: string


=== statusDate
description: Date when the status was recorded

type: string


=== amount
description: Amount to be refunded (net of taxes)

$ref of: xref:v4.0@schemas:Tmf:Money.adoc[]


=== taxAmount
description: Tax applied

$ref of: xref:v4.0@schemas:Tmf:Money.adoc[]


=== totalAmount
description: Amount to be paid (including taxes)

$ref of: xref:v4.0@schemas:Tmf:Money.adoc[]


=== channel
$ref of: xref:v4.0@schemas:Tmf:ChannelRef.adoc[]


=== payment
$ref of: xref:v4.0@schemas:Tmf:PaymentRef.adoc[]


=== requestor
$ref of: xref:v4.0@schemas:Tmf:RelatedParty.adoc[]


=== paymentMethod
$ref of: xref:v4.0@schemas:Tmf:PaymentMethodRefOrValue.adoc[]


=== account
$ref of: xref:v4.0@schemas:Tmf:AccountRef.adoc[]


[#all_of]
== All Of

This schema extends: xref:v4.0@schemas:Tmf:Entity.adoc[]
