= ReserveProductStockItem

[#domain]
== Domain

This schema is part of Resource

[#description]
== Description

ReserveProductStockItem is used to request a stock reservation item for a product


[#data_model]
== Data model

A JSON Schema corresponding to this data model can be found https://tmforum.org[here].

The data model is defined as shown below:


=== id
description: Unique identifier of the ReserveProductStockItem.

type: string


=== quantityRequested
description: Quantity requested for this Product

$ref of: xref:v4.1@schemas:Tmf:Quantity.adoc[]


=== quantityReserved
description: Quantity reserved for this Product

$ref of: xref:v4.1@schemas:Tmf:Quantity.adoc[]


=== reserveProductStockState
description: State of the ReserveProductStockItem (acknowledged, inProgress, failed, done, cancelled).

$ref of: xref:v4.1@schemas:Tmf:TaskStateType.adoc[]


=== productStockRequested
description: Identifier of the Product Stock requested for this reservation item.

$ref of: xref:v4.1@schemas:Tmf:ProductStockRef.adoc[]


=== productStockReserved
description: Identifier of the Product Stock used for this reservation item.

$ref of: xref:v4.1@schemas:Tmf:ProductStockRef.adoc[]


=== requestedProduct
description: Requested product for reservation - a Product configuration could be passed

$ref of: xref:v4.1@schemas:Tmf:ProductRefOrValue.adoc[]


[#all_of]
== All Of

This schema extends: xref:v4.1@schemas:Tmf:Extensible.adoc[]
