= Reservation

[#domain]
== Domain

This schema is part of Common

[#description]
== Description
reservation api resource


[#data_model]
== Data model

A JSON Schema corresponding to this data model can be found //[here].



The data model is defined as shown below:


=== cancellationDate
description: Date when the reservation is cancelled.

type: string


=== cancellationReason
description: Reason why the reservation is cancelled.

type: string


=== channel
$ref of: xref:v4.0@schemas:Tmf:ChannelRef.adoc[]


=== completionDate
description: Date when the reservation was completed

type: string


=== creationDate
description: Date when the reservation was created

type: string


=== description
description: A string. free-text description of the reservation.

type: string


=== expectedCompletionDate
description: Expected completion date amended by the provider

type: string


=== relatedEntity
type: array


=== relatedParty
type: array


=== requestedCompletionDate
description: Requested completion date from the requestor perspective

type: string


=== requestedStartDate
description: Reservation fulfillment start date wished by the requestor. This is used when, for any reason, requestor cannot allow the reservation to begin before a specific date. 

type: string


=== reservationPeriod
description: Period of time for which the target entity is to be in a reserved state

$ref of: xref:v4.0@schemas:Tmf:TimePeriod.adoc[]


=== state
$ref of: xref:v4.0@schemas:Tmf:ReservationStateType.adoc[]


=== stateChangeDate
description: The date and time the state changed.

type: string


=== stateChangeReason
description: The reason for changing the state

type: string


=== validFor
$ref of: xref:v4.0@schemas:Tmf:TimePeriod.adoc[]


[#all_of]
== All Of

This schema extends: xref:v4.0@schemas:Tmf:Entity.adoc[]
