= ResourceSpecificationRelationship

[#domain]
== Domain

This schema is part of Resource

[#description]
== Description
A migration, substitution, dependency or exclusivity relationship between/among resource specifications.


[#data_model]
== Data model

A JSON Schema corresponding to this data model can be found https://tmforum.org[here].

The data model is defined as shown below:


=== relationshipType
description: Type of relationship such as migration, substitution, dependency, exclusivity

type: string


=== role
description: The association role for this resource specification

type: string


=== id
description: Unique identifier of target ResourceSpecification

type: string


=== href
description: Reference of the target ResourceSpecification

type: string


=== name
description: The name given to the target resource specification instance

type: string


=== defaultQuantity
description: The default number of the related resource that should be instantiated, for example a rack would typically have 4 cards, although it could support more.

type: integer


=== maximumQuantity
description: The maximum number of the related resource that should be instantiated, for example a rack supports a maximum of 16 cards

type: integer


=== minimumQuantity
description: The minimum number of the related resource that should be instantiated, for example a rack must have at least 1 card

type: integer


=== characteristic
description: A characteristic that refines the relationship. For example, consider the relationship between a slot and a card. For a half-height card it is important to know the position at which the card is inserted, so a characteristic Position might be defined on the relationship to allow capturing of this in the inventory

type: array


=== validFor
description: The period for which the ResourceSpecRelationship is valid

$ref of: xref:4.0.0@schemas:Tmf:TimePeriod.adoc[]

