= ResourceSpecificationCharacteristic

[#domain]
== Domain

This schema is part of Resource

[#description]
== Description

This class defines the characteristic features of a resource specification. Every ResourceSpecification has a variety of important attributes, methods, constraints, and
relationships, which distinguish a resource specification from other resource specifications.


[#data_model]
== Data model

A JSON Schema corresponding to this data model can be found https://tmforum.org[here].

The data model is defined as shown below:


=== resourceSpecCharRelationship
description: An aggregation, migration, substitution, dependency or exclusivity relationship between/among Specification Characteristics.

type: array


=== resourceSpecCharacteristicValue
description: A CharacteristicValueSpecification object is used to define a set of attributes, each of which can be assigned to a corresponding set of attributes in a ResourceSpecificationCharacteristic object. The values of the attributes in the CharacteristicValueSpecification object describe the values of the attributes that a corresponding ResourceSpecificationCharacteristic object can take on.

type: array


= All Of 
This schema extends: xref:v4.0@schemas:Tmf:CharacteristicSpecificationBase.adoc[]
