= ResourceSpecificationCharacteristicRelationship

[#domain]
== Domain

This schema is part of Resource

[#description]
== Description
An aggregation, migration, substitution, dependency or exclusivity relationship between/among ResourceSpecificationCharacteristics. The specification characteristic is embedded within the specification whose ID and href are in this entity, and identified by its ID.


[#data_model]
== Data model

A JSON Schema corresponding to this data model can be found //[here].

The data model is defined as shown below:


=== relationshipType
description: Type of relationship such as aggregation, migration, substitution, dependency, exclusivity

type: string


=== name
description: Name of the target characteristic within the specification

type: string


=== characteristicSpecificationId
description: Unique identifier of the characteristic within the specification

type: string


=== resourceSpecificationId
description: Unique identifier of the resource specification containing the target characteristic

type: string


=== resourceSpecificationHref
description: Hyperlink reference to the resource specification containing the target characteristic

type: string


=== validFor
description: The period for which the object is valid

$ref of: xref:v4.0@schemas:Tmf:TimePeriod.adoc[]


[#all_of]
== All Of

This schema extends: xref:v4.0@schemas:Tmf:Extensible.adoc[]
