= ResourceOrderItem

[#domain]
== Domain

This schema is part of Resource

[#description]
== Description
An identified part of the order. A resource order is decomposed into one or more order items.


[#data_model]
== Data model

A JSON Schema corresponding to this data model can be found //[here].

Diagram:


The data model is defined as shown below:


=== action
$ref of: xref:v4.0@schemas:Tmf:OrderItemActionType.adoc[]


=== id
description: Identifier of the line item (such as a sequence number 01, 02, 03)

type: string


=== orderItemRelationship
type: array


=== quantity
description: Quantity ordered

type: integer


=== resourceSpecification
$ref of: xref:v4.0@schemas:Tmf:ResourceSpecificationRef.adoc[]


=== appointment
$ref of: xref:v4.0@schemas:Tmf:AppointmentRef.adoc[]


=== resource
$ref of: xref:v4.0@schemas:Tmf:ResourceReforValue.adoc[]


=== state
$ref of: xref:v4.0@schemas:Tmf:ResourceOrderItemStateType.adoc[]


[#all_of]
== All Of

This schema extends: xref:v4.0@schemas:Tmf:Entity.adoc[]
