= ResourceSpecification

[#domain]
== Domain

This schema is part of Resource

[#description]
== Description
Resources are physical or non-physical components (or some combination of these) within an enterprise&#x27;s infrastructure or inventory. They are typically consumed or used by services (for example a physical port assigned to a service) or contribute to the realization of a Product (for example, a SIM card). They can be drawn from the Application, Computing and Network domains, and include, for example, Network Elements, software, IT systems, content and information, and technology components.
A ResourceSpecification is a base class that represents a generic means for implementing a particular type of Resource. In essence, a ResourceSpecification defines the common attributes and relationships of a set of related Resources, while Resource defines a specific instance that is based on a particular ResourceSpecification.


[#data_model]
== Data model

A JSON Schema corresponding to this data model can be found //[here].

Diagram:
aaa

The data model is defined as shown below:


=== id
description: Unique identifier of this REST resource

type: string


=== href
description: Hyperlink reference to this REST resource

type: string


=== name
description: Name given to this REST resource

type: string


=== description
description: Description of this REST resource

type: string


=== version
description: Resource Specification version

type: string


=== validFor
description: The period for which this REST resource is valid

$ref of: xref:v4.1@schemas:Tmf:TimePeriod.adoc[]


=== lastUpdate
description: Date and time of the last update of this REST resource

type: string


=== lifecycleStatus
description: Used to indicate the current lifecycle status of the resource specification

type: string


=== isBundle
description: A flag indicates that if this resource specification is a bundled specification (true) or single (false).

type: boolean


=== category
description: Category of the target resource like NetworkConnectivity, PhysicalLinks, Generic, L2Network and so on.

type: string


=== targetResourceSchema
description: A target resource schema reference. The reference object to the schema and type of target resource which is described by resource specification.

$ref of: xref:v4.1@schemas:Tmf:TargetResourceSchema.adoc[]


=== featureSpecification
description: A list of Features for this specification.

type: array


=== attachment
description: Complements the description of an element (for instance a resource) through video, pictures ...

type: array


=== relatedParty
description: A related party defines party or party role linked to a specific entity.

type: array


=== resourceSpecCharacteristic
description: A characteristic quality or distinctive feature of a ResourceSpecification.  The characteristic can be take on a discrete value, such as color, can take on a range of values, (for example, sensitivity of 100-240 mV), or can be derived from a formula (for example, usage time (hrs) = 30 - talk time *3). Certain characteristics, such as color, may be configured during the ordering or some other process.

type: array


=== resourceSpecRelationship
description: A migration, substitution, dependency or exclusivity relationship between/among resource specifications.

type: array


[#all_of]
== All Of

This schema extends: xref:v4.1@schemas:Tmf:Extensible.adoc[]
This schema extends: xref:v4.1@schemas:Tmf:Addressable.adoc[]
