= ResourceRelationship

[#domain]
== Domain

This schema is part of Resource

[#description]
== Description

Linked resources to the one instantiate, such as [bundled] if the resource is a bundle and you want to describe the bundled resources inside this bundle; [reliesOn] if the resource needs another already owned resource to rely on (e.g. an option on an already owned mobile access resource) [targets] or [isTargeted] (depending on the way of expressing the link) for any other kind of links that may be useful


[#data_model]
== Data model

A JSON Schema corresponding to this data model can be found https://tmforum.org[here].

The data model is defined as shown below:


=== relationshipType
description: Type of the resource relationship, such as [bundled] if the resource is a bundle and you want to describe the bundled resources inside this bundle; [reliesOn] if the resource needs another already owned resource to rely on (eg: an option on an already owned mobile access resource) [targets] or [isTargeted] (depending on the way of expressing the link) for any other kind of links that may be useful

type: string


=== resource
$ref of: xref:4.0.0@schemas:Tmf:ResourceRefOrValue.adoc[]


{&#x27;$ref&#x27;: &#x27;../Common/Entity.schema.json#Entity&#x27;}