= ResourceCandidate

[#domain]
== Domain

This schema is part of Resource

[#description]
== Description
ResourceCandidate is an entity that makes a resource specification available to a catalog. A ResourceCandidate and its associated resource specification may be published - made visible - in any number of resource catalogs, or in none.


[#data_model]
== Data model

A JSON Schema corresponding to this data model can be found //[here].

Diagram:
aaa

The data model is defined as shown below:


=== id
description: Unique identifier of this REST resource

type: string


=== href
description: Hyperlink reference to this REST resource

type: string


=== name
description: Name given to this REST resource

type: string


=== description
description: Description of this REST resource

type: string


=== version
description: the version of resource candidate

type: string


=== validFor
description: The period for which this REST resource is valid

$ref of: xref:v4.1@schemas:Tmf:TimePeriod.adoc[]


=== lastUpdate
description: Date and time of the last update of this REST resource

type: string


=== lifecycleStatus
description: Used to indicate the current lifecycle status of the resource candidate.

type: string


=== category
description: The categories in which this candidate is exposed

type: array


=== resourceSpecification
description: The detailed specification for this candidate

$ref of: xref:v4.1@schemas:Tmf:ResourceSpecificationRef.adoc[]


[#all_of]
== All Of

This schema extends: xref:v4.1@schemas:Tmf:Entity.adoc[]
