= Scale

[#domain]
== Domain

This schema is part of Resource

[#description]
== Description
Task Resource used to request scaling of a Resource Function


[#data_model]
== Data model

A JSON Schema corresponding to this data model can be found //[here].

THE DIAGRAM WILL BE IN HERE !!!
aaa

The data model is defined as shown below:


=== id
description: Unique identifier of the Scale task resource

type: string


=== href
description: Reference to the Scale task resource

type: string


=== name
description: Name of the Scale task resource

type: string


=== resourceFunction
description: Reference to the Resource Function that needs to be scaled

$ref of: xref:v4.0@schemas:Tmf:ResourceFunctionRef.adoc[]


=== scaleType
description: Type of scaling requested

type: string


=== aspectId
description: Scaling aspect is the dimension along which the Resource Function needs to be scaled. The id of the aspect is provided here

type: string


=== numberOfSteps
description: Number of scaling steps in the direction indicated by type of scale

type: integer


=== schedule
description: Schedule for the scale. If not provided then needs to be actioned immediately

type: array


=== state
description: Tracks the lifecycle status of the migrate request.

$ref of: xref:v4.0@schemas:Tmf:TaskStateType.adoc[]


[#all_of]
== All Of

This schema extends: xref:v4.0@schemas:Tmf:Entity.adoc[]
