= ScheduleDefinition

[#domain]
== Domain

This schema is part of Common

[#description]
== Description
The schedule definition for running jobs.


[#data_model]
== Data model

A JSON Schema corresponding to this data model can be found //[here].

THE DIAGRAM WILL BE IN HERE !!!
aaa

The data model is defined as shown below:


=== scheduleDefinitionStartTime
description: The Start time of the Schedule Definition

type: string


=== scheduleDefinitionEndTime
description: The Endtime of the Schedule Definition. If the attribute is empty the Schedule run forever, not having a time constraint.

type: string


=== recurringFrequency
description: A recurring frequency to run a job within day that is included in schedule definition, for example: every 5 minutes, 15 minute, 30 minutes, 1 hour

type: string


=== excludedDate
description: A list of specific dates that should be excluded from the Schedule Definition.

type: array


=== scheduleDefinitionHourRange
description: A list of time ranges within a specific day that the schedule will be active on, for example 08:00-12:00, 16:00-19:00.

type: string


=== WeeklyScheduledDefinition
description: The weekly schedule is used to define a schedule that is based on the days of the week, e.g. a schedule that will be active only on Monday and Tuesday.

type: array


=== monthlyScheduleDayOfMonthDefinition
description: The schedule definition for running the threshold job

type: array


=== MonthlyScheduleDayOfWeekDefinition
$ref of: xref:v4.0@schemas:Tmf:.adoc[]


=== dateScheduleDefintion
description: The date schedule is used to define a schedule that is based on specific dates, such as December 31st 2015, Feberaury 28th 2013

type: array


[#all_of]
== All Of

This schema extends: xref:v4.0@schemas:Tmf:Extensible.adoc[]
