= ServiceCatalog

[#domain]
== Domain

This schema is part of Service

[#description]
== Description

The root entity for service catalog management.
A service catalog is a group of service specifications made available through service candidates that an organization provides to the consumers (internal consumers like its employees or B2B customers or B2C customers). 
A service catalog typically includes name, description and time period that is valid for. It will have a list of ServiceCandidate catalog items. A ServiceCandidate is an entity that makes a ServiceSpecification available to a catalog.
A ServiceCandidate and its associated ServiceSpecification may be &quot;published&quot; - made visible -in any number of ServiceCatalogs, or in none.


[#data_model]
== Data model

A JSON Schema corresponding to this data model can be found https://tmforum.org[here].

The data model is defined as shown below:


=== category
description: List of service categories associated with this catalog

type: array


=== description
description: Description of this catalog

type: string


=== lastUpdate
description: Date and time of the last update

type: string


=== lifecycleStatus
description: Used to indicate the current lifecycle status

type: string


=== name
description: Name of the service catalog

type: string


=== relatedParty
description: List of parties or party roles related to this category

type: array


=== validFor
description: The period for which the service catalog is valid

$ref of: xref:v4.0@schemas:Tmf:TimePeriod.adoc[]


=== version
description: ServiceCatalog version

type: string


= All Of 
This schema extends: xref:v4.0@schemas:Tmf:Addressable.adoc[]
This schema extends: xref:v4.0@schemas:Tmf:Extensible.adoc[]
