= Service-ProductOfferAnalytics

[#domain]
== Domain

This schema is part of Analytics

[#description]
== Description
No description on schema


[#data_model]
== Data model

A JSON Schema corresponding to this data model can be found //[here].

== Diagram:
aaa

The data model is defined as shown below:


=== offerActivationDate
description: Activation date of Offer

type: string


=== offerOcAmount
description: Offering One time amount

type: number


=== offerRcAmount
description: Offering Recurrent amount

type: number


=== offerUsageAmount
description: Offering Usage amount

type: number


=== offerUnitValue
description: Offering Chargeable unit

type: number


=== customerStatusDate
description: Date when status was set or changed last time

type: string


=== customerCreationDate
description: Date when customer was created

type: string


=== customerBirthDate
description: Date of birth

type: string


=== arpuAmount
$ref of: xref:v4.1@schemas:Tmf:Money.adoc[]


=== accountStatusDate
description: Status last change date

type: string


=== accountCreationDate
description: Account creation Date

type: string


=== subscriptionStatusDate
description: Status last change date

type: string


=== subscriptionCreationDate
description: Subscriber creation date

type: string


=== subscriptionActivationDate
description: Activation date

type: string


=== planActivationDate
description: Activation date of billing plan

type: string


=== contractStartDate
description: Contract start date

type: string


=== contractEndDate
description: Contract end date

type: string


=== contractMinimumPeriodDays
description: Minimal contract duration specified with number of days

type: number


=== priceChargeAmount
description: Amount corresponding to the charge type

type: number


=== dataCreationTimestamp
description: Time stamp for data creation (e.g. system dump creation, event generation…)

type: string


=== runTimestamp
description: Time stamp for data upload run

type: string


=== validFromTimestamp
description: Time stamp for business validity of entity record

type: string


[#all_of]
== All Of

