= ServiceQualificationItem

[#domain]
== Domain

This schema is part of Service

[#description]
== Description

A ServiceQualificationItem relates to a specific service being checked in a qualification operation.


[#data_model]
== Data model

A JSON Schema corresponding to this data model can be found https://tmforum.org[here].

The data model is defined as shown below:


=== expectedActivationDate
description: The date when the service is expected to be activated

type: string


=== id
description: Id of the Service Qualification Item

type: string


=== service
description: Configure the service characteristics (only configurable characteristics and necessary only if a non default value is selected) and/or identify the service that needs to be modified/deleted.

$ref of: xref:v4.0@schemas:Tmf:ServiceRefOrValue.adoc[]


=== expectedServiceAvailabilityDate
description: Date when the requester looks for service availability

type: string


=== expirationDate
description: Date when the qualification item response expires

type: string


=== category
description: The category resource is used to group product offerings, service and resource candidates in logical containers. Categories can contain other categories and/or product offerings, resource or service candidates.

$ref of: xref:v4.0@schemas:Tmf:ServiceCategoryRef.adoc[]


[#all_of]
== All Of

This schema extends: xref:v4.0@schemas:Tmf:Entity.adoc[]
