= ServiceSpecCharacteristic

[#domain]
== Domain

This schema is part of Service

[#description]
== Description

This class represents the key features of this service specification. For example, bandwidth is a characteristic of many different types of services; if bandwidth is a relevant characteristic (e.g., from the point-of-view of a Customer obtaining this Service via a Product) then bandwidth would be a ServiceSpecCharacteristic for that particular Service.


[#data_model]
== Data model

A JSON Schema corresponding to this data model can be found https://tmforum.org[here].

The data model is defined as shown below:


=== name
description: A word, term, or phrase by which this characteristic specification is known and distinguished from other characteristic specifications.

type: string


=== description
description: A narrative that explains in detail what the serviceSpecCharacteristic is

type: string


=== valueType
description: A kind of value that the characteristic can take on, such as numeric, text and so forth

type: string


=== configurable
description: If true, the Boolean indicates that the serviceSpecCharacteristic is configurable

type: boolean


=== validFor
description: The period for which the serviceSpecCharacteristic is valid

$ref of: xref:4.0.0@schemas:Tmf:TimePeriod.adoc[]


=== @valueSchemaLocation
description: This (optional) field provides a link to the schema describing the value type.

type: string


=== minCardinality
description: The minimum number of instances a CharacteristicValue can take on. For example, zero to five phone numbers in a group calling plan, where zero is the value for the minCardinality.

type: integer


=== maxCardinality
description: The maximum number of instances a CharacteristicValue can take on. For example, zero to five phone numbers in a group calling plan, where five is the value for the maxCardinality.

type: integer


=== isUnique
description: An indicator that specifies if a value is unique for the specification. Possible values are; &quot;unique while value is in effect&quot; and &quot;unique whether value is in effect or not&quot;

type: boolean


=== regex
description: A rule or principle represented in regular expression used to derive the value of a characteristic value.

type: string


=== extensible
description: An indicator that specifies that the values for the characteristic can be extended by adding new values when instantiating a characteristic for an Entity.

type: boolean


=== serviceSpecCharacteristicValue
description: A list of service spec characteristic values (ServiceSpecCharacteristicValue [*]). A ServiceSpecCharacteristicValue object is used to define a set of attributes, each of which can be assigned to a corresponding set of attributes in a ServiceSpecCharacteristic object. The values of the attributes in the ServiceSpecCharacteristicValue object describe the values of the attributes that a corresponding ServiceSpecCharacteristic object can take on.

type: array


=== serviceSpecCharRelationship
description: A list of service spec char relationships (ServiceSpecCharRelationship [*]). An aggregation, migration, substitution, dependency or exclusivity relationship between/among Specification Characteristics.

type: array


= All Of 
