= ServiceLevelAgreement

[#domain]
== Domain

This schema is part of EngagedParty

[#description]
== Description

Service Level Agreement (SLA) is a type of agreement that represents targets formally or informally agreed between parties in order to achieve and maintain specified Quality of Service.


[#data_model]
== Data model

A JSON Schema corresponding to this data model can be found https://tmforum.org[here].

The data model is defined as shown below:


=== description
description: verbal description of the Service Level Agreement (SLA)

type: string


=== initialDate
description: Date at which the agreement was initialized

type: string


=== lastUpdate
description: Date and time of the last update

type: string


=== completionDate
description: Date at which the agreement is completed

$ref of: xref:4.0.0@schemas:Tmf:TimePeriod.adoc[]


=== statementOfIntent
description: An overview and goals of the Agreement

type: string


=== lifecycleStatus
description: The current lifecycle status of the SLA. Typical values are: in-process, approved and rejected

type: string


=== statusChangeDate
description: A date time( DateTime). The date that the entity status changed to the current one

type: string


=== agreementType
description: The type of the agreement. For example commercial, operational

type: string


=== externalId
description: external identifier

type: string


=== version
description: A string identifying the version of the agreement

type: string


=== agreementSpecification
description: reference to the corresponding specification for this SLA

$ref of: xref:4.0.0@schemas:Tmf:AgreementSpecificationRef.adoc[]


=== agreementItem
type: array


=== termOrCondition
type: array


=== agreementAuthorization
type: array


=== characteristic
type: array


=== relatedParty
type: array


=== attachment
description: Attachments that may be of relevance to this entity, such as picture, document, media

type: array


=== note
type: array


=== agreementRelationship
description: A relationship from this SLA to another agreement/SLA

type: array


=== name
description: name associated with the SLA

type: string


=== constraint
description: This is a list of references to rules applied to this SLA

type: array


=== entityRelationship
description: Relationship to another entity

type: array


=== validFor
description: The period for which the SLA is valid  (A period of time, either as a deadline (endDateTime only) a startDateTime only, or both)

$ref of: xref:4.0.0@schemas:Tmf:TimePeriod.adoc[]


= All Of 
