= ServiceProblem

[#domain]
== Domain

This schema is part of Service

[#description]
== Description
The problem information for Middle B which is abstracted in the service layer from the issued event information by First B


[#data_model]
== Data model

A JSON Schema corresponding to this data model can be found //[here].

Diagram:
aaa

The data model is defined as shown below:


=== place
description: A list of the locations affected by the problem. At least one of affectedResource, affectedService or affectedLocation should be present.

type: array


=== affectedNumberOfServices
description: Number of affected services

type: integer


=== affectedResource
description: A list of the resources affected by the problem. At least one of affectedResource, affectedService or affectedLocation should be present.

type: array


=== affectedService
description: List of affected services. At least one of affectedResource, affectedService or affectedLocation should be present.

type: array


=== category
description: Classifier for the problem. Settable. For example, this is used for distinguish the category of problem originator in [role].[category] format. Example: serviceProvider.declarer, supplier.originated, system.originated

type: string


=== note
description: A list of comments or notes made on the problem

type: array


=== externalIdentifier
type: array


=== name
description: Name of the Service Problem

type: string


=== description
description: Free form text describing the Service Problem

type: string


=== characteristic
type: array


=== firstAlert
description: Indicates what first alerted the system to the problem. It is not the root cause of the Service Problem. Examples: Threshold crossing alert

$ref of: xref:v4.2@schemas:Tmf:RelatedEntity.adoc[]


=== impactImportanceFactor
description: Impact Importance is characterized by an Impact Importance Factor: overall importance of the impact of all the affected services, e.g. 0 (zero impact) to 100 (worst impact). The Impact Importance is a calculated field which is set by the OSS determining the impact.

type: string


=== impactPattern
description: Define the patterns of impact (optional)- e.g. other service characteristics- Used when defining impact through another pattern than the predefined attributes.

$ref of: xref:v4.2@schemas:Tmf:ImpactPattern.adoc[]


=== originatingSystem
description: Indicates where the problem was generated

type: string


=== parentProblem
description: The parent problem to which this problem is attached.

type: array


=== priority
description: An indication varying from 1 (highest) to 10 (lowest) of how important it is for the service provider to correct the Service Problem.

type: integer


=== problemEscalation
description: Indicates if this service problem has been escalated or not. Possible values are 0 to 10. A value of zero means no escalation. The meanings of values 1-10 are to be determined by the user of the interface, but they show increasing levels of escalation.

type: string


=== reason
description: Free text or optionally structured text. It can be Unknown.

type: string


=== relatedEvent
description: List of events associated to this problem

type: array


=== relatedEntity
description: List of entities associated with this problem

type: array


=== originatorParty
description: Individual or organization that created the problem

$ref of: xref:v4.2@schemas:Tmf:RelatedParty.adoc[]


=== responsibleParty
description: Individual or organization responsible for handling this problem

$ref of: xref:v4.2@schemas:Tmf:RelatedParty.adoc[]


=== relatedParty
description: List of parties or party roles playing a role within the service problem

type: array


=== rootCauseResource
description: Resource(s) that are associated to the underlying service problems that are the Root Cause of this one if any (used only if applicable).

type: array


=== rootCauseService
description: Service(s) that are associated to the underlying service problems that are the Root Cause of this one if any (used only if applicable)

type: array


=== resolutionDate
description: Time the problem was resolved

type: string


=== status
$ref of: xref:v4.2@schemas:Tmf:ServiceProblemStateType.adoc[]


=== statusChangeDate
description: Time the problem was last status changed

type: string


=== statusChangeReason
description: The reason of state change

type: string


=== lastUpdate
description: Time the problem was last changed

type: string


=== creationDate
description: Time the problem was created

type: string


=== trackingRecord
description: List of tracking records that allow the tracking of modifications on the problem.The tracking records should not be embedded in the problem to allow retrieving the problem without the tracking records

type: array


=== underlyingAlarm
description: A list of alarms underlying this problem.

type: array


=== slaViolation
description: A List of SLA violations associated with this problem.

type: array


=== troubleTicket
description: A list of trouble tickets associated with this problem.

type: array


=== underlyingProblem
description: A list of underlying problems. Relevant only if this problem is derived from other problems.

type: array


[#all_of]
== All Of

This schema extends: xref:v4.2@schemas:Tmf:Entity.adoc[]
