= ServiceLevelObjective

[#domain]
== Domain

This schema is part of Service

[#description]
== Description
Service level objectives are defined in terms of parameters and metrics, thresholds, and tolerances 
associated with the parameters.


[#data_model]
== Data model

A JSON Schema corresponding to this data model can be found //[here].

Diagram:
aaa

The data model is defined as shown below:


=== conformanceComparator
description: An operator that specifies whether a Service Level Objective is 
violated above or below the conformanceTarget.

type: string


=== conformancePeriod
description: An interval of time during which the Conformance Target must be measured.

$ref of: xref:v4.0@schemas:Tmf:TimePeriod.adoc[]


=== conformanceTarget
description: A value used to determine if Service Level Objective is met. 
The data type should be adjusted case by case.

type: string


=== graceTimes
description: The number of times an objective can remain un-updated without 
a violation of a Service Level Agreement in reference to a measurement period and/or Service Level Agreement reporting period.

type: string


=== href
description: The hyperlink to access a service level objective.

type: string


=== id
description: The identifier of a service level objectives.

type: string


=== name
description: The name of the service level objectives.

type: string


=== thresholdTarget
description: A value that used to specify when a warning should be used 
that indicates an objective is danger of not being met. Notice, the data type should be adjusted case by case.

type: string


=== tolerancePeriod
description: A value that specifies the allowable time variation of a conformance

$ref of: xref:v4.0@schemas:Tmf:TimePeriod.adoc[]


=== toleranceTarget
description: A value that specifies the allowable variation of a conformance 
Target. The data type should be adjusted case by case.

type: string


=== validFor
description: A valid duration of a thing.

$ref of: xref:v4.0@schemas:Tmf:TimePeriod.adoc[]


=== serviceLevelSpecParameter
description: A parameter for this objective

$ref of: xref:v4.0@schemas:Tmf:ServiceLevelSpecParameter.adoc[]


=== serviceLevelSpecConsequence
description: A list of consequences for this objective.

type: array


[#all_of]
== All Of

This schema extends: xref:v4.0@schemas:Tmf:Entity.adoc[]
