= ServiceLevelAgreement

[#domain]
== Domain

This schema is part of EngagedParty

[#description]
== Description
Service Level Agreement


[#data_model]
== Data model

A JSON Schema corresponding to this data model can be found //[here].

== Diagram:
aaa

The data model is defined as shown below:


=== description
description: verbal description of the SLA

type: string


=== href
description: Hyperlink to access the SLA definition

type: string


=== id
description: Unique identifier created by SLA Management system

type: string


=== name
description: name associated with the SLA

type: string


=== relatedParty
type: array


=== rule
type: array


=== template
$ref of: xref:v4.2@schemas:Tmf:Template.adoc[]


=== validFor
description: The period for which the SLA is valid  (A period of time, either as a deadline (endDateTime only) a startDateTime only, or both)

$ref of: xref:v4.2@schemas:Tmf:TimePeriod.adoc[]


=== version
type: string


[#all_of]
== All Of

This schema extends: xref:v4.2@schemas:Tmf:Entity.adoc[]
