= ServiceCandidate

[#domain]
== Domain

This schema is part of Service

[#description]
== Description

ServiceCandidate is an entity that makes a service specification available to a catalog. A
ServiceCandidate and its associated service specification may be published - made visible - in any number of service catalogs, or in none. One service specification can be composed of other service specifications.


[#data_model]
== Data model

A JSON Schema corresponding to this data model can be found https://tmforum.org[here].

The data model is defined as shown below:


=== description
description: Description of this REST resource

type: string


=== version
description: the version of service candidate

type: string


=== validFor
description: The period for which this REST resource is valid

$ref of: xref:v5.0@schemas:Tmf:TimePeriod.adoc[]


=== lastUpdate
description: Date and time of the last update of this REST resource

type: string


=== category
description: List of categories for this candidate

type: array


= All Of 
This schema extends: xref:v5.0@schemas:Gc:GcAddressable.adoc[]
This schema extends: xref:v5.0@schemas:Gc:GcExtensible.adoc[]
