= ServiceTestSpecification

[#domain]
== Domain

This schema is part of Service

[#description]
== Description

The service test specification describes the service test in terms of parameters to be configured and 
measures to be taken.


[#data_model]
== Data model

A JSON Schema corresponding to this data model can be found https://tmforum.org[here].

The data model is defined as shown below:


=== description
description: Description of a service test specification.

type: string


=== testMeasureDefinition
description: A list of definitions for the measurements for the test defined by this specification

type: array


=== relatedServiceSpecification
description: The related service specification may relate to more than one service specification.

type: array


=== serviceTestSpecRelationship
description: A list of service test specifications related to this specification e.g. dependency, substitution

type: array


= All Of 
This schema extends: xref:4.0.0@schemas:Tmf:EntitySpecification.adoc[]
