= ServiceFeatureSpecification

[#domain]
== Domain

This schema is part of Service

[#description]
== Description
Specification for service features


[#data_model]
== Data model

A JSON Schema corresponding to this data model can be found //[here].

Diagram:
aaa

The data model is defined as shown below:


=== id
description: Identifier of the feature specification. Must be locally unique within the containing specification, thus allowing direct access to the feature spec.

type: string


=== version
description: Version of the feature specification

type: string


=== name
description: Unique name given to the feature specification

type: string


=== isBundle
description: A flag indicating if this is a feature group (true) or not (false)

type: boolean


=== validFor
description: The period for which this feature specification is valid

$ref of: xref:v4.2@schemas:Tmf:TimePeriod.adoc[]


=== featureSpecRelationship
description: A dependency, exclusivity or aggratation relationship between/among feature specifications.

type: array


=== constraint
description: A list of feature constraints/rules

type: array


=== isEnabled
description: A flag indicating if the feature is enabled (true) or not (false)

type: boolean


=== featureSpecCharacteristic
description: This is a list of characteristics for a particular feature

type: array


[#all_of]
== All Of

This schema extends: xref:v4.2@schemas:Tmf:Entity.adoc[]
