= ServiceOrder

[#domain]
== Domain

This schema is part of Service

[#description]
== Description
No description on schema


[#data_model]
== Data model

A JSON Schema corresponding to this data model can be found https://tmforum.org[here].

The data model is defined as shown below:


=== cancellationDate
description: Date when the order is cancelled. This is used when order is cancelled. 

type: string


=== cancellationReason
description: Reason why the order is cancelled. This is used when order is cancelled. 

type: string


=== category
description: Used to categorize the order, useful for the OM system, such as: Broadband, TVOption

type: string


=== completionDate
description: Effective delivery date amended by the provider

type: string


=== description
description: A free-text description of the service order

type: string


=== expectedCompletionDate
description: Expected delivery date amended by the provider

type: string


=== externalId
description: ID given by the consumer to facilitate searches

type: string


=== externalReference
description: 

type: array


=== note
description: Extra-information about the order; e.g. useful to add extra delivery information that could be useful for a human process

type: array


=== notificationContact
description: Contact attached to the order to send back information regarding this order

type: string


=== orderRelationship
description: A list of service orders related to this order (e.g. prerequisite, dependent on)

type: array


=== priority
description: Can be used by consumers to prioritize orders in a Service Order Management system

type: string


=== relatedParty
description: A list of parties which are involved in this order and the role they are playing

type: array


=== requestedCompletionDate
description: Requested delivery date from the requestors perspective

type: string


=== requestedStartDate
description: Order start date wished by the requestor

type: string


=== startDate
description: Date when the order was started for processing

type: string


=== milestone
description: A list of milestones related to this order

type: array


=== jeopardyAlert
description: A list of jeopardy alerts related to this order

type: array


=== errorMessage
description: the error message if the order closed by an error

$ref of: xref:4.0.0@schemas:Tmf:ServiceOrderErrorMessage.adoc[]

