= ServiceLevelSpecification

[#domain]
== Domain

This schema is part of Service

[#description]
== Description

A Service Level Specification represents a pre-defined or negotiated set of Service Level 
Objectives. In addition, certain consequences are associated with not meeting the Service Level 
Objectives. Service Level Agreements are expressed in terms of Service Level Specifications.


[#data_model]
== Data model

A JSON Schema corresponding to this data model can be found https://tmforum.org[here].

The data model is defined as shown below:


=== description
description: A brief introduction of a service level specification.

type: string


=== href
description: The hyperlink to access a service level specification.

type: string


=== id
description: The identifier to a service level specification.

type: string


=== name
description: The name of Service Level Specification

type: string


=== validFor
description: A valid duration of a thing.

$ref of: xref:v4.0@schemas:Tmf:TimePeriod.adoc[]


=== relatedServiceLevelObjective
description: A list of objectives related to this service level specification

type: array


[#all_of]
== All Of

This schema extends: xref:v4.0@schemas:Tmf:Entity.adoc[]
