= Shipment

[#domain]
== Domain

This schema is part of EngagedParty

[#description]
== Description

No description on schema


[#data_model]
== Data model

A JSON Schema corresponding to this data model can be found https://tmforum.org[here].

The data model is defined as shown below:


=== id
description: Unique identifier of the shipment

type: string


=== href
description: Reference of the shipment

type: string


=== description
description: Description of the shipment. It could be the same as the description of the shipment specification.

type: string


=== name
description: Name of the shipment. It could be the same as the name of the shipment specification.

type: string


=== state
description: The current status of the shipment.

type: string


=== completionDate
description: Effective delivery date amended by the provider

type: string


=== deliveryDate
description: Is the date at which the shipment was completed (customer has taken ownership of the package)

type: string


=== collectionDate
description: The date the package was collected from the carrier (Collection scenario)

type: string


=== expectedDeliveryDate
description: The date that the shipment will be delivered

type: string


=== requestedDeliveryDate
description: The date requester by the sender for shipment delivery

type: string


=== weight
description: Weight of the shipping package/parcel

$ref of: xref:v4.1@schemas:Tmf:Quantity.adoc[]


=== shippingInstruction
description: Shipping instructions, usually relevant for the carrier.

$ref of: xref:v4.1@schemas:Tmf:ShippingInstruction.adoc[]


=== shipmentCharacteristic
description: List of characteristics with values

type: array


=== shipmentItem
description: List of items that are part of the shipment (parcel/package)

type: array


=== shipmentPrice
description: Shipment price

$ref of: xref:v4.1@schemas:Tmf:ProductPrice.adoc[]


=== note
description: A list of notes made on this shipment

type: array


=== shipmentTracking
description: A reference number usually provided by the delivery partner(carrier) used to identify and track shipments across the delivery network

$ref of: xref:v4.1@schemas:Tmf:ShipmentTrackingRef.adoc[]


=== placeFrom
description: Source location of the package. E.g. warehouse or shop location

$ref of: xref:v4.1@schemas:Tmf:RelatedPlaceRefOrValue.adoc[]


=== placeTo
description: Destination of the package. E.g. customer home address

$ref of: xref:v4.1@schemas:Tmf:RelatedPlaceRefOrValue.adoc[]


=== relatedShipment
description: A list of existing shipments that has some form of correlation with the given shipment

type: array


=== paymentMethod
description: Payment method to be used when delivering the package(e.g.: cash, credit card, ). Structure including at least attribute name. Notice that the use of a voucher can be managed as a specific methodtype, where he voucher code can be passed as value.

$ref of: xref:v4.1@schemas:Tmf:PaymentMethodRef.adoc[]


=== externalIdentifier
description: An identification of an entity that is owned by or originates in a software system different from the current system, for example a ProductOrder handed off from a commerce platform into an order handling system. The structure identifies the system itself, the nature of the entity within the system (e.g. class name) and the unique ID of the entity within the system. It is anticipated that multiple external IDs can be held for a single entity, e.g. if the entity passed through multiple systems on the way to the current system. In this case the consumer is expected to sequence the IDs in the array in reverse order of provenance, i.e. most recent system first in the list.

type: array


=== shipmentSpecification
description: A set of characteristics to describe the shipment

$ref of: xref:v4.1@schemas:Tmf:ShipmentSpecificationRefOrValue.adoc[]


=== relatedParty
description: A list of parties which are involved in this shipment and the role they are playing

type: array


=== attachment
description: Attachments that may be of relevance to this shipment, such as shippingLabels, Signature or photos of the delivery


type: array


= All Of 
This schema extends: xref:v4.1@schemas:Tmf:Entity.adoc[]
