= ShippingOrderItem

[#domain]
== Domain

This schema is part of EngagedParty

[#description]
== Description
A list of shipping order items


[#data_model]
== Data model

A JSON Schema corresponding to this data model can be found //[here].

THE DIAGRAM WILL BE IN HERE !!!


The data model is defined as shown below:


=== id
description: Identifier of the Shipping Order Item

type: string


=== action
description: The action to be carried out on the Product. Can be: add, modify, delete, noChange

$ref of: xref:v4.2@schemas:Tmf:ShippingOrderItemActionType.adoc[]


=== status
description: status of shipping order item. e.g &quot;active&quot; , &quot;savedForLater&quot;

type: string


=== shipment
description: A set of goods to be shipped

$ref of: xref:v4.2@schemas:Tmf:Shipment.adoc[]


=== shippingOrderItemOffer
description: Each shipping order item can have a corresponding product offer in the product catalog.

$ref of: xref:v4.2@schemas:Tmf:ProductOfferingRef.adoc[]


[#all_of]
== All Of

This schema extends: xref:v4.2@schemas:Tmf:Entity.adoc[]
