= ShippingOrder

[#domain]
== Domain

This schema is part of EngagedParty

[#description]
== Description
A Shipping Order is a document used by a business to specify what items are to be transferred from a storage location or warehouse to which person and to which new location. A Shipping Order can typically be sent along with a shipment of goods so that the person receiving them can verify that the document correctly reflects the items that they actually received.


[#data_model]
== Data model

A JSON Schema corresponding to this data model can be found //[here].

THE DIAGRAM WILL BE IN HERE !!!
aaa

The data model is defined as shown below:


=== id
description: Identifier of the Shipping Order

type: string


=== href
description: Shipping Order unique reference

type: string


=== relatedShippingOrder
description: An existing shipping order that has some form of correlation with the given shipping order

$ref of: xref:v4.2@schemas:Tmf:RelatedShippingOrder.adoc[]


=== productOrderRef
description: The product order for which the shipping order is created, if supplied as input the attribute id must be populated

$ref of: xref:v4.2@schemas:Tmf:ProductOrderRef.adoc[]


=== shippingOrderItem
description: A list of shipping order items. Each shipping order item has a corresponding Shipment(e.g. parcel) which has one or multiple products in it

type: array


=== characteristic
description: List of characteristics with values

type: array


=== note
description: A list of notes made on this shipping shipment

type: array


=== shippingOrderPrice
description: Shipping Order price

$ref of: xref:v4.2@schemas:Tmf:Price.adoc[]


=== shippingOrderOffer
description: Shipping order can have a corresponding entry in the product catalog (product offering)

$ref of: xref:v4.2@schemas:Tmf:ProductOfferingRef.adoc[]


[#all_of]
== All Of

This schema extends: xref:v4.2@schemas:Tmf:Entity.adoc[]
