= ShipmentSpecificationRelationship

[#domain]
== Domain

This schema is part of EngagedParty

[#description]
== Description
A migration, substitution, dependency or exclusivity relationship between/among entity specifications.


[#data_model]
== Data model

A JSON Schema corresponding to this data model can be found //[here].

Diagram:


The data model is defined as shown below:


=== name
description: The name given to the target entity specification instance

type: string


=== role
description: The association role for this entity specification

type: string


=== relationshipType
description: Type of relationship such as migration, substitution, dependency, exclusivity

type: string


=== associationSpec
description: A specification for an association used by this relationship


$ref of: xref:v4.0@schemas:Tmf:AssociationSpecificationRef.adoc[]


=== validFor
description: The period for which this REST resource is valid

$ref of: xref:v4.0@schemas:Tmf:TimePeriod.adoc[]


[#all_of]
== All Of

This schema extends: xref:v4.0@schemas:Tmf:Entity.adoc[]
