= ShoppingCart

[#domain]
== Domain

This schema is part of Customer

[#description]
== Description
Shopping Cart resource is used for the temporarily selection and reservation of product offerings in e-commerce, call center and retail purchase. Shopping cart supports purchase of both physical and digital goods and service (e.g. handset, telecom network service). Shopping Cart contain list of cart items, a reference to customer (partyRole) or contact medium in case customer not exist, and the total items price including promotions


[#data_model]
== Data model

A JSON Schema corresponding to this data model can be found //[here].

== Diagram:
aaa

The data model is defined as shown below:


=== href
description: Hyperlink to access the shopping cart

type: string


=== id
description: Unique identifier created on provider side (e.g. Order Capture system)

type: string


=== validFor
description: The period for which the shopping cart is valid (e.g. 90 if no activity or 7 days if cart is empty)

$ref of: xref:v4.1@schemas:Tmf:TimePeriod.adoc[]


=== contactMedium
type: array


=== cartTotalPrice
description: Total amount of the shopping cart, usually of money, that represents the actual price paid by the Customer for cart (considering only &quot;Active&quot; cart items)

type: array


=== cartItem
type: array


=== relatedParty
type: array


[#all_of]
== All Of

This schema extends: xref:v4.1@schemas:Tmf:Entity.adoc[]
