= SimpleThresholdRule

[#domain]
== Domain

This schema is part of Common

[#description]
== Description

A threshold rule that is based on explicit definition of attributes that represent a Boolean expression


[#data_model]
== Data model

A JSON Schema corresponding to this data model can be found https://tmforum.org[here].

The data model is defined as shown below:


=== conformanceComparatorLower
description: An operator that when applied on a value (of conformanceTargetLower) specifies whether a Performance threshold rule is crossed or ceased to be crossed.

type: integer


=== conformanceComparatorUpper
description: An operator that when applied on a value (of conformanceTargetUpper) specifies whether a Performance threshold rule is crossed or ceased to be crossed.

type: string


=== conformancePeriod
$ref of: xref:4.0.0@schemas:Tmf:.adoc[]


=== conformanceTargetLower
description: A value used to determine if the Performance threshold is crossed or ceased to be crossed, serving as an lower value

type: integer


=== conformanceTargetUpper
description: A value used to determine if the Performance threshold is crossed or ceased to be crossed, serving as an upper value

type: integer


=== gracePeriods
description: The number of times an objective can remain un-updated in reference to the conformancePeriod without a Performance threshold Consequence being initiated

type: integer


=== thresholdTarget
description: A percent that is used to specify when a warning should be used that indicates a Performance threshold is in danger of not being met.

type: integer


=== tolerancePeriod
$ref of: xref:4.0.0@schemas:Tmf:.adoc[]


= All Of 
