= SLA

[#domain]
== Domain

This schema is part of EngagedParty

[#description]
== Description

Part of a business agreement between a Service Provider and a Customer, quantitatively specifying the service performance level the Service Provider commits to deliver.


[#data_model]
== Data model

A JSON Schema corresponding to this data model can be found https://tmforum.org[here].

The data model is defined as shown below:


=== approvalDate
type: string


=== approved
type: boolean


=== description
description: Description of the Service Level Agreement (SLA)

type: string


=== href
description: Reference of the Service Level Agreement (SLA)

type: string


=== id
description: Unique identifier of the Service Level Agreement (SLA)

type: string


=== name
description: Name of the Service Level Agreement (SLA)

type: string


=== state
description: State of the Service Level Agreement (SLA)

type: string


=== validFor
description: Period where the clauses of the SLA are applicable

$ref of: xref:v4.1@schemas:Tmf:TimePeriod.adoc[]


=== version
description: Version of the Service Level Agreement (SLA)

type: string


=== rule
type: array


=== relatedParty
type: array


=== template
$ref of: xref:v4.1@schemas:Tmf:TemplateRef.adoc[]


= All Of 
This schema extends: xref:v4.1@schemas:Tmf:Entity.adoc[]
