= SLARef

[#domain]
== Domain

This schema is part of EngagedParty

[#description]
== Description
ServiceLevelAgreement reference: A service level agreement (SLA) is a type of agreement that represents a formal negotiated agreement between two parties designed to create a common understanding about products, services, priorities, responsibilities, and so forth. The SLA is a set of appropriate procedures and targets formally or informally agreed between parties in order to achieve and maintain specified Quality of Service.


[#data_model]
== Data model

A JSON Schema corresponding to this data model can be found //[here].

== Diagram:
aaa

The data model is defined as shown below:


=== href
description: Reference of the service level agreement

type: string


=== id
description: Unique identifier of service level agreement

type: string


=== name
description: Name of the service level agreement

type: string


=== @referredType
description: The actual type of the target instance when needed for disambiguation.

type: string


[#all_of]
== All Of

This schema extends: xref:v4.2@schemas:Tmf:Entity.adoc[]
