= SpecificationCharacteristic

[#domain]
== Domain

This schema is part of Common

[#description]
== Description
A characteristic quality or distinctive feature of a Specification.  The characteristic can be take on a discrete value, such as color, can take on a range of values, (for example, sensitivity of 100-240 mV), or can be derived from a formula (for example, usage time (hrs) = 30 - talk time *3). Certain characteristics, such as color, may be configured during the ordering or some other process.


[#data_model]
== Data model

A JSON Schema corresponding to this data model can be found //[here].

THE DIAGRAM WILL BE IN HERE !!!


The data model is defined as shown below:


=== configurable
description: If true, the Boolean indicates that the SpecificationCharacteristic is configurable

type: boolean


=== description
description: A narrative that explains in detail what the SpecificationCharacteristic is

type: string


=== name
description: Name of the SpecificationCharacteristic

type: string


=== validFor
description: The period for which the productSpecificationCharacteristic is valid

$ref of: xref:v4.1@schemas:Tmf:TimePeriod.adoc[]


=== valueType
description: A kind of value that the characteristic can take on, such as numeric, text and so forth

type: string


=== specCharacteristicValue
description: The value or values that this characteristic can take on

type: array


=== specCharRelationship
description: Relationship to other characteristics, such as dependency (the value that this characteristic can take may be limited by the value of the related characteristic)

type: array


[#all_of]
== All Of

This schema extends: xref:v4.1@schemas:Tmf:Entity.adoc[]
