= StreetSegment

[#domain]
== Domain

This schema is part of Common

[#description]
== Description
StreetSegment corresponds to a part of a street referenced by a number or a set of number. Sometimes a suffix is added.


[#data_model]
== Data model

A JSON Schema corresponding to this data model can be found //[here].

THE DIAGRAM WILL BE IN HERE !!!
aaa

The data model is defined as shown below:


=== id
description: Unique identifier of the Street Segment

type: string


=== number
description: number identifying a specific property on a public street. It may be combined with streetNrLast for ranged addresses

type: string


=== numberLast
description: the last number in a range of street numbers allocated to a property

type: string


=== numberLastSuffix
description: the last street number suffix for a ranged address

type: string


=== numberSuffix
description: the first street number suffix

type: string


=== address
$ref of: xref:v4.1@schemas:Tmf:AddressRef.adoc[]


[#all_of]
== All Of

This schema extends: xref:v4.1@schemas:Tmf:Entity.adoc[]
