= SubAddress

[#domain]
== Domain

This schema is part of Common

[#description]
== Description
Representation of a SubAddress 
It is used for addressing within a property in an urban area (country properties are often defined differently). It may refer to a building, a building cluster, or a floor of a multistory building.


[#data_model]
== Data model

A JSON Schema corresponding to this data model can be found //[here].



The data model is defined as shown below:


=== buildingName
description: Allows for buildings that have well-known names

type: string


=== href
type: string


=== id
description: Unique ID for this SubAddress

type: string


=== levelNumber
description: Used where a level type may be repeated e.g. BASEMENT 1, BASEMENT 2

type: string


=== levelType
description: Describes level types within a building

type: string


=== name
description: Name of the subAddress to identify it with a meaningful identification

type: string


=== privateStreetName
description: Private streets internal to a property (e.g. a university) may have internal names that are not recorded by the land title office.

type: string


=== privateStreetNumber
description: Private streets numbers internal to a private street

type: string


=== subUnitNumber
description: The discriminator of the subunit, often just a simple number e.g. FLAT 5, may also be a range

type: string


=== subUnitType
description: The type of subunit, such as BERTH, FLAT, PIER, SUITE, SHOP, TOWER, UNIT, WHARF

type: string


=== subAddressType
description: The type of subaddress : it can be a subunit or a private street

type: string


[#all_of]
== All Of

This schema extends: xref:v4.2@schemas:Tmf:Entity.adoc[]
