= TaxDefinition

[#domain]
== Domain

This schema is part of Common

[#description]
== Description

Reference of a tax definition. A tax is levied by an authorized tax jurisdiction. There are many different types of tax (Federal Tax levied by the US Government, State Tax levied by the State of California,…).


[#data_model]
== Data model

A JSON Schema corresponding to this data model can be found https://tmforum.org[here].

The data model is defined as shown below:


=== id
description: Unique identifier of the tax.

type: string


=== name
description: Tax name.

type: string


=== validFor
description: The period of time for which the tax applies, might be set for example if it is known that the jurisdiction will cease to apply the tax after a certain date.

$ref of: xref:v4.0@schemas:Tmf:TimePeriod.adoc[]


=== jurisdictionName
description: Name of the jurisdiction that levies the tax

type: string


=== jurisdictionLevel
description: Level of the jurisdiction that levies the tax

type: string


=== taxType
description: Type of the tax.

type: string


= All Of 
This schema extends: xref:v4.0@schemas:Tmf:Extensible.adoc[]
