= TaxExemptionCertificate

[#domain]
== Domain

This schema is part of EngagedParty

[#description]
== Description

A tax exemption certificate represents a tax exemption granted to a party (individual or organization) by a tax jurisdiction which may be a city, state, country,... An exemption has a certificate identifier (received from the jurisdiction that levied the tax) and a validity period. An exemption is per tax types and determines for each type of tax what portion of the tax is exempted (partial by percentage or complete) via the tax definition.


[#data_model]
== Data model

A JSON Schema corresponding to this data model can be found https://tmforum.org[here].

The data model is defined as shown below:


=== id
description: Identifier of the tax exemption within list of the exemptions

type: string


=== taxDefinition
description: A list of taxes that are covered by the exemption, e.g. City Tax, State Tax. The definition would include the exemption (e.g. for a rate exemption 0% would be a full exemption, 5% could be a partial exemption if the actual rate was 10%).

type: array


=== validFor
description: The period of time for which the exemption is valid

$ref of: xref:4.0.0@schemas:Tmf:TimePeriod.adoc[]


=== certificateNumber
description: Identifier of a document that shows proof of exemption from taxes for the taxing jurisdiction

type: string


=== issuingJurisdiction
description: Name of the jurisdiction that issued the exemption

type: string


=== reason
description: Reason for the tax exemption

type: string


=== attachment
description: The actual certificate contents, if such is supplied by the issuing jurisdiction

$ref of: xref:4.0.0@schemas:Tmf:AttachmentRefOrValue.adoc[]


{&#x27;$ref&#x27;: &#x27;../Common/Extensible.schema.json#Extensible&#x27;}