= TestMeasureDefinition

[#domain]
== Domain

This schema is part of Service

[#description]
== Description
A TestMeasureDefinition specifies a measure of a specific aspect of a product, service, or resource test, such as lost packets or connectivity status


[#data_model]
== Data model

A JSON Schema corresponding to this data model can be found //[here].

THE DIAGRAM WILL BE IN HERE !!!
aaa

The data model is defined as shown below:


=== captureFrequency
description: The frequency of capture for the metric. Note: This may be replaced by a set of entities similar to the Performance Monitoring

type: string


=== captureMethod
description: The method used to capture the Metric. Note: This may be replaced by a set of entities similar to the Performance Monitoring

type: string


=== capturePeriod
description: A period of the capture

$ref of: xref:v4.0@schemas:Tmf:Duration.adoc[]


=== metricDescription
description: Brief description of the metric

type: string


=== metricHref
description: Hyperlink to access a metric for detail information

type: string


=== metricName
description: The name of a metric that in the test measure

type: string


=== name
description: The name of the TestMeasureDefinition

type: string


=== unitOfMeasure
description: Name of a service test specification

type: string


=== validFor
description: The time period for which this definition is valid

$ref of: xref:v4.0@schemas:Tmf:TimePeriod.adoc[]


=== valueType
description: A kind of value that the Metric value can take on, such as numeric, text, and so forth

type: string


=== thresholdRule
description: The rule(s) associated with the measure threshold

type: array


[#all_of]
== All Of

This schema extends: xref:v4.0@schemas:Tmf:Extensible.adoc[]
