= ThresholdRule

[#domain]
== Domain

This schema is part of Common

[#description]
== Description
ThresholdRule A base entity for concrete definition of thresholds.This datatype  is  abstract


[#data_model]
== Data model

A JSON Schema corresponding to this data model can be found //[here].

The data model is defined as shown below:


=== measurement
$ref of: xref:v4.1@schemas:Tmf:Measurement.adoc[]


=== consequence
description: A threshold crossing or a threshold ceased to be crossing results in a Performance consequence.

type: array


=== perfAlarmSpecThresholdCrossingDescription
description: A specific description of the threshold crossing (intended to be populated e under the alarm under CrossedThreshold structure).

type: string


=== performanceAlarmSpecification
$ref of: xref:v4.1@schemas:Tmf:PerformanceAlarmSpecification.adoc[]


=== thresholdRuleCondition
description: A concrete threshold may have two possible values: \&quot;Raise\&quot; - a threshold was crossed or \&quot;Clear\&quot; - a threshold ceased crossing

type: string


=== thresholdRuleName
description: A word, term, or phrase by which a Performance threshold rule is known and distinguished from other threshold rules

type: string


=== thresholdRuleSeverity
description: A threshold can be generated in different severity levels. A crossing for each level may require a different condition and possibly trigger a different consequence. The supported severity levels are equivalent to the possible severity level of alarms.

type: string


[#all_of]
== All Of

This schema extends: xref:v4.1@schemas:Tmf:Rule.adoc[]
