= Threshold

[#domain]
== Domain

This schema is part of Common

[#description]
== Description
A threshold base entity containing threshold rules.This entity  is  mandatoryThis entity  is  extendableThis entity   does not generate Object Creation notifications (NA)This entity   generates Object Deletion notificationsThis entity   does not generate Object Discovery notifications (NA)This entity supports the Common Get Operation.This entity supports the Common Get Multiple Operation.This entity supports the Common Create Operation.This entity supports the Common Delete Operation.


[#data_model]
== Data model

A JSON Schema corresponding to this data model can be found //[here].

The data model is defined as shown below:


=== description
description: A description of the threshold

type: string


=== name
description: A word, term, or phrase by which a Performance threshold is known and distinguished from other thresholds.

type: string


=== thresholdRule
description: A Performance Threshold contains a set of Performance threshold rules of different conditions (Raise, Clear) and different severities

type: array


[#all_of]
== All Of

This schema extends: xref:v4.0@schemas:Tmf:Entity.adoc[]
