= Ticket

[#domain]
== Domain

This schema is part of Common

[#description]
== Description

A trouble ticket represents a record used for reporting and managing the resolution of resource problems


[#data_model]
== Data model

A JSON Schema corresponding to this data model can be found https://tmforum.org[here].

The data model is defined as shown below:


=== correlationId
description: Additional identifier coming from an external system

type: string


=== creationDate
description: The date on which the trouble was discovered

type: string


=== description
description: Description of the trouble

type: string


=== href
description: Reference of the trouble ticket

type: string


=== id
description: Unique identifier of the trouble ticket

type: string


=== resolutionDate
description: The date on which the service was brought back to its original condition

type: string


=== severity
description: The severity of the trouble. It can be for example : minor, major, critical

type: string


=== status
description: The current status of the Trouble Ticket

type: string


=== statusChangeDate
description: The date of state change

type: string


=== statusChangeReason
description: The reason of state change

type: string


=== subStatus
description: The current sub status of the Trouble Ticket

type: string


=== targetResolutionDate
description: Foreseen trouble resolution date

type: string


=== ticketType
description: Type of trouble ticket

type: string


=== relatedObject
description: Any object(s) associated with this trouble ticket

type: array


=== note
description: Any note(s) associated with this trouble ticket

type: array


=== relatedParty
description: Any Party/Parties associated with this trouble ticket

type: array


= All Of 
