= TopologyQueryJob

[#domain]
== Domain

This schema is part of Common

[#description]
== Description
Represents a task used to query topology in the service


[#data_model]
== Data model

A JSON Schema corresponding to this data model can be found //[here].

Diagram:
aaa

The data model is defined as shown below:


=== completionDate
description: Date at which the job was completed

type: string


=== creationDate
description: Date at which the job was created

type: string


=== status
description: Status of the topolology query job

$ref of: xref:v4.0@schemas:Tmf:TaskStateType.adoc[]


=== graphSource
description: The topology graph to be queried

$ref of: xref:v4.0@schemas:Tmf:GraphRef.adoc[]


=== query
description: Implementation specific query language

type: string


=== graphTemplate
description: Attributes of the created Graph


=== graphResult
description: The topology graph(s) created by the query

type: array


=== vertexResult
description: The vertices result of the query

type: array


[#all_of]
== All Of

This schema extends: xref:v4.0@schemas:Tmf:Entity.adoc[]
