= TopupBalance

[#domain]
== Domain

This schema is part of Customer

[#description]
== Description

Represents a detailed description of a recharge operation requested over a bucket (defined by a specific product or reference to a product (i.e.: a commercial id such as an msisidn) and a service type)


[#data_model]
== Data model

A JSON Schema corresponding to this data model can be found https://tmforum.org[here].

The data model is defined as shown below:


=== relatedTopupBalance
$ref of: xref:v4.1@schemas:Tmf:RelatedTopupBalance.adoc[]


=== isAutoTopup
description: Indicates if the topup requested is an autotopup (to be processed periodically)

type: boolean


=== numberOfPeriods
description: For autotopup indicates the number of occurrences of the period the recharge operation must be executed. If not included then no limit is set to stop the execution of the topup every period

type: integer


=== recurringPeriod
description: For autotopup indicates the periodicity for the recharge operation (monthly, weekly, )

type: string


=== paymentMethod
description: Payment method used for the recharge operation (e.g.: cash, credit card). Structure including at least attribute dname. Notice that the use of a voucher can be managed as a specific methodtype, where he voucher code can be passed as value.

$ref of: xref:v4.1@schemas:Tmf:PaymentMethodRef.adoc[]


=== payment
$ref of: xref:v4.1@schemas:Tmf:PaymentRef.adoc[]


=== voucher
description: Identifier for a voucher when the topup can be performed by this means

type: string


= All Of 
This schema extends: xref:v4.1@schemas:Tmf:BalanceAction.adoc[]
