= UsageVolumeProduct

[#domain]
== Domain

This schema is part of Product

[#description]
== Description
A bucket (called UsageVolumeProduct in the SID model) represents a quantity of usage, as 2 hours national calls or 50 sms for example. It could be either a quantity or an amount in a currency (i.e. It could represent a fixed number of SMS, MMS, minutes of calls, quantity of data, number of events as well as a specific amount in a given currency). It requires one or more network products from which usages will debit the bucket.


[#data_model]
== Data model

A JSON Schema corresponding to this data model can be found //[here].

THE DIAGRAM WILL BE IN HERE !!!
aaa

The data model is defined as shown below:


=== bucketBalance
type: array


=== bucketCounter
type: array


=== id
description: Unique identifier of the bucket

type: string


=== isShared
description: True if the bucket is shared between several devices or users

type: boolean


=== name
description: Bucket name

type: string


=== product
type: array


=== usageType
description: Type of usage concerned by the bucket, such as voice, sms, data

type: string


[#all_of]
== All Of

This schema extends: xref:v4.2@schemas:Tmf:Entity.adoc[]
