= UsageConsumptionReport

[#domain]
== Domain

This schema is part of Product

[#description]
== Description
An usage consumption report enables to know at a given point the balances and the consumption counters related to various buckets (SMS, Voice, Data for example). It could be calculated for a device identified by a public key (msisdn number for a mobile device for example or PSTN or VOIP number for a fix device), for a subscribed offer or option or for an user.


[#data_model]
== Data model

A JSON Schema corresponding to this data model can be found //[here].



The data model is defined as shown below:


=== bucket
description: Bucket(s) included in the offer or option subscribed.

type: array


=== description
description: Free short text describing the usage consumption report content

type: string


=== effectiveDate
description: Date and time when the usage consumption report was calculated and generated

type: string


=== name
description: Usage consumption report name

type: string


=== relatedParty
$ref of: xref:v4.2@schemas:Tmf:RelatedParty.adoc[]


[#all_of]
== All Of

This schema extends: xref:v4.2@schemas:Tmf:Extensible.adoc[]
