= UsageConsumption

[#domain]
== Domain

This schema is part of Product

[#description]
== Description

An usage consumption enables to know at a given point the balances and the consumption counters related to various buckets (SMS, Voice, Data for example). It could be calculated for a device identified by a public key (msisdn number for a mobile device for example or PSTN or VOIP number for a fix device), for a subscribed offer or option or for an user.


[#data_model]
== Data model

A JSON Schema corresponding to this data model can be found https://tmforum.org[here].

The data model is defined as shown below:


=== name
description: Usage consumption name

type: string


=== description
description: Free short text describing the usage consumption content

type: string


=== creationDate
description: Date and time of the request creation

type: string


=== lastUpdate
description: Date when the status was last changed

type: string


=== state
description: State of the report report defined in the state engine

$ref of: xref:4.0.0@schemas:Tmf:TaskStateType.adoc[]


=== validPeriod
description: Validity period

$ref of: xref:4.0.0@schemas:Tmf:TimePeriod.adoc[]


=== relatedParty
description: Reference and role of the related parties for which the usage consumption is requested

type: array


=== partyAccount
description: A reference to the account that owns the bucket

type: array


=== bucketRefOrValue
description: Bucket(s) included in the offer or option subscribed.

type: array


=== product
type: array


=== service
type: array


=== logicalResource
type: array


= All Of 
