= Usage

[#domain]
== Domain

This schema is part of Product

[#description]
== Description

An occurrence of employing a Product, Service, or Resource for its intended purpose, which is of interest to the business and can have charges applied to it. It is comprised of characteristics, which represent attributes of usage.

None

[#data_model]
== Data model

A JSON Schema corresponding to this data model can be found https://tmforum.org[here].

The data model is defined as shown below:


=== usageDate
description: Date of usage

type: string


=== description
description: Description of usage

type: string


=== status
$ref of: xref:v4.1@schemas:Tmf:UsageStatusType.adoc[]


=== usageType
description: Type of usage

type: string


=== usageSpecification
$ref of: xref:v4.1@schemas:Tmf:UsageSpecificationRef.adoc[]


=== usageCharacteristic
type: array


=== relatedParty
type: array


=== ratedProductUsage
type: array


[#all_of]
== All Of

This schema extends: xref:v4.1@schemas:Tmf:Entity.adoc[]
