= UsageConsumptionReportRequest

[#domain]
== Domain

This schema is part of Product

[#description]
== Description
An UsageConsumptionReportRequest allows to manage the calculation request of an usage consumption report


[#data_model]
== Data model

A JSON Schema corresponding to this data model can be found //[here].

Diagram:


The data model is defined as shown below:


=== bucket
description: Reference of the buckets for which the usage consumption report is requested

type: array


=== creationDate
description: Date and time of the request creation

type: string


=== href
description: Reference of the usage consumption report request

type: string


=== id
description: Unique identifier of the usage consumption report request given by the server

type: string


=== lastUpdate
description: Date when the status was last changed

type: string


=== product
description: Network product reference for which the usage consumption report is requested

$ref of: xref:v4.2@schemas:Tmf:NetworkProductRef.adoc[]


=== relatedParty
description: Reference and role of the related parties for which the usage consumption report is requested

type: array


=== status
description: Status of the usage consumption report request (InProgress or done)

type: string


=== usageConsumptionReport
description: References of the usage consumption report (given when it has been calculated and the status of the request is done)

$ref of: xref:v4.2@schemas:Tmf:UsageConsumptionReportRef.adoc[]


=== validPeriod
description: Validity period

$ref of: xref:v4.2@schemas:Tmf:TimePeriod.adoc[]


[#all_of]
== All Of

