= UserAsset

[#domain]
== Domain

This schema is part of Common

[#description]
== Description

No description on schema


[#data_model]
== Data model

A JSON Schema corresponding to this data model can be found https://tmforum.org[here].

The data model is defined as shown below:


=== assetType
description: Second level to define the type of managed element for product/service/resource managed entities (e.g.: mobile line subscription, video platform license, mobile equipment, etc). Allows identifying the specific asset within the server referenced. Supported values are implementation and application specific. Other values can be added if those listed are not enough

type: string


=== entitlement
description: information about individual entitlements to define access levels to operate over different functions that can be defined in an asset

type: array


=== entityType
description: Type of managed entity (e.g.: product, resource, service, customer, account)

type: string


=== id
description: Unique identifier of referenced entity within the entity/asset pair (customerId, accountId, mobile line number, ...)

type: string


=== role
description: Represents the part played by an individual in relation to being granted a set of entitlements for manageable assets (e.g.: owner, user, viewer, ...)

type: string


[#all_of]
== All Of

This schema extends: xref:v4.2@schemas:Tmf:Entity.adoc[]
