= VertexSpecificationCharacteristic

[#domain]
== Domain

This schema is part of Common

[#description]
== Description

This class defines the characteristic features of a vertex specification. Every VertexSpecification has a variety of important attributes, methods, constraints, and relationships, which distinguish a vertex specification from other vertex specifications.


[#data_model]
== Data model

A JSON Schema corresponding to this data model can be found https://tmforum.org[here].

The data model is defined as shown below:


=== vertexSpecCharRelationship
description: An aggregation, migration, substitution, dependency or exclusivity relationship between/among Specification Characteristics.

type: array


=== vertexSpecCharacteristicValue
description: A CharacteristicValueSpecification object is used to define a set of attributes, each of which can be assigned to a corresponding set of attributes in a VertexSpecificationCharacteristic object. The values of the attributes in the CharacteristicValueSpecification object describe the values of the attributes that a corresponding VertexSpecificationCharacteristic object can take on.

type: array


[#all_of]
== All Of

This schema extends: xref:v4.1@schemas:Tmf:CharacteristicSpecificationBase.adoc[]
