= Warranty

[#domain]
== Domain

This schema is part of Product

[#description]
== Description
No description on schema


[#data_model]
== Data model

A JSON Schema corresponding to this data model can be found //[here].



The data model is defined as shown below:


=== appliesToProduct
type: array


=== appliesToResource
type: array


=== description
description: free-text description of the entity

type: string


=== endDate
description: A date time( DateTime). The date till the entity is effective

type: string


=== place
type: array


=== startDate
description: A date time( DateTime). The date from which the entity is effective

type: string


=== state
$ref of: xref:v4.0@schemas:Tmf:WarrantyStateType.adoc[]


=== statusChangeDate
description: A date time( DateTime). The date that the entity status changed

type: string


=== validFor
$ref of: xref:v4.0@schemas:Tmf:TimePeriod.adoc[]


=== warranty
type: array


=== warrantyAgreement
type: array


=== warrantyRelationship
type: array


=== warrantySpecification
$ref of: xref:v4.0@schemas:Tmf:WarrantySpecificationRef.adoc[]


[#all_of]
== All Of

This schema extends: xref:v4.0@schemas:Tmf:MEntity.adoc[]
