= WorkPrice

[#domain]
== Domain

This schema is part of EngagedParty

[#description]
== Description
An amount, usually of money, that represents the actual price paid by the Customer for this item or this order.


[#data_model]
== Data model

A JSON Schema corresponding to this data model can be found //[here].

Diagram:


The data model is defined as shown below:


=== billingAccount
$ref of: xref:v4.1@schemas:Tmf:BillingAccountRef.adoc[]


=== description
description: A narrative that explains in detail the semantics of this shipment price.

type: string


=== name
description: A short descriptive name such as &quot;Subscription price&quot;.

type: string


=== price
$ref of: xref:v4.1@schemas:Tmf:Price.adoc[]


=== priceAlteration
type: array


=== priceType
$ref of: xref:v4.1@schemas:Tmf:PriceType.adoc[]


=== productOfferingPrice
$ref of: xref:v4.1@schemas:Tmf:ProductOfferingPriceRef.adoc[]


=== recurringChargePeriod
description: Could be month, week...

type: string


=== unitOfMeasure
description: Could be minutes, GB...

type: string


[#all_of]
== All Of

This schema extends: xref:v4.1@schemas:Tmf:Entity.adoc[]
