= WorkOrder

[#domain]
== Domain

This schema is part of EngagedParty

[#description]
== Description

No description on schema


[#data_model]
== Data model

A JSON Schema corresponding to this data model can be found https://tmforum.org[here].

The data model is defined as shown below:


=== agreement
description: A reference to an agreement defined in the context of the work order

type: array


=== appointment
$ref of: xref:v4.1@schemas:Tmf:AppointmentRef.adoc[]


=== billingAccount
$ref of: xref:v4.1@schemas:Tmf:BillingAccountRef.adoc[]


=== cancellationDate
description: Date when the order is cancelled. This is used when order is cancelled. 

type: string


=== cancellationReason
description: Reason why the order is cancelled. This is used when order is cancelled. 

type: string


=== category
description: Used to categorize the order from a business perspective that can be useful for the OM system (e.g. &quot;enterprise&quot;, &quot;residential&quot;, ...)

type: string


=== channel
type: array


=== completionDate
description: Date when the order was completed

type: string


=== description
description: A free-text description of the order

type: string


=== expectedCompletionDate
description: Expected completion date amended by the provider

type: string


=== externalId
description: ID given by the consumer to facilitate searches

type: string


=== href
description: Hyperlink to access the order

type: string


=== id
description: ID created on repository side

type: string


=== note
$ref of: xref:v4.1@schemas:Tmf:Note.adoc[]


=== notificationContact
description: Contact attached to the order to send back information regarding this order

type: string


=== order
type: array


=== orderDate
description: Date when the order was created

type: string


=== orderTotalPrice
type: array


=== payment
type: array


=== place
$ref of: xref:v4.1@schemas:Tmf:PlaceRefOrValue.adoc[]


=== priority
description: A way that can be used by consumers to prioritize orders in OM system (from 0 to 4 : 0 is the highest priority, and 4 the lowest)

type: string


=== quote
type: array


=== relatedEntity
type: array


=== relatedParty
type: array


=== requestedCompletionDate
description: Requested completion date from the requestors perspective

type: string


=== requestedStartDate
description: Order fulfillment start date wished by the requestor. This is used when, for any reason, requestor cannot allow provider to begin to operationally begin the fulfillment before a date.

type: string


=== startDate
description: Date when the order started

type: string


=== state
$ref of: xref:v4.1@schemas:Tmf:WorkOrderStateType.adoc[]


=== stateChangeDate
description: Last change date of the order state.

type: string


=== version
description: The version number allows for the tracking of multiple evolution steps during the lifecycle of the entity.
It can be correlated to the revision number related to the lifecycle management change of the entity.

type: string


=== workOrderItem
type: array


=== workOrderRelationship
type: array


= All Of 
This schema extends: xref:v4.1@schemas:Tmf:Entity.adoc[]
