@startuml
hide circle
hide methods
hide stereotype
show <<Enumeration>> stereotype
skinparam class {
   BackgroundColor<<Enumeration>> #E6F5F7
   BackgroundColor<<Ref>> #FFFFE0
   BackgroundColor<<Pivot>> #FFFFFFF
   BackgroundColor<<SimpleType>> #E2F0DA
   BackgroundColor #FCF2E3
}

class BankCardDetails <<Pivot>> {
    bank : String
    brand : String
    cardNumber : String
    cardType : String
    cvv : String
    expirationDate : DateTime
    href : Uri
    id : String
    lastFourDigits : String
    nameOnCard : String
    @baseType : String
    @schemaLocation : Uri
    @type : String
}


@enduml