@startuml
hide circle
hide methods
hide stereotype
show <<Enumeration>> stereotype
skinparam class {
   BackgroundColor<<Enumeration>> #E6F5F7
   BackgroundColor<<Ref>> #FFFFE0
   BackgroundColor<<Pivot>> #FFFFFFF
   BackgroundColor<<SimpleType>> #E2F0DA
   BackgroundColor #FCF2E3
}

class ConnectionSpecification <<Pivot>> {
    associationType : String [1]
    href : Uri
    id : String
    name : String
    @baseType : String
    @schemaLocation : Uri
    @type : String
}

class EndpointSpecificationRef  <<Ref>> {
    href : Uri
    id : String [1]
    isRoot : Boolean
    name : String
    role : String
    @baseType : String
    @referredType : String
    @schemaLocation : Uri
    @type : String
}

class ConnectionPointSpecificationRef  <<Ref>> {
    href : Uri
    id : String [1]
    name : String
    version : String
    @baseType : String
    @referredType : String
    @schemaLocation : Uri
    @type : String
}

ConnectionSpecification *-->  "1..*" EndpointSpecificationRef : endpointSpecification

EndpointSpecificationRef *-->  "0..1" ConnectionPointSpecificationRef : connectionPointSpecification

@enduml