@startuml
hide circle
hide methods
hide stereotype
show <<Enumeration>> stereotype
skinparam class {
   BackgroundColor<<Enumeration>> #E6F5F7
   BackgroundColor<<Ref>> #FFFFE0
   BackgroundColor<<Pivot>> #FFFFFFF
   BackgroundColor<<SimpleType>> #E2F0DA
   BackgroundColor #FCF2E3
}

class ShipmentSpecification <<Pivot>> {
    description : String
    href : Uri
    id : String
    isBundle : Boolean
    lastUpdate : DateTime
    lifecycleStatus : String
    name : String
    validFor : TimePeriod
    version : String
    @baseType : String
    @schemaLocation : Uri
    @type : String
}

class ShipmentSpecificationRelationship  <<Ref>> {
    href : Uri
    id : String
    name : String
    relationshipType : String [1]
    role : String
    validFor : TimePeriod
    @baseType : String
    @schemaLocation : Uri
    @type : String
}

class AssociationSpecificationRef  <<Ref>> {
    href : Uri
    id : String [1]
    name : String
    @baseType : String
    @referredType : String
    @schemaLocation : Uri
    @type : String
}

class RelatedParty  {
    href : Uri
    id : String [1]
    name : String
    role : String
    @baseType : String
    @referredType : String [1]
    @schemaLocation : Uri
    @type : String
}

class CharacteristicSpecification  {
    configurable : Boolean
    description : String
    extensible : Boolean
    id : String
    isUnique : Boolean
    maxCardinality : Integer
    minCardinality : Integer
    name : String
    regex : String
    validFor : TimePeriod
    valueType : String
    @baseType : String
    @schemaLocation : Uri
    @type : String
    @valueSchemaLocation : String
}

class CharacteristicSpecificationRelationship  {
    characteristicSpecificationId : String
    name : String
    parentSpecificationHref : Uri
    parentSpecificationId : String
    relationshipType : String
    validFor : TimePeriod
    @baseType : String
    @schemaLocation : Uri
    @type : String
}

class CharacteristicValueSpecification  {
    isDefault : Boolean
    rangeInterval : String
    regex : String
    unitOfMeasure : String
    validFor : TimePeriod
    value : Any
    valueFrom : Integer
    valueTo : Integer
    valueType : String
    @baseType : String
    @schemaLocation : Uri
    @type : String
}

class AttachmentRefOrValue  {
    attachmentType : String
    content : string/base64
    description : String
    href : Uri
    id : String
    mimeType : String
    name : String
    size : Quantity
    url : Uri
    validFor : TimePeriod
    @baseType : String
    @referredType : String
    @schemaLocation : Uri
    @type : String
}

class TargetShipmentSchema  {
    @schemaLocation : String [1]
    @type : String [1]
}

class ConstraintRef  <<Ref>> {
    href : Uri
    id : String [1]
    name : String
    version : String
    @baseType : String
    @referredType : String
    @schemaLocation : Uri
    @type : String
}

AttachmentRefOrValue "0..*" <-left-* ShipmentSpecification : attachment

ShipmentSpecification *-right-> "0..*" ConstraintRef : constraint

RelatedParty "0..*" <--* ShipmentSpecification : relatedParty

TargetShipmentSchema "0..1" <--* ShipmentSpecification : targetShipmentSchema

ShipmentSpecification *-->  "0..*" ShipmentSpecificationRelationship : shipmentSpecRelationship

ShipmentSpecification *-->  "0..*" CharacteristicSpecification : shipmentSpecificationCharacteristic

CharacteristicSpecification *-->  "0..*" CharacteristicSpecificationRelationship : charSpecRelationship

CharacteristicSpecification *-->  "0..*" CharacteristicValueSpecification : characteristicValueSpecification

ShipmentSpecificationRelationship *-->  "0..1" AssociationSpecificationRef : associationSpec

@enduml