@startuml
hide circle
hide methods
hide stereotype
show <<Enumeration>> stereotype
skinparam class {
   BackgroundColor<<Enumeration>> #E6F5F7
   BackgroundColor<<Ref>> #FFFFE0
   BackgroundColor<<Pivot>> #FFFFFFF
   BackgroundColor<<SimpleType>> #E2F0DA
   BackgroundColor #FCF2E3
}

class SpecCharacteristic <<Pivot>> {
    configurable : Boolean
    description : String
    href : Uri
    id : String
    name : String
    validFor : TimePeriod
    valueType : String
    @baseType : String
    @schemaLocation : Uri
    @type : String
}

class SpecCharRelationship  <<Ref>> {
    href : String
    id : String
    name : String
    relationshipType : String
    validFor : TimePeriod
    @baseType : String
    @schemaLocation : Uri
    @type : String
}

class SpecCharacteristicValue  {
    href : Uri
    id : String
    isDefault : Boolean
    rangeInterval : String
    regex : String
    unitOfMeasure : String
    validFor : TimePeriod
    value : object
    valueFrom : Integer
    valueTo : Integer
    valueType : String
    @baseType : String
    @schemaLocation : Uri
    @type : String
}

SpecCharacteristic *-->  "0..*" SpecCharRelationship : specCharRelationship

SpecCharacteristic *-->  "0..*" SpecCharacteristicValue : specCharacteristicValue

@enduml