@startuml
hide circle
hide methods
hide stereotype
show <<Enumeration>> stereotype
skinparam class {
   BackgroundColor<<Enumeration>> #E6F5F7
   BackgroundColor<<Ref>> #FFFFE0
   BackgroundColor<<Pivot>> #FFFFFFF
   BackgroundColor<<SimpleType>> #E2F0DA
   BackgroundColor #FCF2E3
}

class NonFunctionalTestResult <<Pivot>> {
    href : Uri
    id : String
    @baseType : String
    @schemaLocation : Uri
    @type : String
}

class NonFunctionalTestResultDefinition  {
    attachmentType : String
    content : string/base64
    description : String
    href : Uri
    id : String
    mimeType : String
    name : String
    size : Quantity
    url : Uri
    validFor : TimePeriod
    @baseType : String
    @schemaLocation : Uri
    @type : String
}

class NonFunctionalTestExecutionRefOrValue  {
    dataCorrelationId : String
    href : Uri
    id : String
    name : String
    state : ExecutionStateType
    @baseType : String
    @referredType : String
    @schemaLocation : Uri
    @type : String
}

class GeneralTestArtifactRef  <<Ref>> {
    href : Uri
    id : String [1]
    name : String
    @baseType : String
    @referredType : String
    @schemaLocation : Uri
    @type : String
}

class NonFunctionalTestModelRef  <<Ref>> {
    href : Uri
    id : String [1]
    name : String
    @baseType : String
    @referredType : String
    @schemaLocation : Uri
    @type : String
}

class TestEnvironmentProvisioningExecution  {
    dataCorrelationId : String
    href : Uri
    id : String
    state : ExecutionStateType
    @baseType : String
    @schemaLocation : Uri
    @type : String
}

class ProvisioningArtifactRef  <<Ref>> {
    href : Uri
    id : String [1]
    name : String
    @baseType : String
    @referredType : String
    @schemaLocation : Uri
    @type : String
}

class TestEnvironmentAllocationExecution  {
    dataCorrelationId : String
    href : Uri
    id : String
    resourceManagerUrl : Uri [1]
    state : ExecutionStateType
    @baseType : String
    @schemaLocation : Uri
    @type : String
}

class AbstractEnvironmentRef  <<Ref>> {
    href : Uri
    id : String [1]
    name : String
    @baseType : String
    @referredType : String
    @schemaLocation : Uri
    @type : String
}

class ExecutionStateType <<Enumeration>> {
    acknowledged
    rejected
    pending
    inProgress
    cancelled
    completed
    failed
}

class TestScenarioRef  <<Ref>> {
    href : Uri
    id : String [1]
    name : String
    @baseType : String
    @referredType : String
    @schemaLocation : Uri
    @type : String
}

class ConcreteResourceMapping  {
    abstractResource : String
    href : Uri
    id : String
    @baseType : String
    @schemaLocation : Uri
    @type : String
}

class ConcreteResource  {
    href : Uri
    id : String
    name : String [1]
    @baseType : String
    @schemaLocation : Uri
    @type : String
}

class TestDataInstanceRef  <<Ref>> {
    href : Uri
    id : String [1]
    name : String
    @baseType : String
    @referredType : String
    @schemaLocation : Uri
    @type : String
}

NonFunctionalTestResult *-->  "1" NonFunctionalTestExecutionRefOrValue : testExecution

NonFunctionalTestExecutionRefOrValue -right[hidden]-> ExecutionStateType

NonFunctionalTestExecutionRefOrValue *-->  "0..*" GeneralTestArtifactRef : generalTestArtifact

NonFunctionalTestExecutionRefOrValue *-->  "1" TestEnvironmentProvisioningExecution : testEnvironmentProvisioningExecution

TestEnvironmentProvisioningExecution *-->  "1" TestEnvironmentAllocationExecution : testEnvironmentAllocationExecution

GeneralTestArtifactRef "0..*" <--* TestEnvironmentAllocationExecution : generalTestArtifact

TestEnvironmentProvisioningExecution *-right-> "0..*" GeneralTestArtifactRef : generalTestArtifact

TestDataInstanceRef "0..*" <-left-* NonFunctionalTestExecutionRefOrValue : testDataInstance

NonFunctionalTestModelRef "0..1" <--* NonFunctionalTestExecutionRefOrValue : nonFunctionalTestModel

TestScenarioRef "0..1" <-left-* TestEnvironmentAllocationExecution : testScenario

TestEnvironmentAllocationExecution *-right-> "0..1" AbstractEnvironmentRef : abstractEnvironment

TestEnvironmentAllocationExecution *-->  "0..*" ConcreteResourceMapping : concreteResourceMapping

ProvisioningArtifactRef "0..*" <-left-* TestEnvironmentProvisioningExecution : provisioningArtifact

NonFunctionalTestResult *-right-> "1" NonFunctionalTestResultDefinition : nonFunctionalTestResultDefinition

ConcreteResourceMapping *-->  "0..*" ConcreteResource : concreteResource

@enduml