@startuml
hide circle
hide methods
hide stereotype
show <<Enumeration>> stereotype
skinparam class {
   BackgroundColor<<Enumeration>> #E6F5F7
   BackgroundColor<<Ref>> #FFFFE0
   BackgroundColor<<Pivot>> #FFFFFFF
   BackgroundColor<<SimpleType>> #E2F0DA
   BackgroundColor #FCF2E3
}

class Customer360AppointmentVO <<Pivot>> {
    category : String
    creationDate : DateTime
    description : String
    externalId : String
    href : String
    id : String
    lastUpdate : DateTime
    status : AppointmentStateType
    validFor : TimePeriod [1]
    @baseType : String
    @schemaLocation : Uri
    @type : String
}

class CalendarEventRef  <<Ref>> {
    href : Uri
    id : String [1]
    name : String
    @baseType : String
    @referredType : String
    @schemaLocation : Uri
    @type : String
}

class AppointmentStateType <<Enumeration>> {
    initialized
    confirmed
    cancelled
    completed
    failed
}

Customer360AppointmentVO -right[hidden]-> AppointmentStateType

Customer360AppointmentVO *-->  "0..1" CalendarEventRef : calendarEvent

@enduml