@startuml
hide circle
hide methods
hide stereotype
show <<Enumeration>> stereotype
skinparam class {
   BackgroundColor<<Enumeration>> #E6F5F7
   BackgroundColor<<Ref>> #FFFFE0
   BackgroundColor<<Pivot>> #FFFFFFF
   BackgroundColor<<SimpleType>> #E2F0DA
   BackgroundColor #FCF2E3
}

class LocationCommons <<Pivot>> {
    areaServed : String
}

class Address  {
    city : String
    country : String
    href : Uri
    id : String
    locality : String
    postcode : String
    stateOrProvince : String
    streetName : String
    streetNr : String
    streetNrLast : String
    streetNrLastSuffix : String
    streetNrSuffix : String
    streetSuffix : String
    streetType : String
    @baseType : String
    @schemaLocation : Uri
    @type : String
}

class SubAddress  {
    buildingName : String
    href : String
    id : String
    levelNumber : String
    levelType : String
    name : String
    privateStreetName : String
    privateStreetNumber : String
    subAddressType : String
    subUnitNumber : String
    subUnitType : String
    @baseType : String
    @schemaLocation : Uri
    @type : String
}

class GeographicLocation  {
    href : String
    id : String
    name : String
    @baseType : String
    @schemaLocation : Uri
    @type : String [1]
}

LocationCommons *-right-> "0..1" Address : address

LocationCommons *-->  "0..1" GeographicLocation : location

Address *-->  "0..1" SubAddress : subAddress

@enduml