@startuml
hide circle
hide methods
hide stereotype
show <<Enumeration>> stereotype
skinparam class {
   BackgroundColor<<Enumeration>> #E6F5F7
   BackgroundColor<<Ref>> #FFFFE0
   BackgroundColor<<Pivot>> #FFFFFFF
   BackgroundColor<<SimpleType>> #E2F0DA
   BackgroundColor #FCF2E3
}

class ServiceOrderItemRelationship <<Pivot>> {
    relationshipType : String
    @baseType : String
    @schemaLocation : Uri
    @type : String
}

class ServiceOrderItemRef  {
    itemId : String
    serviceOrderHref : Uri
    serviceOrderId : String
    @baseType : String
    @referredType : String
    @schemaLocation : Uri
    @type : String
}

ServiceOrderItemRelationship *-->  "0..1" ServiceOrderItemRef : orderItem

@enduml