@startuml
hide circle
hide methods
hide stereotype
show <<Enumeration>> stereotype
skinparam class {
   BackgroundColor<<Enumeration>> #E6F5F7
   BackgroundColor<<Ref>> #FFFFE0
   BackgroundColor<<Pivot>> #FFFFFFF
   BackgroundColor<<SimpleType>> #E2F0DA
   BackgroundColor #FCF2E3
}

class OrderItem <<Pivot>> {
    action : String
    href : Uri
    id : String
    quantity : Integer
    state : String
    @baseType : String
    @schemaLocation : Uri
    @type : String
}

class Product  {
    description : String
    href : String
    id : String
    isBundle : Boolean
    isCustomerVisible : Boolean
    name : String
    orderDate : DateTime
    productSerialNumber : String
    startDate : DateTime
    status : ProductStatusType
    terminationDate : DateTime
    @baseType : String
    @schemaLocation : Uri
    @type : String
}

class ProductSpecificationRef  <<Ref>> {
    href : Uri
    id : String [1]
    name : String
    version : String
    @baseType : String
    @referredType : String
    @schemaLocation : Uri
    @type : String
}

class TargetProductSchema  {
    @schemaLocation : Uri [1]
    @type : String [1]
}

class Characteristic  {
    id : String
    name : String [1]
    value : Any [1]
    valueType : String
    @baseType : String
    @schemaLocation : Uri
    @type : String
}

class CharacteristicRelationship  <<Ref>> {
    href : Uri
    id : String
    relationshipType : String
    @baseType : String
    @schemaLocation : Uri
    @type : String
}

class BillingAccountRef  <<Ref>> {
    href : String
    id : String [1]
    name : String
    ratingType : String
    @baseType : String
    @referredType : String
    @schemaLocation : Uri
    @type : String
}

class RelatedProductOrderItem  {
    href : Uri
    id : String
    orderItemAction : String
    orderItemId : String [1]
    productOrderHref : String
    productOrderId : String [1]
    role : String
    @baseType : String
    @referredType : String
    @schemaLocation : Uri
    @type : String
}

class ServiceRef  <<Ref>> {
    href : Uri
    id : String [1]
    name : String
    @baseType : String
    @referredType : String
    @schemaLocation : Uri
    @type : String
}

class ResourceRef  <<Ref>> {
    href : Uri
    id : String [1]
    name : String
    @baseType : String
    @referredType : String
    @schemaLocation : Uri
    @type : String
}

class RelatedPlaceRefOrValue  {
    href : String
    id : String
    name : String
    role : String [1]
    @baseType : String
    @referredType : String
    @schemaLocation : Uri
    @type : String
}

class ProductRefOrValue  {
    description : String
    href : String
    id : String
    isBundle : Boolean
    isCustomerVisible : Boolean
    name : String
    orderDate : DateTime
    productSerialNumber : String
    startDate : DateTime
    status : ProductStatusType
    terminationDate : DateTime
    @baseType : String
    @referredType : String
    @schemaLocation : Uri
    @type : String
}

class AgreementItemRef  <<Ref>> {
    agreementItemId : String
    href : Uri
    id : String [1]
    name : String
    @baseType : String
    @referredType : String
    @schemaLocation : Uri
    @type : String
}

class ProductOfferingRef  <<Ref>> {
    href : Uri
    id : String [1]
    name : String
    @baseType : String
    @referredType : String
    @schemaLocation : Uri
    @type : String
}

class ProductTerm  {
    description : String
    duration : Quantity
    href : Uri
    id : String
    name : String
    validFor : TimePeriod
    @baseType : String
    @schemaLocation : Uri
    @type : String
}

class RelatedParty  {
    href : Uri
    id : String [1]
    name : String
    role : String
    @baseType : String
    @referredType : String [1]
    @schemaLocation : Uri
    @type : String
}

class ProductRelationship  <<Ref>> {
    href : Uri
    id : String
    relationshipType : String [1]
    @baseType : String
    @schemaLocation : Uri
    @type : String
}

class ProductPrice  {
    description : String
    href : Uri
    id : String
    name : String
    priceType : String [1]
    recurringChargePeriod : String
    unitOfMeasure : String
    @baseType : String
    @schemaLocation : Uri
    @type : String
}

class ProductOfferingPriceRef  <<Ref>> {
    href : Uri
    id : String [1]
    name : String
    @baseType : String
    @referredType : String
    @schemaLocation : Uri
    @type : String
}

class Price  {
    dutyFreeAmount : Money
    href : Uri
    id : String
    percentage : Float
    taxIncludedAmount : Money
    taxRate : Float
    @baseType : String
    @schemaLocation : Uri
    @type : String
}

class PriceAlteration  {
    applicationDuration : Integer
    description : String
    href : Uri
    id : String
    name : String
    priceType : String [1]
    priority : Integer
    recurringChargePeriod : String
    unitOfMeasure : String
    @baseType : String
    @schemaLocation : Uri
    @type : String
}

class ProductStatusType <<Enumeration>> {
    created
    pendingActive
    cancelled
    active
    pendingTerminate
    terminated
    suspended
    aborted
}

class OrderPrice  {
    description : String
    href : Uri
    id : String
    name : String
    priceType : String
    recurringChargePeriod : String
    unitOfMeasure : String
    @baseType : String
    @schemaLocation : Uri
    @type : String
}

class AppointmentRef  <<Ref>> {
    description : String
    href : String
    id : String [1]
    @baseType : String
    @referredType : String
    @schemaLocation : Uri
    @type : String
}

class OrderTerm  {
    description : String
    duration : Quantity
    href : Uri
    id : String
    name : String
    @baseType : String
    @schemaLocation : Uri
    @type : String
}

class QualificationRef  <<Ref>> {
    href : Uri
    id : String [1]
    name : String
    qualificationItemId : String
    @baseType : String
    @referredType : String
    @schemaLocation : Uri
    @type : String
}

class OrderItemRelationship  <<Ref>> {
    href : Uri
    id : String
    relationshipType : String
    @baseType : String
    @schemaLocation : Uri
    @type : String
}

class PaymentRef  <<Ref>> {
    href : Uri
    id : String [1]
    name : String
    @baseType : String
    @referredType : String
    @schemaLocation : Uri
    @type : String
}

OrderItem *-right-> "0..*" OrderItem : orderItem

OrderItem *-->  "0..1" ProductOfferingRef : productOffering

OrderItem *-->  "0..1" BillingAccountRef : billingAccount

OrderItem *-->  "0..*" OrderPrice : itemTotalPrice

OrderItem *-->  "0..*" OrderPrice : itemPrice

OrderItem *-->  "0..1" Product : product

Product *-->  "0..*" ProductPrice : productPrice

BillingAccountRef "0..1" <--* ProductPrice : billingAccount

Product *-->  "0..*" ProductRefOrValue : product

BillingAccountRef "0..1" <--* ProductRefOrValue : billingAccount

Product *-right-> "0..1" ProductOfferingRef : productOffering

BillingAccountRef "0..1" <-left-* Product : billingAccount

Product *-->  "0..*" AgreementItemRef : agreement

Product *-->  "0..*" ProductRelationship : productRelationship

Product *-->  "0..*" ProductTerm : productTerm

Product *-->  "0..*" RelatedParty : relatedParty

Product *-->  "0..*" RelatedPlaceRefOrValue : place

Product *-->  "0..*" RelatedProductOrderItem : productOrderItem

Product *-->  "0..*" ResourceRef : realizingResource

Product *-->  "0..*" ServiceRef : realizingService

ProductOfferingRef -right[hidden]-> ProductStatusType

Product *-->  "0..1" ProductSpecificationRef : productSpecification

ProductSpecificationRef -right[hidden]-> ProductPrice

Product *-->  "0..*" Characteristic : productCharacteristic

Characteristic -right[hidden]-> ProductSpecificationRef

ProductRefOrValue *-right-> "0..*" ProductRefOrValue : product

ProductRefOrValue *-->  "0..*" AgreementItemRef : agreement

ProductRefOrValue *-->  "0..*" ProductTerm : productTerm

ProductRefOrValue *-->  "0..*" RelatedParty : relatedParty

ProductRefOrValue *-->  "0..*" RelatedPlaceRefOrValue : place

ProductRefOrValue *-->  "0..*" RelatedProductOrderItem : productOrderItem

ProductRefOrValue *-->  "0..*" ResourceRef : realizingResource

ProductRefOrValue *-->  "0..*" ServiceRef : realizingService

ProductRefOrValue *-->  "0..*" Characteristic : productCharacteristic

ProductRefOrValue *-->  "0..1" ProductSpecificationRef : productSpecification

ProductOfferingRef "0..1" <--* ProductRefOrValue : productOffering

ProductPrice "0..*" <--* ProductRefOrValue : productPrice

ProductRelationship *-->  "1" ProductRefOrValue : product

ProductRelationship "0..*" <--* ProductRefOrValue : productRelationship

ProductPrice *-->  "1" Price : price

ProductRefOrValue <-left[hidden]- Price

ProductPrice *-->  "0..1" ProductOfferingPriceRef : productOfferingPrice

Price <-left[hidden]- ProductOfferingPriceRef

ProductPrice *-->  "0..*" PriceAlteration : productPriceAlteration

ProductOfferingPriceRef <-left[hidden]- PriceAlteration

ProductOfferingPriceRef "0..1" <--* PriceAlteration : productOfferingPrice

Price "1" <--* PriceAlteration : price

OrderPrice *-->  "0..*" PriceAlteration : priceAlteration

OrderPrice *-->  "0..1" ProductOfferingPriceRef : productOfferingPrice

OrderPrice *-->  "0..1" Price : price

BillingAccountRef "0..1" <--* OrderPrice : billingAccount

PaymentRef "0..*" <--* OrderItem : payment

OrderTerm "0..*" <--* OrderItem : itemTerm

AppointmentRef "0..1" <--* OrderItem : appointment

QualificationRef "0..*" <--* OrderItem : qualification

OrderItem *-->  "0..*" OrderItemRelationship : orderItemRelationship

ProductSpecificationRef *-->  "0..1" TargetProductSchema : targetProductSchema

Characteristic *-->  "0..*" CharacteristicRelationship : characteristicRelationship

@enduml