@startuml
hide circle
hide methods
hide stereotype
show <<Enumeration>> stereotype
skinparam class {
   BackgroundColor<<Enumeration>> #E6F5F7
   BackgroundColor<<Ref>> #FFFFE0
   BackgroundColor<<Pivot>> #FFFFFFF
   BackgroundColor<<SimpleType>> #E2F0DA
   BackgroundColor #FCF2E3
}

class ServiceLevelAgreementViolation <<Pivot>> {
    date : DateTime
    href : String
    id : Integer
}

class Violation  {
    actualValue : String
    comment : String
    consequence : String
    href : Uri
    id : String
    operator : String
    referenceValue : String
    tolerance : String
    unit : String
    violationAverage : String
    @baseType : String
    @schemaLocation : Uri
    @type : String
}

class RuleRef  <<Ref>> {
    href : Uri
    id : String [1]
    name : String
    @baseType : String
    @referredType : String
    @schemaLocation : Uri
    @type : String
}

class AttachmentRef  <<Ref>> {
    description : String
    href : Uri
    id : String [1]
    name : String
    url : Uri
    @baseType : String
    @referredType : String
    @schemaLocation : Uri
    @type : String
}

class ServiceLevelAgreementRef  <<Ref>> {
    description : String
    href : Uri
    id : String [1]
    name : String
    @baseType : String
    @referredType : String
    @schemaLocation : Uri
    @type : String
}

class RelatedParty  {
    href : Uri
    id : String [1]
    name : String
    role : String
    @baseType : String
    @referredType : String [1]
    @schemaLocation : Uri
    @type : String
}

ServiceLevelAgreementViolation *-->  "0..*" RelatedParty : relatedParty

ServiceLevelAgreementViolation *-->  "0..1" ServiceLevelAgreementRef : serviceLevelAgreement

ServiceLevelAgreementViolation *-->  "0..1" Violation : violation

Violation *-->  "0..1" RuleRef : rule

Violation *-->  "0..1" AttachmentRef : attachment

@enduml