= Account

[#domain]
== Domain

This schema is part of EngagedParty

[#description]
== Description

Generic Account structure used to define commonalities between sub concepts of PartyAccount and Financial Account.


[#data_model]
== Data model

A JSON Schema corresponding to this data model can be found https://tmforum.org[here].

The data model is defined as shown below:


=== creditLimit
description: The maximum amount of money that may be charged on an account

$ref of: xref:v4.0@schemas:EngagedParty:Money.adoc[]


=== description
description: Detailed description of the party account

type: string


=== href
description: Unique reference of the account

type: string


=== id
description: Unique identifier of the account

type: string


=== lastModified
description: Date of last modification of the account

type: string


=== name
description: Name of the account

type: string


=== state
description: Contains the lifecycle state such as: Active, Closed, Suspended and so on.

type: string


=== accountType
description: A categorization of an account, such as individual, joint, and so forth, whose instances share some of the same characteristics. Note: for flexibility we use a String here but an implementation may use an enumeration with a limited list of valid values.

type: string


=== relatedParty
type: array


=== taxExemption
type: array


=== contact
type: array


=== accountBalance
type: array


=== accountRelationship
type: array


= All Of 
This schema extends: xref:v4.0@schemas:EngagedParty:Entity.adoc[]
