= BankAccountTransferMethod

[#domain]
== Domain

This schema is part of EngagedParty

[#description]
== Description

No description on schema


[#data_model]
== Data model

A JSON Schema corresponding to this data model can be found https://tmforum.org[here].

The data model is defined as shown below:


=== details
$ref of: xref:v4.0@schemas:EngagedParty:BankAccountTransferDetails.adoc[]


=== description
description: Text describing the contents of the payment method

type: string


=== href
description: A resource URI pointing to the resource in the server that stores the detailed information. This is typically the resource url to retrieve individual details for the specific payment method

type: string


=== id
description: Unique Identifier within the server for the payment method.

type: string


=== name
description: Friendly name assigned to the payment method

type: string


=== preferred
description: If the method is the preferred one by the owner. Typically used when querying for the payment methods of a specific customer or account

type: boolean


=== status
type: string


=== statusDate
type: string


=== validFor
description: Date interval in which the payment method is valid

$ref of: xref:v4.0@schemas:EngagedParty:TimePeriod.adoc[]


=== relatedParty
$ref of: xref:v4.0@schemas:EngagedParty:RelatedParty.adoc[]


=== account
type: array


= All Of 
This schema extends: xref:v4.0@schemas:EngagedParty:Entity.adoc[]
