= CheckWorkQualificationItem

[#domain]
== Domain

This schema is part of EngagedParty

[#description]
== Description

A WorkQualificationItem relates to a specific unit of work being checked in a qualification operation.


[#data_model]
== Data model

A JSON Schema corresponding to this data model can be found https://tmforum.org[here].

The data model is defined as shown below:


=== alternateWorkProposal
type: array


=== eligibilityUnavailabilityReason
type: array


=== qualificationItemRelationship
type: array


=== qualificationRelationship
type: array


=== qualificationResult
description: Qualification result for workQualification item. It could be: - qualified (requested unit of work is valid), - unqualified (requested unit of work not valid and not alternative available), - alternate (requested unit of work not valid but alternate proposal available)

type: string


=== state
description: State of the qualification item (acknowledged, inProgress, terminatedWithError, done)

type: string


=== terminationError
description: If qualificationItem has not been done properly this lists the error(s) that caused termination of the qualification.

type: array


= All Of 
This schema extends: xref:v4.1@schemas:EngagedParty:WorkQualificationItem.adoc[]
