= Individual

[#domain]
== Domain

This schema is part of EngagedParty

[#description]
== Description

Individual represents a single human being (a man, woman or child). The individual can be a customer, an employee or any other person that the organization needs to store information about.


[#data_model]
== Data model

A JSON Schema corresponding to this data model can be found https://tmforum.org[here].

The data model is defined as shown below:


=== gender
description: Gender

type: string


=== placeOfBirth
description: Reference to the place where the individual was born

type: string


=== countryOfBirth
description: Country where the individual was born

type: string


=== nationality
description: Nationality

type: string


=== maritalStatus
description: Marital status (married, divorced, widow ...)

type: string


=== birthDate
description: Birth date

type: string


=== deathDate
description: Date of death

type: string


=== title
description: Useful for titles (aristocratic, social,...) Pr, Dr, Sir, ...

type: string


=== aristocraticTitle
description: e.g. Baron, Graf, Earl,…

type: string


=== generation
description: e.g.. Sr, Jr, III (the third),…

type: string


=== givenName
description: First name of the individual

type: string


=== preferredGivenName
description: Contains the chosen name by which the individual prefers to be addressed. Note: This name may be a name other than a given name, such as a nickname

type: string


=== familyNamePrefix
description: Family name prefix

type: string


=== familyName
description: Contains the non-chosen or inherited name. Also known as last name in the Western context

type: string


=== legalName
description: Legal name or birth name (name one has for official purposes)

type: string


=== middleName
description: Middles name or initial

type: string


=== fullName
description: Full name flatten (first, middle, and last names)

type: string


=== formattedName
description: A fully formatted name in one string with all of its pieces in their proper place and all of the necessary punctuation. Useful for specific contexts (Chinese, Japanese, Korean,…)

type: string


=== location
description: Temporary current location od the individual (may be used if the individual has approved its sharing)

type: string


=== status
description: Status of the individual

$ref of: xref:v4.2@schemas:EngagedParty:IndividualStateType.adoc[]


=== otherName
type: array


=== individualIdentification
type: array


=== disability
type: array


=== languageAbility
type: array


=== skill
type: array


[#all_of]
== All Of

This schema extends: xref:v4.2@schemas:EngagedParty:Party.adoc[]
This schema extends: xref:v4.2@schemas:EngagedParty:Entity.adoc[]
