= LanguageAbility

[#domain]
== Domain

This schema is part of EngagedParty

[#description]
== Description
Ability of an individual to understand or converse in a language.


[#data_model]
== Data model

A JSON Schema corresponding to this data model can be found https://tmforum.org[here].

The data model is defined as shown below:


=== languageCode
description: Language code (RFC 5646)

type: string


=== languageName
description: Language name

type: string


=== isFavouriteLanguage
description: A “true” value specifies whether the language is considered by the individual as his favourite one

type: boolean


=== writingProficiency
description: Writing proficiency evaluated for this language

type: string


=== readingProficiency
description: Reading proficiency evaluated for this language

type: string


=== speakingProficiency
description: Speaking proficiency evaluated for this language

type: string


=== listeningProficiency
description: Listening proficiency evaluated for this language

type: string


=== validFor
$ref of: xref:4.0.0@schemas:EngagedParty:TimePeriod.adoc[]

