= RelatedWorkOrderItem

[#domain]
== Domain

This schema is part of EngagedParty

[#description]
== Description

RelatedWorkOrderItem (WorkOrder item). The work order item which triggered this unit of work&#x27;s creation/change/termination.


[#data_model]
== Data model

A JSON Schema corresponding to this data model can be found https://tmforum.org[here].

The data model is defined as shown below:


=== @referredType
description: The actual type of the target instance when needed for disambiguation.

type: string


=== orderItemAction
description: Action of the order item for this unit of work


type: string


=== orderItemId
description: Identifier of the work order item where the unit of work was managed

type: string


=== role
description: Role of the work order item for this unitof work


type: string


=== workOrderHref
description: Reference of the related entity.

type: string


=== workOrderId
description: Unique identifier of a related entity.

type: string


= All Of 
This schema extends: xref:4.0.0@schemas:EngagedParty:Extensible.adoc[]
