= ServiceLevelAgreementSpecification

[#domain]
== Domain

This schema is part of EngagedParty

[#description]
== Description

A specification that can be used when instantiating a service level agreement (SLA)


[#data_model]
== Data model

A JSON Schema corresponding to this data model can be found https://tmforum.org[here].

The data model is defined as shown below:


=== description
description: A narrative that explains in detail what the agreement specification is about

type: string


=== isBundle
description: If true, this agreement specification is a grouping of other agreement specifications. The list of bundled agreement specifications is provided by the agreementSpecificationRelationship property

type: boolean


=== lastUpdate
description: Date and time of the last update

type: string


=== lifecycleStatus
description: Indicates the current lifecycle status

type: string


=== name
description: Name of the agreement specification

type: string


=== validFor
description: The period for which the agreement specification is valid

$ref of: xref:v4.0@schemas:EngagedParty:TimePeriod.adoc[]


=== version
description: Agreement specification version

type: string


=== category
description: The category of product/services that are in scope of this SLA

$ref of: xref:v4.0@schemas:EngagedParty:EntityRef.adoc[]


=== specCharacteristic
description: List of characteristics that the SLA can take

type: array


=== template
description: the template document correponding with this SLA specifiction

$ref of: xref:v4.0@schemas:EngagedParty:ServiceLevelAgreementTemplate.adoc[]


=== itemSpecification
description: Service Level Agreement (SLA) item specification

type: array


=== relatedParty
description: Parties who manage or otherwise have an interest in this specification

type: array


=== attachment
description: Attachments that may be of relevance to this specification, such as picture, document, media

type: array


=== constraint
description: This is a list of constraint references applied to this specification

type: array


=== agreementSpecificationRelationship
description: Relationship to another agreement

type: array


=== entitySpecRelationship
description: Relationship to another entity specification

type: array


= All Of 
This schema extends: xref:v4.0@schemas:EngagedParty:Entity.adoc[]
