= ShippingOrderItem

[#domain]
== Domain

This schema is part of EngagedParty

[#description]
== Description

A list of shipping order items


[#data_model]
== Data model

A JSON Schema corresponding to this data model can be found https://tmforum.org[here].

The data model is defined as shown below:


=== id
description: Identifier of the Shipping Order Item

type: string


=== action
description: The action to be carried out on the Product. Can be: add, modify, delete, noChange

$ref of: xref:v4.0@schemas:EngagedParty:ShippingOrderItemActionType.adoc[]


=== productOrderItem
description: The product order item for which the shipping order is created, if supplied as input the attribute id must be populated

$ref of: xref:v4.0@schemas:EngagedParty:ProductOrderItemRef.adoc[]


=== product
description: The product for which the shipping order is created, if supplied as input the attribute id must be populated

$ref of: xref:v4.0@schemas:EngagedParty:ProductRef.adoc[]


=== relatedParty
description: A party which is involved in this shipment and the role they are playing and address. In case of shipping to addresses where a geo location is needed than then PlaceTo,PlaceFrom can be used.

type: array


=== quantity
description: Quantity the individual shipment line item

type: string


=== status
description: status of shipping order item. e.g &quot;active&quot; , &quot;savedForLater&quot;

type: string


=== shippingInstruction
description: Shipping instructions, usually relevant for the carrier.

$ref of: xref:v4.0@schemas:EngagedParty:ShippingInstruction.adoc[]


=== shippingOrderItemOffering
description: Each shipping order item can have a corresponding product offer in the product catalog.

$ref of: xref:v4.0@schemas:EngagedParty:ProductOfferingRef.adoc[]


=== productOffering
description: Item has a corresponding offering in the product catalog.

$ref of: xref:v4.0@schemas:EngagedParty:ProductOfferingRef.adoc[]


=== shipment
description: A set of goods to be shipped

$ref of: xref:v4.0@schemas:EngagedParty:ShipmentRefOrValue.adoc[]


=== shippingOrderItemPrice
description: Shipping Order Item price. The price of shipping this item. It depends if there is a ShippingOrder level price or per each individual item.

$ref of: xref:v4.0@schemas:EngagedParty:ProductPrice.adoc[]


=== placeFrom
description: Source location of the item. E.g. warehouse or shop location

$ref of: xref:v4.0@schemas:EngagedParty:RelatedPlaceRefOrValue.adoc[]


=== placeTo
description: Destination of the item. E.g. customer home address. 

$ref of: xref:v4.0@schemas:EngagedParty:RelatedPlaceRefOrValue.adoc[]


[#all_of]
== All Of

This schema extends: xref:v4.0@schemas:EngagedParty:Entity.adoc[]
