= ShipmentSpecification

[#domain]
== Domain

This schema is part of EngagedParty

[#description]
== Description

Definition of the nature of a Shipment. For example, could be a standard ground delivery, overnight express with signature required by an adult, etc.


[#data_model]
== Data model

A JSON Schema corresponding to this data model can be found https://tmforum.org[here].

The data model is defined as shown below:


=== description
description: Description of this REST resource

type: string


=== lastUpdate
description: Date and time of the last update of this REST resource

type: string


=== lifecycleStatus
description: Used to indicate the current lifecycle status of this catalog item

type: string


=== name
description: Name given to this REST resource

type: string


=== isBundle
description: isBundle determines whether an ShipmentSpecification represents a single ShipmentSpecification (false), or a bundle of ShipmentSpecification (true).

type: boolean


=== version
description: Entity specification version

type: string


=== constraint
description: This is a list of constraint references applied to this specification


type: array


=== targetShipmentSchema
description: Pointer to a schema that defines the target shipment

$ref of: xref:v4.1@schemas:EngagedParty:TargetShipmentSchema.adoc[]


=== attachment
description: Attachments that may be of relevance to this specification, such as picture, document, media


type: array


=== shipmentSpecificationCharacteristic
description: List of characteristics that the shipment can take

type: array


=== relatedParty
description: Parties who manage or otherwise have an interest in this shipment specification

type: array


=== validFor
description: The period for which this REST resource is valid

$ref of: xref:v4.1@schemas:EngagedParty:TimePeriod.adoc[]


=== shipmentSpecRelationship
description: Relationship to another shipment specification, might be dependency, substitution, etc.


type: array


[#all_of]
== All Of

This schema extends: xref:v4.1@schemas:EngagedParty:Entity.adoc[]
