= ShipmentItem

[#domain]
== Domain

This schema is part of EngagedParty

[#description]
== Description
No description on schema


[#data_model]
== Data model

A JSON Schema corresponding to this data model can be found https://tmforum.org[here].

The data model is defined as shown below:


=== id
description: Identifier of the individual shipment line item

type: string


=== action
description: The action to be carried out on the shipment item. Can be: add, modify, delete, noChange

$ref of: xref:4.0.0@schemas:EngagedParty:ShipmentItemActionType.adoc[]


=== quantity
description: Quantity the individual shipment line item

type: string


=== sku
description: SKU (Stock Keeping Unit) is a unique code that you use to identify every inventory item in your warehouse

type: string


=== weight
description: Weight of the shipping item package/parcel

$ref of: xref:4.0.0@schemas:EngagedParty:Quantity.adoc[]


=== productReservationRef
$ref of: xref:4.0.0@schemas:EngagedParty:ReserveProductStockRef.adoc[]


=== productStockRef
$ref of: xref:4.0.0@schemas:EngagedParty:ProductStockRef.adoc[]


=== externalIdentifier
description: An identification of an entity that is owned by or originates in a software system different from the current system, for example a ProductOrder handed off from a commerce platform into an order handling system. The structure identifies the system itself, the nature of the entity within the system (e.g. class name) and the unique ID of the entity within the system. It is anticipated that multiple external IDs can be held for a single entity, e.g. if the entity passed through multiple systems on the way to the current system. In this case the consumer is expected to sequence the IDs in the array in reverse order of provenance, i.e. most recent system first in the list.

type: array


=== shipmentItemPrice
description: Item price details

$ref of: xref:4.0.0@schemas:EngagedParty:Price.adoc[]


=== characteristic
description: List of characteristics with values that define the test run

type: array


=== product
description: This data structure captures the product information.

$ref of: xref:4.0.0@schemas:EngagedParty:ProductRefOrValue.adoc[]

