= WorkSpecificationRelationship

[#domain]
== Domain

This schema is part of EngagedParty

[#description]
== Description

A migration, substitution, dependency or exclusivity relationship between/among entity specifications.


[#data_model]
== Data model

A JSON Schema corresponding to this data model can be found https://tmforum.org[here].

The data model is defined as shown below:


=== @referredType
description: The actual type of the target instance when needed for disambiguation.

type: string


=== associationSpec
description: A specification for an association used by this relationship


$ref of: xref:v4.2@schemas:EngagedParty:AssociationSpecificationRef.adoc[]


=== name
description: The name given to the target entity specification instance

type: string


=== relationshipType
description: Type of relationship such as migration, substitution, dependency, exclusivity

type: string


=== role
description: The association role for this entity specification

type: string


=== validFor
description: The period for which this REST resource is valid

$ref of: xref:v4.2@schemas:EngagedParty:TimePeriod.adoc[]


= All Of 
This schema extends: xref:v4.2@schemas:EngagedParty:Entity.adoc[]
