@startuml
hide circle
hide methods
hide stereotype
show <<Enumeration>> stereotype
skinparam class {
   BackgroundColor<<Enumeration>> #E6F5F7
   BackgroundColor<<Ref>> #FFFFE0
   BackgroundColor<<Pivot>> #FFFFFFF
   BackgroundColor<<SimpleType>> #E2F0DA
   BackgroundColor #FCF2E3
}

class TroubleTicket <<Pivot>> {
    creationDate : DateTime
    description : String
    expectedResolutionDate : DateTime
    externalId : String
    href : String
    id : String
    lastUpdate : DateTime
    name : String
    priority : String
    requestedResolutionDate : DateTime
    resolutionDate : DateTime
    severity : String
    status : TroubleTicketStatusType
    statusChangeDate : DateTime
    statusChangeReason : String
    ticketType : String
    @baseType : String
    @schemaLocation : Uri
    @type : String
}

class Note  {
    author : String
    date : DateTime
    id : String
    text : String
    @baseType : String
    @schemaLocation : Uri
    @type : String
}

class TroubleTicketRelationship  <<Ref>> {
    href : String
    id : String
    name : String
    relationshipType : String
    @baseType : String
    @schemaLocation : Uri
    @type : String
}

class ChannelRef  <<Ref>> {
    href : Uri
    id : String [1]
    name : String
    @baseType : String
    @referredType : String
    @schemaLocation : Uri
    @type : String
}

class AttachmentRefOrValue  {
    attachmentType : String
    content : string/base64
    description : String
    href : Uri
    id : String
    mimeType : String
    name : String
    size : Quantity
    url : Uri
    validFor : TimePeriod
    @baseType : String
    @referredType : String
    @schemaLocation : Uri
    @type : String
}

class StatusChange  {
    changeDate : DateTime
    changeReason : String
    href : Uri
    id : String
    status : String
    @baseType : String
    @schemaLocation : Uri
    @type : String
}

class RelatedEntity  {
    href : Uri
    id : String [1]
    name : String
    role : String [1]
    @baseType : String
    @referredType : String [1]
    @schemaLocation : Uri
    @type : String
}

class RelatedParty  {
    href : Uri
    id : String [1]
    name : String
    role : String
    @baseType : String
    @referredType : String [1]
    @schemaLocation : Uri
    @type : String
}

class TroubleTicketStatusType <<Enumeration>> {
    acknowledged
    rejected
    pending
    held
    inProgress
    cancelled
    closed
    resolved
}

TroubleTicket -right[hidden]-> TroubleTicketStatusType

Note "0..*" <-left-* TroubleTicket : note

ChannelRef "0..1" <--* TroubleTicket : channel

AttachmentRefOrValue "0..*" <--* TroubleTicket : attachment

RelatedParty "0..*" <--* TroubleTicket : relatedParty

TroubleTicket *-->  "0..*" StatusChange : statusChange

TroubleTicket *-->  "0..*" TroubleTicketRelationship : troubleTicketRelationship

TroubleTicket *-->  "0..*" RelatedEntity : relatedEntity

@enduml