= GcAssociation

[#domain]
== Domain

This schema is part of Common

[#description]
== Description
Association is the class that describes a relationship between two or more entities or entity specifications based on a given association specification. The role of each endpoint in the relationship is given by an association role. The type of endpoints in the relationship should match the ones as defined in the corresponding association role specification. A relationship between entity specifications may be governed by conditions and rules which are addressed by constraint references in this resource. Constraints for a relationship may include new rules and conditions in addition to those defined for the corresponding association specification


[#data_model]
== Data model

A JSON Schema corresponding to this data model can be found //[here].

== Diagram:
aaa

The data model is defined as shown below:


=== associationRole
description: The end point roles of this association

type: array


=== name
description: Name given to this association

type: string


[#all_of]
== All Of

This schema extends: xref:v5.0@schemas:Gc:GcAddressable.adoc[]
This schema extends: xref:v5.0@schemas:Gc:GcExtensible.adoc[]
