= GcCommunicationMessage

[#domain]
== Domain

This schema is part of Common

[#description]
== Description

Communication message means a notification approach in the format of a message which can be dispatched (sent) to the certain user by the system with the content which can be felt and understood by the recipient. The user can be either a final customer or a customer service agent. The message can reach the customer in different interaction channels, including: email, short message, mobile app notification (push).


[#data_model]
== Data model

A JSON Schema corresponding to this data model can be found https://tmforum.org[here].

The data model is defined as shown below:


=== content
description: The content of the communication message

type: string


=== messageType
description: The type of message, such as: SMS, Email, Mobile app push notification

type: string


=== receiver
description: The receiver(s) of this message

type: array


=== sender
description: The sender of this message

$ref of: xref:4.0.0@schemas:Gc:Sender.adoc[]

