= GcGeographicSubAddress

[#domain]
== Domain

This schema is part of Common

[#description]
== Description
Representation of a GeographicSubAddress 
It is used for addressing within a property in an urban area (country properties are often defined differently). It may refer to a building, a building cluster, or a floor of a multistory building.


[#data_model]
== Data model

A JSON Schema corresponding to this data model can be found //[here].



The data model is defined as shown below:


=== levelNumber
description: used where a level type may be repeated e.g. BASEMENT 1, BASEMENT 2

type: string


=== levelType
description: describes level types within a building

type: string


=== privateStreetName
description: private streets internal to a property (e.g. a university) may have internal names that are not recorded by the land title office.

type: string


=== privateStreetNumber
description: private streets numbers internal to a private street

type: string


=== subAddressType
description: Type of subAddress : it can be a subunit or a private street

type: string


[#all_of]
== All Of

This schema extends: xref:v5.0@schemas:Core:Entity.adoc[]
