= GcGeographicAddress

[#domain]
== Domain

This schema is part of Common

[#description]
== Description
Structured textual way of describing how to find a Property in an urban area (country properties are often defined differently).
Note : Address corresponds to SID UrbanPropertyAddress


[#data_model]
== Data model

A JSON Schema corresponding to this data model can be found https://tmforum.org[here].

The data model is defined as shown below:


=== city
description: City that the address is in

type: string


=== country
description: Country that the address is in

type: string


=== geographicSubAddress
type: array


=== postcode
description: descriptor for a postal delivery area, used to speed and simplify the delivery of mail (also know as zipcode)

type: string


=== stateOrProvince
description: the State or Province that the address is in

type: string


=== streetName
description: Name of the street or other street type

type: string


=== streetNr
description: Number identifying a specific property on a public street. It may be combined with streetNrLast for ranged addresses

type: string


=== streetType
description: alley, avenue, boulevard, brae, crescent, drive, highway, lane, terrace, parade, place, tarn, way, wharf 

type: string

