= GcGeographicAddressValidation

[#domain]
== Domain

This schema is part of Common

[#description]
== Description
This resource is used to manage address validation request and response


[#data_model]
== Data model

A JSON Schema corresponding to this data model can be found //[here].

Diagram:


The data model is defined as shown below:


=== provideAlternative
description: Indicator provided by the requester to specify if alternate addresses must be provided in case of partial or fail result.

type: boolean


=== state
$ref of: xref:v5.0@schemas:Gc:TaskStateType.adoc[]


=== submittedGeographicAddress
description: the address as submitted to validation

$ref of: xref:v5.0@schemas:Gc:GeographicAddress.adoc[]


=== validationDate
description: Date when the address validation is performed

type: string


=== validationResult
description: Result of the address validation (success, partial, fails)

type: string


[#all_of]
== All Of

This schema extends: xref:v5.0@schemas:Core:Entity.adoc[]
