= GcResourceSpecification

[#domain]
== Domain

This schema is part of Resource

[#description]
== Description
Resources are physical or non-physical components (or some combination of these) within an enterprise&#x27;s infrastructure or inventory. They are typically consumed or used by services (for example a physical port assigned to a service) or contribute to the realization of a Product (for example, a SIM card). They can be drawn from the Application, Computing and Network domains, and include, for example, Network Elements, software, IT systems, content and information, and technology components.
A ResourceSpecification is a base class that represents a generic means for implementing a particular type of Resource. In essence, a ResourceSpecification defines the common attributes and relationships of a set of related Resources, while Resource defines a specific instance that is based on a particular ResourceSpecification.


[#data_model]
== Data model

A JSON Schema corresponding to this data model can be found https://tmforum.org[here].

The data model is defined as shown below:


=== lastUpdate
description: Date and time of the last update of this REST resource

type: string


=== lifecycleStatus
description: Used to indicate the current lifecycle status of the resource specification

type: string


=== name
description: Name given to this REST resource

type: string

