= GcServiceCandidate

[#domain]
== Domain

This schema is part of Service

[#description]
== Description

ServiceCandidate is an entity that makes a service specification available to a catalog. A
ServiceCandidate and its associated service specification may be published - made visible - in any number of service catalogs, or in none. One service specification can be composed of other service specifications.


[#data_model]
== Data model

A JSON Schema corresponding to this data model can be found https://tmforum.org[here].

The data model is defined as shown below:


=== lifecycleStatus
description: Used to indicate the current lifecycle status of the service candidate.

type: string


=== name
description: Name given to this REST resource

type: string


=== serviceSpecification
description: The service specification implied by this candidate

$ref of: xref:4.0.0@schemas:Gc:ServiceSpecificationRef.adoc[]


{&#x27;$ref&#x27;: &#x27;../../Gc/Common/GcAddressable.schema.json#GcAddressable&#x27;}{&#x27;$ref&#x27;: &#x27;../../Gc/Common/GcExtensible.schema.json#GcExtensible&#x27;}