= GcServiceCatalog

[#domain]
== Domain

This schema is part of Service

[#description]
== Description
The root entity for service catalog management.
A service catalog is a group of service specifications made available through service candidates that an organization provides to the consumers (internal consumers like its employees or B2B customers or B2C customers). 
A service catalog typically includes name, description and time period that is valid for. It will have a list of ServiceCandidate catalog items. A ServiceCandidate is an entity that makes a ServiceSpecification available to a catalog.
A ServiceCandidate and its associated ServiceSpecification may be &quot;published&quot; - made visible -in any number of ServiceCatalogs, or in none.


[#data_model]
== Data model

A JSON Schema corresponding to this data model can be found //[here].

== Diagram:
aaa

The data model is defined as shown below:


=== name
description: Name of the service catalog

type: string


[#all_of]
== All Of

This schema extends: xref:v5.0@schemas:Gc:GcAddressable.adoc[]
This schema extends: xref:v5.0@schemas:Gc:GcExtensible.adoc[]
