@startuml
hide circle
hide methods
hide stereotype
show <<Enumeration>> stereotype
skinparam class {
   BackgroundColor<<Enumeration>> #E6F5F7
   BackgroundColor<<Ref>> #FFFFE0
   BackgroundColor<<Pivot>> #FFFFFFF
   BackgroundColor<<SimpleType>> #E2F0DA
   BackgroundColor #FCF2E3
}

class AiContract <<Pivot>> {
    approvalDate : DateTime
    approved : Boolean
    description : String
    href : Uri
    id : String
    name : String
    state : String
    validFor : TimePeriod
    version : String
    @baseType : String
    @referredType : String
    @schemaLocation : Uri
    @type : String
}

class TemplateRef  <<Ref>> {
    description : String
    href : String
    id : String [1]
    name : String
    @baseType : String
    @referredType : String
    @schemaLocation : Uri
    @type : String
}

class Rule  {
    href : Uri
    id : String
    name : String
    @baseType : String
    @schemaLocation : Uri
    @type : String
}

class RelatedParty  {
    href : Uri
    id : String [1]
    name : String
    role : String
    @baseType : String
    @referredType : String [1]
    @schemaLocation : Uri
    @type : String
}

class Characteristic  {
    id : String
    name : String [1]
    value : Any [1]
    valueType : String
    @baseType : String
    @schemaLocation : Uri
    @type : String
}

class CharacteristicRelationship  <<Ref>> {
    href : Uri
    id : String
    relationshipType : String
    @baseType : String
    @schemaLocation : Uri
    @type : String
}

AiContract *-right-> "0..*" Rule : rule

TemplateRef "0..1" <--* AiContract : template

AiContract *-->  "0..*" RelatedParty : relatedParty

AiContract *-->  "0..*" Characteristic : characteristic

Characteristic *-->  "0..*" CharacteristicRelationship : characteristicRelationship

@enduml